"""Codex CLI — `AGENTS.md` natively, `.codex/` for everything else.

Codex loads a project's `.codex/` only once the project is trusted.
"""

from __future__ import annotations

from pf.harness import SKILLS_CELL, Harness, Server, toml_str
from pf.harnesses.base import Ctx, Spec


def render_codex(svs: list[Server]) -> str:
    """`.codex/config.toml`: the servers, the protocol, and a sandbox that can write.

    Only our servers. The reference config this shape comes from lists six
    third-party `npx` servers; a data platform's MCP surface is its graph and
    its warehouse tools, and every extra server is context every session pays
    for. `persistent_instructions` is additive to `AGENTS.md`, which Codex reads
    natively — it is the one line that survives a Codex update.
    """
    lines = [
        "#:schema https://developers.openai.com/codex/config-schema.json",
        "# GENERATED by `pf context refresh` from .mcp.json — do not hand-edit.",
        "# Codex has no tool hooks: gate.yaml is enforced at commit by",
        "# platform/hooks/pre_commit.sh (`pf install-hook`), and by you before that",
        "# with `uv run pf gate --paths <files>`. See docs/HARNESSES.md.",
        "",
        'approval_policy = "on-request"',
        'sandbox_mode = "workspace-write"',
        "",
        "persistent_instructions = "
        + toml_str(
            "Follow AGENTS.md. Section 0 names your scope (Session). Ask the graph "
            "before reading files (kg_search, impact_analysis). Run `uv run pf gate "
            "--paths <files>` before committing; never pass --no-verify."
        ),
        "",
    ]
    for s in svs:
        s = s.with_project(None)
        lines.append(f"[mcp_servers.{s.name}]")
        lines.append(f"command = {toml_str(s.command)}")
        lines.append("args = [" + ", ".join(toml_str(a) for a in s.args) + "]")
        if s.env:
            lines.append("env = { " + ", ".join(f"{k} = {toml_str(v)}" for k, v in s.env) + " }")
        lines.append("startup_timeout_sec = 30")
        lines.append("")
    return "\n".join(lines)


def _render(ctx: Ctx) -> dict[str, str]:
    return {".codex/config.toml": render_codex(ctx.servers)}


SPEC = Spec(
    key="codex",
    label="Codex",
    order=10,
    rows=(
        Harness(
            "Codex CLI",
            "`AGENTS.md`, natively",
            "`.codex/config.toml`",
            "none — commit gate only",
            "pre-commit",
            "none",
            "rule — `pf memory show`",
            "rule — `AGENTS.md` §1",
            SKILLS_CELL,
        ),
    ),
    render=_render,
    owner="Codex CLI",
)
