"""Codex CLI — `AGENTS.md` natively, `.codex/` for everything else.

    .codex/config.toml      the MCP servers, the sandbox, one line of protocol
    .codex/hooks.json       SessionStart / PreToolUse / PostToolUse / Stop →
                            `agent_hook.py codex <event>`: the gate before every
                            Bash and apply_patch, provenance, the turn-one context
    .codex/rules/pf.rules   the `ask` list as `prefix_rule(..., decision="prompt")`,
                            so Codex asks a person for `git push` itself
    .codex/agents/*.toml    the power-tools reviewers, `sandbox_mode = "read-only"`

Every file edit Codex makes is one `apply_patch` whose body arrives in
`tool_input.command`; the adapter reads each `*** Add/Update/Delete File:` line,
and one denied path refuses the whole patch.

Codex loads a project's `.codex/` — all four — only once the project is trusted.
"""

from __future__ import annotations

import json

from pf.agenthook import BASH, EDIT, WRITE
from pf.harness import SKILLS_CELL, Harness, Server, claude_style_hooks, json_text, toml_str
from pf.harness_adapters import Adapter, claude_parse, exit2, generic_ok, hook_specific, native_ask
from pf.harness_assets import Doc, readonly
from pf.harnesses.base import Ctx, Spec


def render_codex(svs: list[Server]) -> str:
    """`.codex/config.toml`: the servers, the protocol, and a sandbox that can write.

    Only our servers. The reference config this shape comes from lists six
    third-party `npx` servers; a data platform's MCP surface is its graph and
    its warehouse tools, and every extra server is context every session pays
    for. `persistent_instructions` is additive to `AGENTS.md`, which Codex reads
    natively — it is the one line that survives a Codex update.
    """
    lines = [
        "#:schema https://developers.openai.com/codex/config-schema.json",
        "# GENERATED by `pf context refresh` from .mcp.json — do not hand-edit.",
        "# The gate runs from .codex/hooks.json (PreToolUse on Bash and apply_patch);",
        "# a person approves what .codex/rules/pf.rules marks `prompt`. Codex loads",
        "# both only for a trusted project. See docs/HARNESSES.md.",
        "",
        'approval_policy = "on-request"',
        'sandbox_mode = "workspace-write"',
        "",
        "persistent_instructions = "
        + toml_str(
            "Follow AGENTS.md. Section 0 names your scope (Session). Ask the graph "
            "before reading files (kg_search, impact_analysis). A hook refusal is a "
            "finding: report it, never re-route it. Never pass --no-verify."
        ),
        "",
    ]
    for s in svs:
        s = s.with_project(None)
        lines.append(f"[mcp_servers.{s.name}]")
        lines.append(f"command = {toml_str(s.command)}")
        lines.append("args = [" + ", ".join(toml_str(a) for a in s.args) + "]")
        if s.env:
            lines.append("env = { " + ", ".join(f"{k} = {toml_str(v)}" for k, v in s.env) + " }")
        lines.append("startup_timeout_sec = 30")
        lines.append("")
    return "\n".join(lines)


def render_hooks() -> str:
    """`.codex/hooks.json`: Claude's schema, which Codex reads as-is. The
    `Edit`/`Write` matchers alias `apply_patch`; naming all three costs
    nothing if a release stops aliasing."""
    return json_text(claude_style_hooks("codex", "Bash|apply_patch|Edit|Write"))


def render_rules(asks: list[str]) -> str:
    """`.codex/rules/pf.rules`: Codex prompts a person for these itself. The
    hook stands aside for `ask` in Codex, because refusing would pre-empt
    exactly this prompt."""
    lines = [
        "# GENERATED by `pf context refresh` from .claude/settings.json `ask` — do not hand-edit.",
        "# Loaded only for a trusted project, like .codex/hooks.json.",
        "",
    ]
    for prefix in asks:
        words = ", ".join(json.dumps(w) for w in prefix.split())
        lines.append(
            f'prefix_rule(pattern=[{words}], decision="prompt", '
            f'justification="a person approves `{prefix}` here (.claude/settings.json ask)")'
        )
    return "\n".join(lines) + "\n"


def render_agent(doc: Doc) -> str:
    """`.codex/agents/<name>.toml`: the body is `developer_instructions`;
    read-only is the sandbox, not a request."""

    def s(v: str) -> str:
        return json.dumps(v, ensure_ascii=False)

    lines = [
        f"# GENERATED by `pf context refresh` from {doc.src} — do not hand-edit.",
        f"name = {s(doc.name)}",
        f"description = {s(doc.description)}",
    ]
    if readonly(doc):
        lines.append('sandbox_mode = "read-only"')
    if doc.meta.get("effort") in ("low", "medium", "high"):
        lines.append(f"model_reasoning_effort = {s(str(doc.meta['effort']))}")
    lines.append(f"developer_instructions = {s(doc.body)}")
    return "\n".join(lines) + "\n"


def _render(ctx: Ctx) -> dict[str, str]:
    return {
        ".codex/config.toml": render_codex(ctx.servers),
        ".codex/hooks.json": render_hooks(),
        ".codex/rules/pf.rules": render_rules(ctx.asks),
    }


SPEC = Spec(
    key="codex",
    label="Codex",
    order=10,
    rows=(
        Harness(
            "Codex CLI",
            "`AGENTS.md`, natively",
            "`.codex/config.toml`",
            "hook — trusted project only",
            "pre-commit",
            "hooks write stages 01–03",
            "injected on turn one",
            "SessionStart hook",
            SKILLS_CELL,
            "`.codex/agents/`",
            ".codex/hooks.json",
            "codex",
        ),
    ),
    render=_render,
    owner="Codex CLI",
    adapter=Adapter(
        parse=claude_parse("codex"),
        deny=exit2,
        # PreToolUse cannot carry advice without claiming a decision some
        # releases reject; the blast radius arrives on PostToolUse instead.
        allow=lambda v: hook_specific("PostToolUse", v.message),
        ask=native_ask,
        context=hook_specific,
        ok=generic_ok,
    ),
    tools={"apply_patch": EDIT, "Edit": EDIT, "Write": WRITE, "Bash": BASH, "shell": BASH},
    defer_advice=True,
    agents={".codex/agents/{}.toml": render_agent},
    caveats=(
        "- **Codex** loads `.codex/` — hooks, rules, MCP — only for a trusted project.",
        "  Trust the checkout once when Codex asks. Untrusted, it has the commit gate only.",
    ),
    launch="codex",
)
