"""OpenCode — `AGENTS.md` through `opencode.json`; its hooks are a plugin.

    .opencode/opencode.json          the protocol, the MCP servers, the `ask`
                                     list as `permission.bash` (OpenCode prompts),
                                     and any local model providers a module
                                     contributes (`Spec.providers`)
    .opencode/plugins/pf-gate.js     tool.execute.before / after, the system
                                     prompt, session.idle →
                                     `agent_hook.py opencode <event>`
    .opencode/agents/*.md            the power-tools reviewers as subagents,
                                     `permission: {edit: deny}` when read-only

The plugin is a shim — every decision is the core's. Exit 2 becomes a thrown
error, which is how OpenCode refuses a tool; the model sees the message.
OpenCode is also the harness that drives a local model (Qwen on mlx), and
whatever model it drives, this is the gate.
"""

from __future__ import annotations

from typing import Any

from pf.agenthook import BASH, EDIT, READ, WRITE, Call
from pf.harness import SKILLS_CELL, Harness, Server, json_text
from pf.harness_adapters import Adapter, call, exit2, first, generic_ok, native_ask, obj
from pf.harness_assets import Doc, frontmatter, generated_note, readonly
from pf.harnesses.base import Ctx, Spec


def render_opencode(svs: list[Server], asks: list[str] | None = None) -> str:
    """`.opencode/opencode.json`. Listing a provider selects nothing: the
    default model stays the person's."""
    from pf.harnesses import specs

    mcp: dict[str, Any] = {}
    for s in svs:
        s = s.with_project(None)
        spec: dict[str, Any] = {"type": "local", "command": [s.command, *s.args], "enabled": True}
        if s.env:
            spec["environment"] = dict(s.env)
        mcp[s.name] = spec
    out: dict[str, Any] = {
        "$schema": "https://opencode.ai/config.json",
        "instructions": ["AGENTS.md"],
        "mcp": mcp,
        # A person approves these, in OpenCode's own prompt: the same `ask`
        # list `.claude/settings.json` gives Claude Code.
        "permission": {"bash": {f"{prefix}*": "ask" for prefix in (asks or [])}},
    }
    providers = {k: v for sp in specs() for k, v in sp.providers.items()}
    if providers:
        out["provider"] = providers
    return json_text(out)


PLUGIN = """// GENERATED by `pf context refresh` from platform/src/pf/harnesses/opencode.py — do not hand-edit.
// Every decision is platform/hooks/agent_hook.py; this file only carries
// OpenCode's events to it and its answers back.
import { spawnSync } from "node:child_process";

export const PfGate = async ({ directory, worktree }) => {
  const root = worktree || directory;
  const hook = (event, payload) =>
    spawnSync(
      "uv",
      ["run", "--quiet", "--project", root, "python", `${root}/platform/hooks/agent_hook.py`,
       "opencode", event],
      {
        input: JSON.stringify({ cwd: directory, ...payload }),
        encoding: "utf8",
        env: { ...process.env, PF_AGENT: process.env.PF_AGENT || "opencode" },
      },
    );
  const context = new Map();
  return {
    "tool.execute.before": async (input, output) => {
      const r = hook("pre", { tool: input.tool, args: output.args, sessionID: input.sessionID, callID: input.callID });
      if (r.status === 2) throw new Error((r.stderr || "refused by gate.yaml").trim());
    },
    "tool.execute.after": async (input, output) => {
      const r = hook("post", {
        tool: input.tool, args: input.args, sessionID: input.sessionID, callID: input.callID, output: output?.output,
      });
      const advice = (r.stdout || "").trim();
      if (advice && output && typeof output.output === "string") output.output += `\\n\\n${advice}`;
    },
    "experimental.chat.system.transform": async (input, output) => {
      const sid = input?.sessionID || "";
      if (!context.has(sid)) context.set(sid, (hook("session", { sessionID: sid }).stdout || "").trim());
      if (context.get(sid)) output.system.push(context.get(sid));
    },
    event: async ({ event }) => {
      if (event?.type === "session.idle") hook("stop", { sessionID: event.properties?.sessionID || "" });
    },
  };
};
"""


def render_agent(doc: Doc) -> str:
    fields: dict[str, Any] = {"description": doc.description, "mode": "subagent"}
    if readonly(doc):
        fields["permission"] = {"edit": "deny"}
    if isinstance(doc.meta.get("maxTurns"), int):
        fields["steps"] = doc.meta["maxTurns"]
    return frontmatter(fields) + generated_note(doc) + doc.body


def parse(p: dict[str, Any]) -> Call:
    return call("opencode", p, first(p, "tool"), obj(p.get("args")), first(p, "callID"))


def _render(ctx: Ctx) -> dict[str, str]:
    return {
        ".opencode/opencode.json": render_opencode(ctx.servers, ctx.asks),
        ".opencode/plugins/pf-gate.js": PLUGIN,
    }


SPEC = Spec(
    key="opencode",
    label="OpenCode",
    order=50,
    rows=(
        Harness(
            "OpenCode",
            "`AGENTS.md` via `opencode.json`",
            "`.opencode/opencode.json`",
            "hook — plugin",
            "pre-commit",
            "hooks write stages 01–03",
            "injected into the system prompt",
            "plugin",
            SKILLS_CELL,
            "`.opencode/agents/`",
            ".opencode/plugins/pf-gate.js",
            "opencode",
        ),
    ),
    render=_render,
    owner="OpenCode",
    # The plugin turns exit 2 into a thrown error, stdout on post into text
    # appended to the tool's output, stdout on session into a system entry.
    adapter=Adapter(
        parse=parse,
        deny=exit2,
        allow=lambda v: (v.message, "", 0),
        ask=native_ask,
        context=lambda ev, text: (text, "", 0),
        ok=generic_ok,
    ),
    tools={"edit": EDIT, "write": WRITE, "apply_patch": EDIT, "patch": EDIT, "bash": BASH, "read": READ},
    defer_advice=True,
    agents={".opencode/agents/{}.md": render_agent},
    launch="opencode",
)
