{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `yahoo_finance.fx_rates` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: FxRate · Grain: one currency pair per day
#}

with renamed as (
    select
        {{ pf_clean('fx_rate_id', 'natural_key') }} as fx_rate_id,
        {{ pf_clean('base_currency', 'currency_code') }} as base_currency_code,
        {{ pf_clean('quote_currency', 'currency_code') }} as quote_currency_code,
        {{ pf_clean('rate', 'exchange_rate') }} as rate,
        {{ pf_clean('rate_date', 'event_time') }} as rate_at,
        _dlt_load_id
    from {{ source('yahoo_finance', 'fx_rates') }}
)

select * exclude (_dlt_load_id)
from renamed
where fx_rate_id is not null
{{ pf_dedupe('fx_rate_id') }}
