"""One CI workflow per project, composed from what its capabilities declare.

Why a master workflow rather than a file per capability: every capability that
wanted CI used to ship a whole `.github/workflows/<thing>-<project>.yml`. With
two capabilities and eight projects that is sixteen files, each repeating its own
`on:` block, its own path filter, its own checkout and its own `uv sync`, and
each answering "did this PR touch my project?" separately. Nobody could see a
project's CI in one place, and adding a third capability meant a third file per
project.

Now a capability declares a **job**, and this module composes the workflow. One
file per project, named after the project, holding every job that project runs.

The contract between the two halves is the `changes` job below. It runs once,
diffs the PR against its base, and publishes a boolean per area. Every
contributed job guards itself on those outputs, so a change to one project's
reporting layer does not start its dbt review. A capability that needs a new area
adds it to `CHANGE_AREAS`; nothing else moves.

Jobs are contributed as YAML text rather than as a structure that gets dumped:
these files are read far more often than they are written, and a hand-written
block keeps its comments and its ordering. A YAML round-trip loses both.
"""

from __future__ import annotations

# Area -> the path under the project directory that defines it. A job guards on
# `needs.changes.outputs.<area>`. Ordering is only for the generated file's
# readability; the names are the API.
CHANGE_AREAS: dict[str, str] = {
    "models": "transform/models",
    "sources": "src",
    "transform": "transform",
    "reporting": "reporting",
    "any": "",
}

WORKFLOW_HEADER = """\
# GENERATED by `pf bootstrap`. Every CI job {{group}}/{{project}} runs, in one
# place. Do not hand-edit: the next bootstrap regenerates it, and the edit is
# lost. Change the capability that contributes the job instead — `pf.capabilities`
# for platform features, `pf.tools.<tool>` for a tool.
#
# The `changes` job diffs the PR once and publishes one boolean per area; every
# job below guards on it, so touching a page never starts a dbt review. Adding a
# capability adds a job here and nothing else.
name: {{project}}

on:
  pull_request:
    paths:
      - "groups/{{group}}/projects/{{project}}/**"

# One run per PR per project. A push that supersedes an in-flight run cancels it
# rather than racing it — two builds of the same project writing the same
# baseline is how a review compares against the wrong state.
concurrency:
  group: {{project}}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
{{change_outputs}}
    steps:
      - uses: actions/checkout@v4
        with:
          # The diff is against the merge base, which a shallow clone does not
          # have. Every job below depends on this being right.
          fetch-depth: 0
      - id: areas
        run: |
          P="groups/{{group}}/projects/{{project}}"
          BASE="origin/${{ github.base_ref }}"
          touched() {
            if [ -n "$(git diff --name-only "$BASE"...HEAD -- "$1")" ]; then
              echo true
            else
              echo false
            fi
          }
{{change_steps}}
"""


def _render_outputs() -> str:
    return "\n".join(
        f"      {area}: ${{{{ steps.areas.outputs.{area} }}}}"
        for area in CHANGE_AREAS
    )


def _render_steps(group: str, project: str) -> str:
    lines = []
    for area, rel in CHANGE_AREAS.items():
        path = f'$P/{rel}' if rel else '$P'
        lines.append(f'          echo "{area}=$(touched "{path}")" >> "$GITHUB_OUTPUT"')
    return "\n".join(lines)


def render_project_workflow(group: str, project: str, jobs: dict[str, str]) -> str:
    """The whole workflow file for one project.

    `jobs` maps a job id to its YAML block, already indented two spaces under
    `jobs:` and already rendered. Sorted by job id so the file does not churn
    when a capability is registered in a different order.
    """
    from pf.scaffold.generator import render

    ctx = {"group": group, "project": project}
    head = render(WORKFLOW_HEADER, ctx)
    head = head.replace("{{change_outputs}}", _render_outputs())
    head = head.replace("{{change_steps}}", _render_steps(group, project))

    body = "".join(
        "\n" + render(block, ctx).rstrip("\n") + "\n"
        for _, block in sorted(jobs.items())
    )
    return head + body


def workflow_path(project: str) -> str:
    """Repo-relative path of a project's master workflow."""
    return f".github/workflows/{project}.yml"


def legacy_paths(project: str) -> tuple[str, ...]:
    """Per-capability workflow files this master supersedes.

    Named explicitly rather than globbed: a glob over `*-<project>.yml` would
    also match a workflow somebody wrote by hand for this project, and deleting
    that during a routine bootstrap would be indefensible.
    """
    return (
        f".github/workflows/impact-gate-{project}.yml",
        f".github/workflows/recce-{project}.yml",
    )
