{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `sisters.landed_prices` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: PriceObservation · Grain: one commodity per market per price date
#}

with renamed as (
    select
        {{ pf_clean('landed_price_id', 'natural_key') }} as landed_price_id,
        {{ pf_clean('price_date', 'event_time') }} as price_date,
        {{ pf_clean('price_basis', 'status_enum') }} as price_basis,
        {{ pf_clean('quote_unit', 'unit_of_measure') }} as quote_unit,
        {{ pf_clean('market_unit', 'unit_of_measure') }} as market_unit,
        {{ pf_clean('currency_code', 'currency_code') }} as currency_code,
        {{ pf_clean('benchmark_price_usd', 'unit_price') }} as benchmark_price_usd,
        {{ pf_clean('benchmark_usd_per_market_unit', 'unit_price') }} as benchmark_usd_per_market_unit,
        {{ pf_clean('usd_fx_rate', 'exchange_rate') }} as usd_fx_rate,
        {{ pf_clean('fx_fixed_on', 'reference_date') }} as fx_fixed_on,
        {{ pf_clean('effective_duty_rate', 'rate_fraction') }} as effective_duty_rate,
        {{ pf_clean('is_import_prohibited', 'flag') }} as is_import_prohibited,
        {{ pf_clean('is_duty_rate_confirmed', 'flag') }} as is_duty_rate_confirmed,
        {{ pf_clean('assessable_value_local', 'unit_price') }} as assessable_value_local,
        {{ pf_clean('duty_local', 'unit_price') }} as duty_local,
        {{ pf_clean('landed_price_local', 'unit_price') }} as landed_price_local,
        {{ pf_clean('landed_price_change_local', 'unit_price') }} as landed_price_change_local,
        {{ pf_clean('landed_price_change_pct', 'rate_fraction') }} as landed_price_change_pct,
        {{ pf_clean('commodity_id', 'foreign_key') }} as commodity_id,  -- → Commodity
        {{ pf_clean('market_code', 'foreign_key') }} as market_code,  -- → Market
        _dlt_load_id
    from {{ source('sisters', 'landed_prices') }}
)

select * exclude (_dlt_load_id)
from renamed
where landed_price_id is not null
{{ pf_dedupe('landed_price_id') }}
