"""Project the semantic layer into an Open Knowledge Format (OKF v0.1) bundle.

OKF is Google's knowledge-catalog format: a directory of Markdown files with
YAML frontmatter, one concept per file, `index.md` at the root declaring the
version. OKF Weaver (`vendor/okf-weaver`) makes such bundles from a bare dbt
manifest by asking Claude what each column means and marking every answer with
a confidence for a person to review. This platform does not need to ask. What
a column means is already declared — the ontology role on it, the concept the
table instantiates, the grain and description on the model, the metric built
on it — and every declaration was reviewed when it was written. So the bundle
is a **projection**, like the MDL and the OpenMetadata export: read from the
knowledge the platform holds, never invented, and regenerated by every
`pf bootstrap`.

Three things are taken from the weaver, and the vendor registry says so:

  * its Pydantic models are the **validation gate** — every bundle here is
    constructed as an `OKFBundle` before a single file is written, so a bundle
    the weaver's own review UI would reject cannot be produced;
  * its directory layout and frontmatter keys are **ported**, so a bundle from
    here and a bundle from the weaver read the same to a consumer; the port
    drops the timestamp (a generated file that stamps its build time is stale
    on every commit) and adds `okf_x_concept`, `okf_x_role`, `okf_x_layer`,
    `okf_x_grain` and the link to the platform bundle;
  * its generator is what `pf tool okf weave` runs, for the columns the
    platform has *no* declaration for — as proposals in `okf/weave.md` for a
    person to promote into an annotation, never written into the bundle.

Two bundles, connected. `platform/okf/` is the platform ontology itself as
OKF — one concept file per class, one per role — and every project's
`okf/index.md` names it as `okf_x_platform_bundle`; a project concept file
links to the platform's when the class is the platform's, and says
`okf_x_defined_in: group` when the group's extension declared it. An agent
reading a project bundle can follow the concept up to the definition every
sister shares, which is the whole point of the three-tier ontology.

Confidence here is not a model's self-report. It is `1.0` where the platform
holds a declaration (a description on the model, a role on the column) and
`0.0` where it holds none — an honest "undocumented", surfaced for review in
exactly the way the weaver surfaces a low-confidence guess. PII columns the
MDL hides are withheld from the bundle and counted in its frontmatter: a
portable context file is the last place a masked column's name should travel.

Deterministic for a fixed project: everything sorted, no dates, no commits.
`pf tool okf check` fails when the committed bundle and the semantic layer
disagree.
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

VENDOR_SRC = Path("vendor") / "okf-weaver" / "backend" / "src"
OKF_REL = "okf"
PLATFORM_REL = Path("platform") / OKF_REL
PLATFORM_NAME = "Platform ontology"

#: The spec's reserved files. Everything else under `okf/` carries a `type`.
RESERVED = ("index.md", "log.md")

LOG = (
    "# Directory Update Log\n\n"
    "Regenerated in full by `pf tool okf build` and by every `pf bootstrap`; the\n"
    "history of this bundle is the history of the semantic layer it projects,\n"
    "which git keeps. Nothing here is hand-edited.\n"
)


class NotVendored(RuntimeError):
    """`vendor/okf-weaver` is not checked out, so nothing can validate a bundle."""


def vendored(root: str | Path) -> Any:
    """The weaver's models, imported from the submodule by path.

    By path rather than as a dependency for the reason the group-shared Python
    is: the upstream is pinned as a submodule and read at that pin, and adding
    it to the workspace would make its FastAPI, uvicorn and rate-limiter deps
    every project's. Only the models are needed to validate; the generator and
    the server import lazily in `pf.tools.okf`, where their extras are named.
    """
    src = Path(root) / VENDOR_SRC
    if not (src / "okf_weaver" / "models.py").is_file():
        # A bundle built for a tree that is not this repository — a test's
        # temporary project, say — is still validated against this repository's
        # pin: the models live with the platform package, not with the project.
        src = Path(__file__).resolve().parents[4] / VENDOR_SRC
    if not (src / "okf_weaver" / "models.py").is_file():
        raise NotVendored("vendor/okf-weaver is not checked out — `git submodule update --init vendor/okf-weaver`")
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    import okf_weaver.models as models

    return models


# ----------------------------------------------------------------- gather ---
@dataclass
class Facts:
    group: str
    project: str
    root: Path
    pdir: Path
    models: list[dict[str, Any]] = field(default_factory=list)
    relationships: list[dict[str, Any]] = field(default_factory=list)
    metrics: list[Any] = field(default_factory=list)
    onto: Any = None
    platform_classes: set[str] = field(default_factory=set)


def gather(root: str | Path, group: str, project: str) -> Facts:
    """Everything the project bundle states, from the project and its ontology."""
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    f = Facts(group, project, root, pdir)
    mdl_path = pdir / "mdl" / "mdl.json"
    if mdl_path.is_file():
        try:
            mdl = json.loads(mdl_path.read_text(encoding="utf-8"))
        except ValueError:
            mdl = {}
        f.models = sorted(
            (m for m in mdl.get("models") or [] if isinstance(m, dict) and m.get("name")),
            key=lambda m: str(m["name"]),
        )
        f.relationships = [r for r in mdl.get("relationships") or [] if isinstance(r, dict)]
    try:
        from pf.projections.evidence import collect_metrics

        f.metrics = sorted(collect_metrics(pdir), key=lambda m: m.name)
    except Exception:  # noqa: BLE001 — a project with no semantic layer has no metrics
        f.metrics = []
    try:
        from pf.ontology.model import load_ontology, load_project_ontology

        f.onto = load_project_ontology(root, group, project)
        f.platform_classes = set(load_ontology().classes)
    except Exception:  # noqa: BLE001 — a malformed ontology is `pf check`'s to report
        f.onto = None
    return f


_JOIN = re.compile(r"^\s*(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)\s*$")


def _foreign_keys(rels: list[dict[str, Any]]) -> dict[tuple[str, str], str]:
    """(model, column) -> "model.column" it references, from the MDL joins."""
    out: dict[tuple[str, str], str] = {}
    for r in rels:
        m = _JOIN.match(str(r.get("condition") or ""))
        if not m:
            continue
        a_model, a_col, b_model, b_col = m.groups()
        kind = str(r.get("joinType") or "")
        if kind in ("MANY_TO_ONE", "ONE_TO_ONE"):
            out[(a_model, a_col)] = f"{b_model}.{b_col}"
        elif kind == "ONE_TO_MANY":
            out[(b_model, b_col)] = f"{a_model}.{a_col}"
    return out


def _concepts(f: Facts) -> dict[str, str]:
    """model -> ontology class, from the relations the MDL names and the identities."""
    out: dict[str, str] = {}
    if f.onto is None:
        return out
    for r in f.relationships:
        rel = f.onto.relation(str((r.get("properties") or {}).get("pf.relation") or ""))
        models = r.get("models") or []
        if rel is None or len(models) != 2:
            continue
        out.setdefault(str(models[0]), rel.domain)
        out.setdefault(str(models[1]), rel.range)
    by_identity = {c.identity: name for name, c in sorted(f.onto.classes.items()) if getattr(c, "identity", "")}
    for m in f.models:
        pk = str(m.get("primaryKey") or "")
        if pk and m["name"] not in out and pk in by_identity:
            out[m["name"]] = by_identity[pk]
    return out


# ------------------------------------------------------------------ build ---
def _one_line(text: str) -> str:
    return " ".join(str(text or "").split())


def _front(data: dict[str, Any]) -> str:
    return "---\n" + yaml.safe_dump(data, sort_keys=False, allow_unicode=True).strip() + "\n---\n"


def _cell(text: str) -> str:
    return _one_line(text).replace("|", "\\|")


def _platform_link(pdir: Path, root: Path, rel: str) -> str:
    """A bundle-to-bundle link, relative, so it survives a clone anywhere."""
    return os.path.relpath(root / PLATFORM_REL / rel, pdir / OKF_REL / Path(rel).parent).replace("\\", "/")


def build_project(root: str | Path, group: str, project: str) -> dict[str, str]:
    """The project bundle as {path: text}, validated through the weaver's models."""
    root = Path(root)
    f = gather(root, group, project)
    models = vendored(root)
    fks = _foreign_keys(f.relationships)
    concept_of = _concepts(f)
    roles = f.onto.roles if f.onto is not None else {}
    classes = f.onto.classes if f.onto is not None else {}

    tables = []
    role_of: dict[str, dict[str, str]] = {}
    withheld: dict[str, int] = {}
    for m in f.models:
        name = str(m["name"])
        props = m.get("properties") or {}
        cols = []
        role_of[name] = {}
        for c in sorted(m.get("columns") or [], key=lambda c: str(c.get("name"))):
            if c.get("isHidden"):
                withheld[name] = withheld.get(name, 0) + 1
                continue
            role = str((c.get("properties") or {}).get("pf.role") or "")
            role_of[name][str(c["name"])] = role
            r = roles.get(role)
            definition = _one_line(getattr(r, "description", "")) if r is not None else ""
            cols.append(
                models.OKFColumn(
                    name=str(c["name"]),
                    definition=definition,
                    confidence=1.0 if definition else 0.0,
                    data_type=str(c.get("type") or "unknown"),
                    is_primary_key=str(c["name"]) == str(m.get("primaryKey") or ""),
                    nullable=not bool(c.get("notNull")),
                    references=fks.get((name, str(c["name"]))),
                )
            )
        desc = _one_line(props.get("description") or "")
        fallback = f"{props.get('layer') or 'model'} at grain: {props.get('grain') or 'undeclared'}"
        tables.append(
            models.OKFTable(
                name=name,
                description=desc or fallback,
                confidence=1.0 if desc else 0.0,
                is_source_of_truth=str(props.get("layer") or "") == "marts",
                columns=cols,
            )
        )

    files: dict[str, str] = {"log.md": LOG}
    # The gate: a bundle the weaver would reject cannot be written.
    bundle = models.OKFBundle(name=f"{group}/{project}", tables=tables) if tables else None
    concepts_used = sorted({c for c in concept_of.values() if c in classes})
    files["index.md"] = _index(f, bundle, concept_of, concepts_used)
    if bundle is not None:
        metrics_on = {}
        for ms in f.metrics:
            metrics_on.setdefault(ms.model, []).append(ms.name)
        by_name = {str(m["name"]): m for m in f.models}
        for t in bundle.tables:
            files[f"tables/{t.name}.md"] = _table_file(
                t,
                by_name[t.name],
                concept_of.get(t.name, ""),
                role_of[t.name],
                withheld.get(t.name, 0),
                metrics_on.get(t.name, []),
            )
    for cls in concepts_used:
        files[f"concepts/{cls}.md"] = _concept_file(
            f, classes[cls], cls in f.platform_classes, [t for t, c in sorted(concept_of.items()) if c == cls]
        )
    for ms in f.metrics:
        files[f"metrics/{ms.name}.md"] = _metric_file(ms)
    return files


def _index(f: Facts, bundle: Any, concept_of: dict[str, str], concepts: list[str]) -> str:
    front = {
        "okf_version": bundle.okf_version if bundle is not None else "0.1",
        "name": f"{f.group}/{f.project}",
        "okf_x_group": f.group,
        "okf_x_project": f.project,
        "okf_x_platform_bundle": _platform_link(f.pdir, f.root, "index.md"),
        "okf_x_tables": len(bundle.tables) if bundle is not None else 0,
        "okf_x_concepts": len(concepts),
        "okf_x_metrics": len(f.metrics),
    }
    lines = [
        f"# {f.group}/{f.project}",
        "",
        "Generated by `pf tool okf build` from this project's semantic layer — the MDL, the",
        "ontology annotations and the metric definitions — and validated as an OKF v0.1",
        "bundle before it was written. Nothing here was inferred. A definition with",
        "confidence `0.00` is one the platform does not hold yet; declare it in",
        "`contracts/annotations.yaml` or the model's `description`, and rebuild.",
        "",
        (
            f"The concepts below are the platform's, shared by every sister: [{PLATFORM_NAME}]"
            f"({front['okf_x_platform_bundle']})."
        ),
        "",
        "# Tables",
        "",
    ]
    if bundle is None:
        lines.append("_No models in the semantic layer yet — `pf seed`, then `pf semantic mdl`._")
    else:
        for t in bundle.tables:
            c = concept_of.get(t.name, "")
            tag = f" — `{c}`" if c else ""
            lines.append(f"* [{t.name}](/tables/{t.name}.md){tag} - {_one_line(t.description)}")
    lines += ["", "# Concepts", ""]
    lines += [f"* [{c}](/concepts/{c}.md)" for c in concepts] or ["_none reached by a table_"]
    lines += ["", "# Metrics", ""]
    lines += [f"* [{m.name}](/metrics/{m.name}.md) - {_one_line(m.description)}" for m in f.metrics] or [
        "_no metric yet — `/build-semantic-layer`_"
    ]
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def _table_file(
    t: Any, m: dict[str, Any], concept: str, role_of: dict[str, str], withheld: int, metrics: list[str]
) -> str:
    props = m.get("properties") or {}
    front: dict[str, Any] = {
        "type": "Table",  # REQUIRED by OKF; the one key the spec insists on
        "title": t.name,
        "description": _one_line(t.description),
        "okf_x_source_of_truth": t.is_source_of_truth,
        "okf_x_table_confidence": round(t.confidence, 2),
        "okf_x_concept": concept or None,
        "okf_x_layer": props.get("layer") or None,
        "okf_x_grain": _one_line(props.get("grain") or "") or None,
        "okf_x_columns_withheld": withheld,
    }
    rows = [
        "# Schema",
        "",
        "| Column | Type | Role | Description | Confidence |",
        "|---|---|---|---|---|",
    ]
    for c in t.columns:
        desc = _cell(c.definition)
        if c.references:
            ref_model = c.references.split(".", 1)[0]
            desc = (desc + " " if desc else "") + f"FK to [{ref_model}](/tables/{ref_model}.md)"
        if c.is_primary_key:
            desc = (desc + " " if desc else "") + "(primary key)"
        rows.append(
            f"| `{c.name}` | {c.data_type} | {role_of.get(c.name) or ''} | {desc or '—'} | {c.confidence:.2f} |"
        )
    body = list(rows)
    if concept:
        body += ["", "# Concept", "", f"Instantiates [{concept}](/concepts/{concept}.md)."]
    if metrics:
        body += ["", "# Metrics", ""] + [f"* [{n}](/metrics/{n}.md)" for n in metrics]
    if withheld:
        body += [
            "",
            f"_{withheld} column(s) withheld: masked by policy in the MDL, and not named in a portable file._",
        ]
    return _front(front) + "\n" + "\n".join(body) + "\n"


def _concept_file(f: Facts, cls: Any, platform_defined: bool, tables: list[str]) -> str:
    front: dict[str, Any] = {
        "type": "Concept",
        "title": cls.name,
        "description": _one_line(getattr(cls, "description", "")),
        "okf_x_defined_in": "platform" if platform_defined else "group",
        "okf_x_parent": getattr(cls, "parent", None) or None,
        "okf_x_identity": getattr(cls, "identity", None) or None,
    }
    if platform_defined:
        front["okf_x_platform_concept"] = _platform_link(f.pdir, f.root, f"concepts/{cls.name}.md")
    lines = []
    if platform_defined:
        lines += [f"Defined by the platform ontology: [{cls.name}]({front['okf_x_platform_concept']})."]
    else:
        lines += [f"Declared in `groups/{f.group}/ontology/extension.yaml`, shared by every sister of `{f.group}`."]
    lines += ["", "# Instantiated by", ""] + [f"* [{t}](/tables/{t}.md)" for t in tables]
    props = getattr(cls, "properties", {}) or {}
    if props:
        lines += ["", "# Properties", "", "| Property | Datatype | Role |", "|---|---|---|"]
        lines += [
            f"| `{n}` | {getattr(p, 'datatype', '')} | {getattr(p, 'role', '') or ''} |"
            for n, p in sorted(props.items())
        ]
    if f.onto is not None:
        rels = sorted(f.onto.relations_for(cls.name), key=lambda r: r.name) if hasattr(f.onto, "relations_for") else []
        if rels:
            lines += ["", "# Relations", ""] + [f"* {r.describe()} — {_one_line(r.description)}" for r in rels]
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def _metric_file(ms: Any) -> str:
    front: dict[str, Any] = {
        "type": "Metric",
        "title": ms.label or ms.name,
        "description": _one_line(ms.description),
        "okf_x_kind": ms.kind,
        "okf_x_model": ms.model or None,
        "okf_x_time_column": ms.time_column or None,
    }
    lines = [
        "# Definition",
        "",
        f"* **Kind:** `{ms.kind}`",
        f"* **Expression:** `{ms.expression}`" if ms.expression else "* **Expression:** derived",
    ]
    if ms.numerator or ms.denominator:
        lines.append(
            f"* **Ratio:** `{ms.numerator}` / `{ms.denominator}` — re-divide at the reading grain, "
            "never average the ratio"
        )
    if ms.model:
        lines.append(f"* **Built on:** [{ms.model}](/tables/{ms.model}.md)")
    if ms.dimensions:
        lines.append("* **Dimensions:** " + ", ".join(f"`{d}`" for d in ms.dimensions))
    if ms.filter_sql:
        lines.append(f"* **Filter:** `{ms.filter_sql}`")
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def build_platform(root: str | Path) -> dict[str, str]:
    """The platform ontology itself as an OKF bundle: one concept per class, one per role."""
    root = Path(root)
    from pf.ontology.model import load_ontology

    onto = load_ontology()
    files: dict[str, str] = {"log.md": LOG}
    classes = sorted(onto.classes.values(), key=lambda c: c.name)
    roles = sorted(onto.roles.values(), key=lambda r: r.name)
    front = {
        "okf_version": "0.1",
        "name": PLATFORM_NAME,
        "okf_x_scope": "platform",
        "okf_x_concepts": len(classes),
        "okf_x_roles": len(roles),
    }
    lines = [
        f"# {PLATFORM_NAME}",
        "",
        "Generated by `pf tool okf build --platform` from `platform/src/pf/ontology/`. Every",
        "group's and project's bundle links its concepts here; what a role means is",
        "declared once, for every sister.",
        "",
        "# Concepts",
        "",
    ]
    lines += [f"* [{c.name}](/concepts/{c.name}.md) - {_one_line(getattr(c, 'description', ''))}" for c in classes]
    lines += ["", "# Roles", ""]
    lines += [f"* [{r.name}](/roles/{r.name}.md) - {_one_line(getattr(r, 'description', ''))}" for r in roles]
    files["index.md"] = _front(front) + "\n" + "\n".join(lines) + "\n"
    for c in classes:
        f_ = {
            "type": "Concept",
            "title": c.name,
            "description": _one_line(getattr(c, "description", "")),
            "okf_x_parent": getattr(c, "parent", None) or None,
            "okf_x_abstract": bool(getattr(c, "abstract", False)),
            "okf_x_identity": getattr(c, "identity", None) or None,
        }
        body = []
        props = getattr(c, "properties", {}) or {}
        if props:
            body += ["# Properties", "", "| Property | Datatype | Role |", "|---|---|---|"]
            body += [
                f"| `{n}` | {getattr(p, 'datatype', '')} | "
                + (f"[{p.role}](/roles/{p.role}.md)" if getattr(p, "role", "") else "")
                + " |"
                for n, p in sorted(props.items())
            ]
        rels = sorted(onto.relations_for(c.name), key=lambda r: r.name)
        if rels:
            body += ["", "# Relations", ""] + [f"* {r.describe()} — {_one_line(r.description)}" for r in rels]
        files[f"concepts/{c.name}.md"] = _front(f_) + "\n" + "\n".join(body or ["_no properties declared_"]) + "\n"
    for r in roles:
        f_ = {
            "type": "Role",
            "title": r.name,
            "description": _one_line(getattr(r, "description", "")),
            "okf_x_datatype": getattr(r, "datatype", None) or None,
            "okf_x_pii": bool(getattr(r, "pii", False)),
            "okf_x_review": getattr(r, "review", None) or None,
        }
        policies = onto.policies_for_role(r.name) if hasattr(onto, "policies_for_role") else []
        body = ["# Policies", ""] + (
            [f"* `{p.id}` — {_one_line(getattr(p, 'description', ''))}" for p in sorted(policies, key=lambda p: p.id)]
            or ["_none bound to this role_"]
        )
        files[f"roles/{r.name}.md"] = _front(f_) + "\n" + "\n".join(body) + "\n"
    return files


# ------------------------------------------------------------------ write ---
def _sync(out: Path, files: dict[str, str]) -> tuple[list[Path], list[Path]]:
    """Write what differs; remove concept files the bundle no longer has."""
    written, removed = [], []
    for rel, text in files.items():
        p = out / rel
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
            written.append(p)
    for sub in ("tables", "concepts", "metrics", "roles"):
        d = out / sub
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            if f"{sub}/{p.name}" not in files:
                p.unlink()
                removed.append(p)
    return written, removed


def write_project(root: str | Path, group: str, project: str) -> dict[str, Any]:
    root = Path(root)
    out = root / "groups" / group / "projects" / project / OKF_REL
    files = build_project(root, group, project)
    written, removed = _sync(out, files)
    return {
        "path": out,
        "tables": sum(1 for k in files if k.startswith("tables/")),
        "concepts": sum(1 for k in files if k.startswith("concepts/")),
        "metrics": sum(1 for k in files if k.startswith("metrics/")),
        "written": len(written),
        "removed": len(removed),
    }


def write_platform(root: str | Path) -> dict[str, Any]:
    root = Path(root)
    out = root / PLATFORM_REL
    files = build_platform(root)
    written, removed = _sync(out, files)
    return {
        "path": out,
        "concepts": sum(1 for k in files if k.startswith("concepts/")),
        "roles": sum(1 for k in files if k.startswith("roles/")),
        "written": len(written),
        "removed": len(removed),
    }


# ------------------------------------------------------------------ check ---
_FRONT = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def conformance(bundle_dir: str | Path) -> list[str]:
    """OKF v0.1 §8: every non-reserved file has parseable frontmatter with a non-empty `type`."""
    d = Path(bundle_dir)
    problems = []
    if not (d / "index.md").is_file():
        return [f"{d}: no index.md"]
    for p in sorted(d.rglob("*.md")):
        rel = p.relative_to(d).as_posix()
        if rel in RESERVED:
            continue
        m = _FRONT.match(p.read_text(encoding="utf-8"))
        if not m:
            problems.append(f"{rel}: no YAML frontmatter")
            continue
        try:
            meta = yaml.safe_load(m.group(1)) or {}
        except yaml.YAMLError as exc:
            problems.append(f"{rel}: frontmatter is not YAML ({exc})")
            continue
        if not str(meta.get("type") or "").strip():
            problems.append(f"{rel}: frontmatter has no `type`")
    return problems


def _drift(out: Path, files: dict[str, str]) -> list[str]:
    problems = []
    for rel, text in files.items():
        p = out / rel
        if not p.is_file():
            problems.append(f"{rel}: missing")
        elif p.read_text(encoding="utf-8") != text:
            problems.append(f"{rel}: stale")
    for sub in ("tables", "concepts", "metrics", "roles"):
        d = out / sub
        for p in sorted(d.glob("*.md")) if d.is_dir() else []:
            if f"{sub}/{p.name}" not in files:
                problems.append(f"{sub}/{p.name}: no longer in the semantic layer")
    return problems


def check_project(root: str | Path, group: str, project: str) -> list[str]:
    """Empty when the committed bundle is what the semantic layer projects, and conformant."""
    root = Path(root)
    out = root / "groups" / group / "projects" / project / OKF_REL
    if not out.is_dir():
        return [f"{group}/{project}: no okf/ — run `pf tool okf build {group} {project}`"]
    problems = [f"{group}/{project}: {x}" for x in _drift(out, build_project(root, group, project))]
    problems += [f"{group}/{project}: {x}" for x in conformance(out)]
    return problems


def check_platform(root: str | Path) -> list[str]:
    root = Path(root)
    out = root / PLATFORM_REL
    if not out.is_dir():
        return ["platform: no platform/okf/ — run `pf tool okf build --platform`"]
    return [f"platform: {x}" for x in _drift(out, build_platform(root))] + [f"platform: {x}" for x in conformance(out)]
