"""Project the semantic layer into an Open Knowledge Format (OKF v0.1) bundle.

OKF is Google's knowledge-catalog format: a directory of Markdown files with
YAML frontmatter, one concept per file, `index.md` at the root declaring the
version. OKF Weaver (`vendor/okf-weaver`) makes such bundles from a bare dbt
manifest by asking Claude what each column means and marking every answer with
a confidence for a person to review. This platform does not need to ask. What
a column means is already declared — the ontology role on it, the concept the
table instantiates, the grain and description on the model, the metric built
on it — and every declaration was reviewed when it was written. So the bundle
is a **projection**, like the MDL and the OpenMetadata export: read from the
knowledge the platform holds, never invented, and regenerated by every
`pf bootstrap`.

Three things are taken from the weaver, and the vendor registry says so:

  * its Pydantic models are the **validation gate** — every bundle here is
    constructed as an `OKFBundle` before a single file is written, so a bundle
    the weaver's own review UI would reject cannot be produced;
  * its directory layout and frontmatter keys are **ported**, so a bundle from
    here and a bundle from the weaver read the same to a consumer; the port
    drops the timestamp (a generated file that stamps its build time is stale
    on every commit) and adds `okf_x_concept`, `okf_x_role`, `okf_x_layer`,
    `okf_x_grain` and the link to the platform bundle;
  * its generator is what `pf tool okf weave` runs, for the columns the
    platform has *no* declaration for — as proposals in `okf/weave.md` for a
    person to promote into an annotation, never written into the bundle.

Three bundles, connected, because the ontology has three tiers. `platform/okf/`
is the platform ontology as OKF — a page per class, per role and per relation.
`groups/<group>/okf/` is what that family added on top: the classes, roles and
relations its `extension.yaml` declares, and nothing it merely inherited, which
is one link away. A project's `okf/` is the physical layer — its tables, the
concepts they instantiate, its metrics.

Each tier names the one above it, so a reader who starts at a table can follow
the concept to the family that declared it and up to the vocabulary every sister
shares. A term a steward approved into a group extension used to have no OKF
page at all until some project's mart happened to instantiate it: approved,
propagated to the graph and the MDL, and invisible in the format the platform
publishes its knowledge in.

Joined to the knowledge graph, not exported beside it. Every page names the
node it documents (`okf_x_kg_node`), and states what only the graph holds: the
lineage that reaches the table, the metrics and dashboards downstream of it,
the policies that govern its concept, and the decisions recorded about it. The
graph is read from the tracked `kg/graph.json`, never from `kg/graph.duckdb` —
the database is gitignored, so a bundle projected from it could not be checked
in a clone that never built a warehouse, which is every CI runner. `reconcile`
is that join as a gate: a page naming a node the graph does not hold means one
of the two was rebuilt without the other.

Confidence here is not a model's self-report. It is `1.0` where the platform
holds a declaration (a description on the model, a role on the column) and
`0.0` where it holds none — an honest "undocumented", surfaced for review in
exactly the way the weaver surfaces a low-confidence guess. PII columns the
MDL hides are withheld from the bundle and counted in its frontmatter: a
portable context file is the last place a masked column's name should travel.

Deterministic for a fixed project: everything sorted, no dates, no commits.
`pf tool okf check` fails when the committed bundle and the semantic layer
disagree.
"""

from __future__ import annotations

import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

VENDOR_SRC = Path("vendor") / "okf-weaver" / "backend" / "src"
OKF_REL = "okf"
PLATFORM_REL = Path("platform") / OKF_REL
PLATFORM_NAME = "Platform ontology"
#: The tracked graph export, beside the bundle in the same project.
KG_REL = Path("kg") / "graph.json"
KG_LINK = "../kg/graph.json"

#: The spec's reserved files. Everything else under `okf/` carries a `type`.
RESERVED = ("index.md", "log.md")

LOG = (
    "# Directory Update Log\n\n"
    "Regenerated in full by `pf tool okf build` and by every `pf bootstrap`; the\n"
    "history of this bundle is the history of the semantic layer it projects,\n"
    "which git keeps. Nothing here is hand-edited.\n"
)


class NotVendored(RuntimeError):
    """`vendor/okf-weaver` is not checked out, so nothing can validate a bundle."""


def vendored(root: str | Path) -> Any:
    """The weaver's models, imported from the submodule by path.

    By path rather than as a dependency for the reason the group-shared Python
    is: the upstream is pinned as a submodule and read at that pin, and adding
    it to the workspace would make its FastAPI, uvicorn and rate-limiter deps
    every project's. Only the models are needed to validate; the generator and
    the server import lazily in `pf.tools.okf`, where their extras are named.
    """
    src = Path(root) / VENDOR_SRC
    if not (src / "okf_weaver" / "models.py").is_file():
        # A bundle built for a tree that is not this repository — a test's
        # temporary project, say — is still validated against this repository's
        # pin: the models live with the platform package, not with the project.
        src = Path(__file__).resolve().parents[4] / VENDOR_SRC
    if not (src / "okf_weaver" / "models.py").is_file():
        raise NotVendored("vendor/okf-weaver is not checked out — `git submodule update --init vendor/okf-weaver`")
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    import okf_weaver.models as models

    return models


# ------------------------------------------------------------- the graph ---
@dataclass
class GraphFacts:
    """The project's committed knowledge graph, indexed for the four questions a
    bundle page asks of it: what feeds this, what depends on it, what governs
    its concept, and what was decided about it.

    Indexed rather than queried through `pf.kg.store` because the source here is
    the JSON export, not the DuckDB file: the export is the tracked artefact, so
    a bundle built from it is reproducible in a bare clone, and reading it costs
    no database attachment while a sister holds the write lock.
    """

    nodes: dict[str, dict[str, Any]] = field(default_factory=dict)
    out: dict[str, list[tuple[str, str]]] = field(default_factory=dict)
    into: dict[str, list[tuple[str, str]]] = field(default_factory=dict)

    def has(self, node_id: str) -> bool:
        return node_id in self.nodes

    def count(self, kind: str) -> int:
        return sum(1 for n in self.nodes.values() if n.get("kind") == kind)

    def named(self, kind: str) -> list[str]:
        return sorted(str(n.get("name") or "") for n in self.nodes.values() if n.get("kind") == kind)

    def _walk(self, index: dict[str, list[tuple[str, str]]], node_id: str,
              edge: str, kind: str) -> list[dict[str, Any]]:
        found = [self.nodes[other] for k, other in index.get(node_id, ()) if k == edge and other in self.nodes]
        return sorted((n for n in found if n.get("kind") == kind), key=lambda n: str(n.get("name") or ""))

    def upstream(self, node_id: str, kind: str, edge: str = "feeds") -> list[dict[str, Any]]:
        return self._walk(self.into, node_id, edge, kind)

    def downstream(self, node_id: str, kind: str, edge: str = "feeds") -> list[dict[str, Any]]:
        return self._walk(self.out, node_id, edge, kind)

    def columns_of(self, node_id: str) -> list[str]:
        return [dst for kind, dst in self.out.get(node_id, ()) if kind == "has_column"]

    def governing(self, concept: str) -> list[dict[str, Any]]:
        """The policies that constrain a concept — a table's obligations, stated
        where the table is documented rather than three files away."""
        return self._walk(self.into, f"concept:{concept}", "governs", "Policy") if concept else []

    def decided(self, node_ids: list[str]) -> list[dict[str, Any]]:
        """The ADRs that decided about any of these nodes. A decision is upstream
        of what it governs, so it is only ever reached by asking backwards."""
        found: dict[str, dict[str, Any]] = {}
        for nid in node_ids:
            for kind, src in self.into.get(nid, ()):
                if kind == "decides" and src in self.nodes:
                    found[src] = self.nodes[src]
        return sorted(found.values(), key=lambda n: str(n.get("name") or ""))


def load_graph(pdir: str | Path) -> GraphFacts | None:
    """The project's tracked graph, or None where one was never built.

    None rather than an empty graph: a project with no graph and a project whose
    graph holds nothing about a table are different facts, and only the second
    one means the bundle should stay silent about lineage.
    """
    path = Path(pdir) / KG_REL
    if not path.is_file():
        return None
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except ValueError:
        return None  # a corrupt export is `pf kg build`'s to report, not a bundle's
    gf = GraphFacts(nodes={str(n["id"]): n for n in payload.get("nodes") or [] if isinstance(n, dict) and n.get("id")})
    for e in payload.get("edges") or []:
        if not isinstance(e, dict):
            continue
        src, dst, kind = str(e.get("src") or ""), str(e.get("dst") or ""), str(e.get("kind") or "")
        if not (src and dst and kind):
            continue
        gf.out.setdefault(src, []).append((kind, dst))
        gf.into.setdefault(dst, []).append((kind, src))
    return gf


# ----------------------------------------------------------------- gather ---
@dataclass
class Facts:
    group: str
    project: str
    root: Path
    pdir: Path
    models: list[dict[str, Any]] = field(default_factory=list)
    relationships: list[dict[str, Any]] = field(default_factory=list)
    metrics: list[Any] = field(default_factory=list)
    onto: Any = None
    platform_classes: set[str] = field(default_factory=set)
    graph: GraphFacts | None = None


def gather(root: str | Path, group: str, project: str) -> Facts:
    """Everything the project bundle states, from the project and its ontology."""
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    f = Facts(group, project, root, pdir)
    mdl_path = pdir / "mdl" / "mdl.json"
    if mdl_path.is_file():
        try:
            mdl = json.loads(mdl_path.read_text(encoding="utf-8"))
        except ValueError:
            mdl = {}
        f.models = sorted(
            (m for m in mdl.get("models") or [] if isinstance(m, dict) and m.get("name")),
            key=lambda m: str(m["name"]),
        )
        f.relationships = [r for r in mdl.get("relationships") or [] if isinstance(r, dict)]
    try:
        from pf.ontology.model import load_ontology, load_project_ontology

        f.onto = load_project_ontology(root, group, project)
        f.platform_classes = set(load_ontology().classes)
    except Exception:  # noqa: BLE001 — a malformed ontology is `pf check`'s to report
        f.onto = None
    f.graph = load_graph(pdir)
    f.metrics = metric_specs(f.graph)
    return f


def _inherited_time(gf: GraphFacts, name: str, seen: set[str] | None = None) -> str:
    """A ratio's time column is its components' — it aggregates over the same time."""
    seen = seen or set()
    if name in seen:
        return ""
    seen.add(name)
    for component in gf.upstream(f"metric:{name}", "Metric"):
        cname = str(component.get("name") or "")
        declared = str((component.get("props") or {}).get("time_column") or "")
        if declared:
            return declared
        found = _inherited_time(gf, cname, seen)
        if found:
            return found
    return ""


def metric_specs(gf: GraphFacts | None) -> list[Any]:
    """Every metric the graph holds, as specs a page can be rendered from.

    From the graph rather than from `pf.projections.evidence.collect_metrics`,
    whose only input is `transform/target/semantic_manifest.json`. That file is
    gitignored, so a bundle built through the collector documented whatever the
    last `dbt parse` on that machine happened to leave behind: green on a laptop
    that has built everything, and on a runner that has built nothing it read as
    "these fifteen metric pages are no longer in the semantic layer". The graph
    carries the same facts and git carries the graph.

    Every Metric node gets a spec. The collector drops a metric whose measure it
    cannot turn into SQL, which is the right rule for a dashboard that has to
    run the query and the wrong one for a bundle that has to describe it — a
    metric the platform defines and cannot render is exactly the one worth
    documenting.
    """
    if gf is None:
        return []
    from pf.projections.evidence import MetricSpec, agg_sql, translate_filter

    def owner(name: str, seen: set[str] | None = None) -> str:
        """The model a metric measures, directly or through its components.

        A ratio or a derived metric hangs off other metrics and has no `measures`
        edge of its own, so asking the graph directly says "no model" about a
        metric that is plainly built on one. Walk up until a component names it.
        """
        seen = seen or set()
        if name in seen:
            return ""
        seen.add(name)
        direct = gf.upstream(f"metric:{name}", "Model", edge="measures")
        if direct:
            return str(direct[0].get("name") or "")
        for component in gf.upstream(f"metric:{name}", "Metric"):
            found = owner(str(component.get("name") or ""), seen)
            if found:
                return found
        return ""

    out = []
    for node in sorted(gf.nodes.values(), key=lambda n: str(n.get("name") or "")):
        if node.get("kind") != "Metric":
            continue
        props = node.get("props") or {}
        name = str(node.get("name") or "")
        model = owner(name)
        dims = [
            str(d.get("name") or "")
            for d in gf.downstream(f"model:{model}", "Dimension", edge="grouped_by")
            if (d.get("props") or {}).get("type") != "time"
        ] if model else []
        expression = ""
        if props.get("agg"):
            expression = agg_sql(str(props["agg"]), str(props.get("expr") or name),
                                 props.get("agg_params") or {}) or ""
        out.append(
            MetricSpec(
                name=name,
                label=str(node.get("label") or name),
                kind=str(props.get("type") or "simple"),
                model=model,
                expression=expression,
                filter_sql=translate_filter(str(props.get("filter") or "")),
                time_column=str(props.get("time_column") or _inherited_time(gf, name)),
                dimensions=sorted(dict.fromkeys(dims)),
                numerator=str(props.get("numerator") or ""),
                denominator=str(props.get("denominator") or ""),
                description=str(props.get("description") or ""),
            )
        )
    return out


_JOIN = re.compile(r"^\s*(\w+)\.(\w+)\s*=\s*(\w+)\.(\w+)\s*$")


def _foreign_keys(rels: list[dict[str, Any]]) -> dict[tuple[str, str], str]:
    """(model, column) -> "model.column" it references, from the MDL joins."""
    out: dict[tuple[str, str], str] = {}
    for r in rels:
        m = _JOIN.match(str(r.get("condition") or ""))
        if not m:
            continue
        a_model, a_col, b_model, b_col = m.groups()
        kind = str(r.get("joinType") or "")
        if kind in ("MANY_TO_ONE", "ONE_TO_ONE"):
            out[(a_model, a_col)] = f"{b_model}.{b_col}"
        elif kind == "ONE_TO_MANY":
            out[(b_model, b_col)] = f"{a_model}.{a_col}"
    return out


def _concepts(f: Facts) -> dict[str, str]:
    """model -> ontology class, from the relations the MDL names and the identities."""
    out: dict[str, str] = {}
    if f.onto is None:
        return out
    for r in f.relationships:
        rel = f.onto.relation(str((r.get("properties") or {}).get("pf.relation") or ""))
        models = r.get("models") or []
        if rel is None or len(models) != 2:
            continue
        out.setdefault(str(models[0]), rel.domain)
        out.setdefault(str(models[1]), rel.range)
    by_identity = {c.identity: name for name, c in sorted(f.onto.classes.items()) if getattr(c, "identity", "")}
    for m in f.models:
        pk = str(m.get("primaryKey") or "")
        if pk and m["name"] not in out and pk in by_identity:
            out[m["name"]] = by_identity[pk]
    return out


# ------------------------------------------------------------------ build ---
def _one_line(text: str) -> str:
    return " ".join(str(text or "").split())


def _front(data: dict[str, Any]) -> str:
    return "---\n" + yaml.safe_dump(data, sort_keys=False, allow_unicode=True).strip() + "\n---\n"


def _cell(text: str) -> str:
    return _one_line(text).replace("|", "\\|")


def _link(from_bundle: Path, to_bundle: Path, rel: str) -> str:
    """A bundle-to-bundle link, relative, so it survives a clone anywhere."""
    return os.path.relpath(to_bundle / rel, from_bundle / Path(rel).parent).replace("\\", "/")


def _platform_link(pdir: Path, root: Path, rel: str) -> str:
    return _link(pdir / OKF_REL, root / PLATFORM_REL, rel)


def group_bundle(root: str | Path, group: str) -> Path:
    return Path(root) / "groups" / group / OKF_REL


def group_terms(root: str | Path, group: str) -> dict[str, set[str]]:
    """What this family *declared*, as opposed to what it inherited.

    Read from `extension.yaml` rather than diffed against the platform ontology,
    because a group may extend a platform class — adding properties to `Customer`
    without inventing a word — and that extension is the group's even though the
    class is not.
    """
    path = Path(root) / "groups" / group / "ontology" / "extension.yaml"
    empty = {"classes": set(), "roles": set(), "relations": set()}
    if not path.is_file():
        return empty
    try:
        ext = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError:
        return empty  # a malformed extension is `pf check`'s to report
    return {
        "classes": {str(k) for k in (ext.get("classes") or {})},
        "roles": {str(k) for k in (ext.get("roles") or {})},
        "relations": {
            str(r.get("name"))
            for r in (ext.get("relations") or [])
            if isinstance(r, dict) and r.get("name")
        },
    }


def _ref(name: str, have: set[str], folder: str) -> str:
    """A link when the bundle documents it, the bare name when it does not.

    The graph reaches every staging and intermediate model; the bundle documents
    the layer the semantic layer projects to BI. A link to a page that was never
    written is worse than no link — it reads as a missing file rather than as a
    model that is deliberately below the documented layer.
    """
    return f"[{name}](/{folder}/{name}.md)" if name in have else f"`{name}`"


#: How many downstream readers a page names before it summarises the rest. A
#: project with one Evidence page per metric has dozens, and a context file that
#: lists them all buys nothing a count does not.
MAX_READERS = 6


def _lineage(gf: GraphFacts, node_id: str, have_table: set[str]) -> list[str]:
    rows = []
    up = gf.upstream(node_id, "Model") + gf.upstream(node_id, "Table")
    if up:
        rows.append(
            "* **Upstream:** "
            + ", ".join(
                _ref(str(n.get("name") or ""), have_table, "tables")
                if n.get("kind") == "Model"
                else f"`{str(n.get('id') or '').split(':', 1)[-1]}`"
                for n in up
            )
        )
    down = gf.downstream(node_id, "Model")
    if down:
        rows.append(
            "* **Downstream:** " + ", ".join(_ref(str(n.get("name") or ""), have_table, "tables") for n in down)
        )
    exps = gf.downstream(node_id, "Exposure")
    if exps:
        # The owning team, never the owner's address: this file is meant to
        # travel, and an email in a portable context file is the same mistake
        # as a masked column's name in one.
        def read_by(n: dict[str, Any]) -> str:
            owner = (n.get("props") or {}).get("owner") or ""
            return f"`{n.get('name')}`" + (f" ({owner})" if owner else "")

        shown = ", ".join(read_by(n) for n in exps[:MAX_READERS])
        rest = f", and {len(exps) - MAX_READERS} more" if len(exps) > MAX_READERS else ""
        rows.append(f"* **Read by:** {shown}{rest}")
    return ["", "# Lineage", "", *rows] if rows else []


def _governance(gf: GraphFacts, node_ids: list[str], concept: str) -> list[str]:
    """What constrains this, and what was decided about it. Both are in the graph
    and in neither the MDL nor the ontology alone — the policy chain is resolved
    per project, and an ADR is a file the graph binds to the nodes it names."""
    rows = []
    for pol in gf.governing(concept):
        severity = str((pol.get("props") or {}).get("severity") or "")
        label = _one_line(pol.get("label") or "")
        rows.append(
            f"* **Policy** `{pol.get('name')}`"
            + (f" ({severity})" if severity else "")
            + (f" — {label}" if label else "")
        )
    for dec in gf.decided(node_ids):
        status = str((dec.get("props") or {}).get("status") or "")
        label = _one_line(dec.get("label") or "")
        rows.append(
            f"* **Decision** {dec.get('name')}"
            + (f" — {label}" if label else "")
            + (f" ({status})" if status else "")
        )
    return ["", "# Governance", "", *rows] if rows else []


def _kg_node(gf: GraphFacts | None, node_id: str) -> str | None:
    """The graph node this page documents, stated only when it resolves.

    A key that is written whether or not the node exists is a pointer nobody can
    trust; written only when it resolves, `reconcile` can treat a dangling one as
    what it is — a bundle and a graph rebuilt independently of each other.
    """
    return node_id if gf is not None and gf.has(node_id) else None


def build_project(root: str | Path, group: str, project: str) -> dict[str, str]:
    """The project bundle as {path: text}, validated through the weaver's models."""
    root = Path(root)
    f = gather(root, group, project)
    models = vendored(root)
    fks = _foreign_keys(f.relationships)
    concept_of = _concepts(f)
    roles = f.onto.roles if f.onto is not None else {}
    classes = f.onto.classes if f.onto is not None else {}

    tables = []
    role_of: dict[str, dict[str, str]] = {}
    withheld: dict[str, int] = {}
    unnamed: dict[str, int] = {}
    for m in f.models:
        name = str(m["name"])
        props = m.get("properties") or {}
        cols = []
        role_of[name] = {}
        for c in sorted(m.get("columns") or [], key=lambda c: str(c.get("name"))):
            if c.get("isHidden"):
                withheld[name] = withheld.get(name, 0) + 1
                continue
            role = str((c.get("properties") or {}).get("pf.role") or "")
            r = roles.get(role)
            definition = _one_line(getattr(r, "description", "")) if r is not None else ""
            try:
                column = models.OKFColumn(
                    name=str(c["name"]),
                    definition=definition,
                    confidence=1.0 if definition else 0.0,
                    data_type=str(c.get("type") or "unknown"),
                    is_primary_key=str(c["name"]) == str(m.get("primaryKey") or ""),
                    nullable=not bool(c.get("notNull")),
                    references=fks.get((name, str(c["name"]))),
                )
            except ValueError:
                # A column the spec will not name. Warehouses name an unaliased
                # expression after the expression itself — `CASE WHEN (...) END`,
                # newlines and all — and a bundle is Markdown headings and file
                # references, so the weaver's models reject it. Counted and left
                # out rather than crashing the build of every other project:
                # the defect is an unaliased select in the source model, and the
                # count on the page is what says so.
                unnamed[name] = unnamed.get(name, 0) + 1
                continue
            role_of[name][str(c["name"])] = role
            cols.append(column)
        desc = _one_line(props.get("description") or "")
        fallback = f"{props.get('layer') or 'model'} at grain: {props.get('grain') or 'undeclared'}"
        tables.append(
            models.OKFTable(
                name=name,
                description=desc or fallback,
                confidence=1.0 if desc else 0.0,
                is_source_of_truth=str(props.get("layer") or "") == "marts",
                columns=cols,
            )
        )

    files: dict[str, str] = {"log.md": LOG}
    # OKF v0.1 holds at most `MAX_TABLES` tables, and the vendored models enforce
    # it. A project whose semantic layer exposes more than that — an adopted
    # repository with a thousand marts — has a bundle that cannot exist, and
    # building one raised a pydantic error out of `pf tool okf build --all`.
    # Refusing the table pages and saying why is the honest projection: the
    # concepts and the metrics still travel, and `mdl/mdl.json` and the graph
    # still hold every table. The cap is read from the vendored spec rather than
    # repeated here, so a bump of the pin moves it.
    over_cap = len(tables) if len(tables) > models.MAX_TABLES else 0
    # The gate: a bundle the weaver would reject cannot be written.
    bundle = models.OKFBundle(name=f"{group}/{project}", tables=tables) if tables and not over_cap else None
    concepts_used = sorted({c for c in concept_of.values() if c in classes})
    # What this bundle will document, so a lineage line links a page it holds and
    # names plainly what it does not.
    have_table = {t.name for t in bundle.tables} if bundle is not None else set()
    have_metric = {str(ms.name) for ms in f.metrics}
    files["index.md"] = _index(f, bundle, concept_of, concepts_used, over_cap, models.MAX_TABLES)
    if bundle is not None:
        metrics_on: dict[str, list[str]] = {}
        for ms in f.metrics:
            if ms.model:  # a derived metric sits on another metric, not on a model
                metrics_on.setdefault(ms.model, []).append(ms.name)
        by_name = {str(m["name"]): m for m in f.models}
        for t in bundle.tables:
            files[f"tables/{t.name}.md"] = _table_file(
                t,
                by_name[t.name],
                concept_of.get(t.name, ""),
                role_of[t.name],
                withheld.get(t.name, 0),
                unnamed.get(t.name, 0),
                metrics_on.get(t.name, []),
                f.graph,
                have_table,
            )
    for cls in concepts_used:
        files[f"concepts/{cls}.md"] = _concept_file(
            f, classes[cls], cls in f.platform_classes, [t for t, c in sorted(concept_of.items()) if c == cls]
        )
    for ms in f.metrics:
        files[f"metrics/{ms.name}.md"] = _metric_file(ms, f.graph, have_metric)
    return files


def _index(f: Facts, bundle: Any, concept_of: dict[str, str], concepts: list[str],
           over_cap: int = 0, cap: int = 0) -> str:
    front = {
        "okf_version": bundle.okf_version if bundle is not None else "0.1",
        "name": f"{f.group}/{f.project}",
        "okf_x_group": f.group,
        "okf_x_project": f.project,
        "okf_x_platform_bundle": _platform_link(f.pdir, f.root, "index.md"),
        "okf_x_kg_graph": KG_LINK if f.graph is not None else None,
        "okf_x_kg_models": f.graph.count("Model") if f.graph is not None else None,
        "okf_x_tables": len(bundle.tables) if bundle is not None else 0,
        "okf_x_concepts": len(concepts),
        "okf_x_metrics": len(f.metrics),
    }
    if over_cap:
        front["okf_x_tables_over_cap"] = over_cap
    lines = [
        f"# {f.group}/{f.project}",
        "",
        "Generated by `pf tool okf build` from this project's semantic layer — the MDL, the",
        "ontology annotations and the metric definitions — and validated as an OKF v0.1",
        "bundle before it was written. Nothing here was inferred. A definition with",
        "confidence `0.00` is one the platform does not hold yet; declare it in",
        "`contracts/annotations.yaml` or the model's `description`, and rebuild.",
        "",
        (
            f"The concepts below are the platform's, shared by every sister: [{PLATFORM_NAME}]"
            f"({front['okf_x_platform_bundle']})."
        ),
        "",
    ]
    if f.graph is not None:
        documented = (
            f"{over_cap} reach the BI layer, more than a bundle may hold — see below"
            if over_cap
            else f"the {front['okf_x_tables']} below are the ones the semantic layer projects to BI"
        )
        lines += [
            (
                f"Joined to this project's knowledge graph ([kg/graph.json]({KG_LINK})): every page names the node "
                f"it documents, and states the lineage, policies and decisions the graph holds for it. The graph "
                f"reaches {front['okf_x_kg_models']} model(s); {documented}."
            ),
            "",
        ]
    lines += ["# Tables", ""]
    if over_cap:
        lines.append(
            f"_{over_cap} models are exposed by this project's semantic layer — more than the {cap} an OKF v0.1 "
            f"bundle may hold, so no table is documented here. They are in `mdl/mdl.json`, and every one of them "
            f"is in the knowledge graph. Mark what belongs in the semantic layer with `meta: {{semantic: true}}` "
            f"in dbt, and the rest `false`, to get table pages back._"
        )
    elif bundle is None:
        lines.append("_No models in the semantic layer yet — `pf seed`, then `pf semantic mdl`._")
    else:
        for t in bundle.tables:
            c = concept_of.get(t.name, "")
            tag = f" — `{c}`" if c else ""
            lines.append(f"* [{t.name}](/tables/{t.name}.md){tag} - {_one_line(t.description)}")
    lines += ["", "# Concepts", ""]
    lines += [f"* [{c}](/concepts/{c}.md)" for c in concepts] or ["_none reached by a table_"]
    lines += ["", "# Metrics", ""]
    lines += [f"* [{m.name}](/metrics/{m.name}.md) - {_one_line(m.description)}" for m in f.metrics] or [
        "_no metric yet — `/build-semantic-layer`_"
    ]
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def _table_file(
    t: Any,
    m: dict[str, Any],
    concept: str,
    role_of: dict[str, str],
    withheld: int,
    unnamed: int,
    metrics: list[str],
    gf: GraphFacts | None = None,
    have_table: set[str] | None = None,
) -> str:
    props = m.get("properties") or {}
    front: dict[str, Any] = {
        "type": "Table",  # REQUIRED by OKF; the one key the spec insists on
        "title": t.name,
        "description": _one_line(t.description),
        "okf_x_source_of_truth": t.is_source_of_truth,
        "okf_x_table_confidence": round(t.confidence, 2),
        "okf_x_concept": concept or None,
        "okf_x_layer": props.get("layer") or None,
        "okf_x_grain": _one_line(props.get("grain") or "") or None,
        "okf_x_columns_withheld": withheld,
        "okf_x_kg_node": _kg_node(gf, f"model:{t.name}"),
    }
    if unnamed:
        front["okf_x_columns_unnamed"] = unnamed
    rows = [
        "# Schema",
        "",
        "| Column | Type | Role | Description | Confidence |",
        "|---|---|---|---|---|",
    ]
    for c in t.columns:
        desc = _cell(c.definition)
        if c.references:
            ref_model = c.references.split(".", 1)[0]
            desc = (desc + " " if desc else "") + f"FK to [{ref_model}](/tables/{ref_model}.md)"
        if c.is_primary_key:
            desc = (desc + " " if desc else "") + "(primary key)"
        rows.append(
            f"| `{c.name}` | {c.data_type} | {role_of.get(c.name) or ''} | {desc or '—'} | {c.confidence:.2f} |"
        )
    body = list(rows)
    if concept:
        body += ["", "# Concept", "", f"Instantiates [{concept}](/concepts/{concept}.md)."]
    if metrics:
        body += ["", "# Metrics", ""] + [f"* [{n}](/metrics/{n}.md)" for n in metrics]
    if withheld:
        body += [
            "",
            f"_{withheld} column(s) withheld: masked by policy in the MDL, and not named in a portable file._",
        ]
    if unnamed:
        body += [
            "",
            (
                f"_{unnamed} column(s) left out: the warehouse named them after the expression that produced "
                f"them, which OKF cannot use as a name. Alias them in the model._"
            ),
        ]
    node_id = f"model:{t.name}"
    if gf is not None and gf.has(node_id):
        body += _lineage(gf, node_id, have_table or set())
        body += _governance(gf, [node_id, *gf.columns_of(node_id)], concept)
    return _front(front) + "\n" + "\n".join(body) + "\n"


def _concept_file(f: Facts, cls: Any, platform_defined: bool, tables: list[str]) -> str:
    front: dict[str, Any] = {
        "type": "Concept",
        "title": cls.name,
        "description": _one_line(getattr(cls, "description", "")),
        "okf_x_defined_in": "platform" if platform_defined else "group",
        "okf_x_parent": getattr(cls, "parent", None) or None,
        "okf_x_identity": getattr(cls, "identity", None) or None,
        "okf_x_kg_node": _kg_node(f.graph, f"concept:{cls.name}"),
    }
    if platform_defined:
        front["okf_x_platform_concept"] = _platform_link(f.pdir, f.root, f"concepts/{cls.name}.md")
    else:
        # The tier that declared it. Before the group bundle existed this page
        # named the YAML file and stopped there, which is a path, not a link:
        # the definition every sister shares was the one thing a reader of a
        # project bundle could not follow.
        front["okf_x_group_concept"] = _link(
            f.pdir / OKF_REL, group_bundle(f.root, f.group), f"concepts/{cls.name}.md"
        )
    lines = []
    if platform_defined:
        lines += [f"Defined by the platform ontology: [{cls.name}]({front['okf_x_platform_concept']})."]
    else:
        lines += [
            (
                f"Declared by this family: [{cls.name}]({front['okf_x_group_concept']}) in "
                f"`groups/{f.group}/ontology/extension.yaml`, shared by every sister of `{f.group}`."
            )
        ]
    lines += ["", "# Instantiated by", ""] + [f"* [{t}](/tables/{t}.md)" for t in tables]
    props = getattr(cls, "properties", {}) or {}
    if props:
        lines += ["", "# Properties", "", "| Property | Datatype | Role |", "|---|---|---|"]
        lines += [
            f"| `{n}` | {getattr(p, 'datatype', '')} | {getattr(p, 'role', '') or ''} |"
            for n, p in sorted(props.items())
        ]
    if f.onto is not None:
        rels = sorted(f.onto.relations_for(cls.name), key=lambda r: r.name) if hasattr(f.onto, "relations_for") else []
        if rels:
            lines += ["", "# Relations", ""] + [f"* {r.describe()} — {_one_line(r.description)}" for r in rels]
    if f.graph is not None and f.graph.has(f"concept:{cls.name}"):
        sources = f.graph.upstream(f"concept:{cls.name}", "Table", edge="instantiates")
        if sources:
            lines += ["", "# Raw tables that instantiate it", ""] + [
                f"* `{str(n.get('id') or '').split(':', 1)[-1]}`" for n in sources
            ]
        lines += _governance(f.graph, [f"concept:{cls.name}"], cls.name)
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def _metric_file(ms: Any, gf: GraphFacts | None = None, have_metric: set[str] | None = None) -> str:
    front: dict[str, Any] = {
        "type": "Metric",
        "title": ms.label or ms.name,
        "description": _one_line(ms.description),
        "okf_x_kind": ms.kind,
        "okf_x_model": ms.model or None,
        "okf_x_time_column": ms.time_column or None,
        "okf_x_kg_node": _kg_node(gf, f"metric:{ms.name}"),
    }
    lines = [
        "# Definition",
        "",
        f"* **Kind:** `{ms.kind}`",
        f"* **Expression:** `{ms.expression}`" if ms.expression else "* **Expression:** derived",
    ]
    if ms.numerator or ms.denominator:
        lines.append(
            f"* **Ratio:** `{ms.numerator}` / `{ms.denominator}` — re-divide at the reading grain, "
            "never average the ratio"
        )
    if ms.model:
        lines.append(f"* **Built on:** [{ms.model}](/tables/{ms.model}.md)")
    if ms.dimensions:
        lines.append("* **Dimensions:** " + ", ".join(f"`{d}`" for d in ms.dimensions))
    if ms.filter_sql:
        lines.append(f"* **Filter:** `{ms.filter_sql}`")
    node_id = f"metric:{ms.name}"
    if gf is not None and gf.has(node_id):
        # A derived metric hangs off the metric it is built from, not off a
        # model, so no table page can name it. Said here or nowhere: changing
        # this definition changes every metric below it.
        built_from = gf.upstream(node_id, "Metric")
        if built_from:
            lines.append(
                "* **Built from:** "
                + ", ".join(_ref(str(n.get("name") or ""), have_metric or set(), "metrics") for n in built_from)
            )
        derived = gf.downstream(node_id, "Metric")
        if derived:
            lines.append(
                "* **Derived from it:** "
                + ", ".join(_ref(str(n.get("name") or ""), have_metric or set(), "metrics") for n in derived)
            )
        lines += _governance(gf, [node_id], "")
    return _front(front) + "\n" + "\n".join(lines) + "\n"


def _concept_page(onto: Any, cls: Any, *, tier: str, up: str = "", roles_dir: str = "/roles") -> str:
    """One ontology class, in whichever tier declares it.

    The platform's and a group's concept pages are the same page — a class, its
    properties, the relations it takes part in, the policies that govern it —
    and were two renderers until the group tier existed. One renderer is also
    what keeps the two tiers readable as one vocabulary.
    """
    front: dict[str, Any] = {
        "type": "Concept",
        "title": cls.name,
        "description": _one_line(getattr(cls, "description", "")),
        "okf_x_tier": tier,
        "okf_x_parent": getattr(cls, "parent", None) or None,
        "okf_x_abstract": bool(getattr(cls, "abstract", False)),
        "okf_x_identity": getattr(cls, "identity", None) or None,
    }
    if up:
        front["okf_x_platform_concept"] = up
    body: list[str] = []
    if up:
        body += [f"Extends the platform's [{cls.name}]({up}); this page is what this family added.", ""]
    props = getattr(cls, "properties", {}) or {}
    if props:
        body += ["# Properties", "", "| Property | Datatype | Role |", "|---|---|---|"]
        body += [
            f"| `{n}` | {getattr(p, 'datatype', '')} | "
            + (f"[{p.role}]({roles_dir}/{p.role}.md)" if getattr(p, "role", "") else "")
            + " |"
            for n, p in sorted(props.items())
        ]
    rels = sorted(onto.relations_for(cls.name), key=lambda r: r.name) if hasattr(onto, "relations_for") else []
    if rels:
        body += ["", "# Relations", ""]
        body += [f"* [{r.name}](/relations/{r.name}.md) — {r.describe()}" for r in rels]
    governed = sorted(
        (p for p in getattr(onto, "policies", []) if (p.applies_to or {}).get("class") == cls.name),
        key=lambda p: p.id,
    )
    if governed:
        body += ["", "# Governance", ""]
        body += [
            f"* `{p.id}` ({p.severity}) — {_one_line(p.intent).split('. ')[0]}." for p in governed
        ]
    return _front(front) + "\n" + "\n".join(body or ["_no properties declared_"]) + "\n"


def _role_page(onto: Any, role: Any, *, tier: str, up: str = "") -> str:
    front: dict[str, Any] = {
        "type": "Role",
        "title": role.name,
        "description": _one_line(getattr(role, "description", "")),
        "okf_x_tier": tier,
        "okf_x_datatype": getattr(role, "datatype", None) or None,
        "okf_x_pii": bool(getattr(role, "pii", False)),
        "okf_x_review": getattr(role, "review", None) or None,
    }
    if up:
        front["okf_x_platform_role"] = up
    policies = onto.policies_for_role(role.name) if hasattr(onto, "policies_for_role") else []
    body = ([f"Overrides the platform's [{role.name}]({up}) for this family.", ""] if up else []) + [
        "# Policies",
        "",
    ]
    body += [
        f"* `{p.id}` — {_one_line(getattr(p, 'description', '') or getattr(p, 'intent', ''))}"
        for p in sorted(policies, key=lambda p: p.id)
    ] or ["_none bound to this role_"]
    return _front(front) + "\n" + "\n".join(body) + "\n"


def _relation_page(rel: Any, *, tier: str, concept_link: Any) -> str:
    """A named relation, addressable.

    Relations were described inside the concept pages of both ends and had no
    page of their own, so the one object the topology exists to name — the verb
    between two classes — was the one an agent could not link to.
    """
    front = {
        "type": "Relation",
        "title": rel.name,
        "description": _one_line(getattr(rel, "description", "")) or rel.describe(),
        "okf_x_tier": tier,
        "okf_x_domain": rel.domain,
        "okf_x_range": rel.range,
        "okf_x_cardinality": rel.cardinality,
        "okf_x_inverse": getattr(rel, "inverse", None) or None,
    }
    body = [
        "# Reading it",
        "",
        f"* {rel.describe()}",
        f"* Reverse: {rel.describe(reverse=True)}",
        "",
        "# Between",
        "",
        f"* Domain: {concept_link(rel.domain)}",
        f"* Range: {concept_link(rel.range)}",
    ]
    return _front(front) + "\n" + "\n".join(body) + "\n"


def build_group(root: str | Path, group: str) -> dict[str, str]:
    """A family's own vocabulary as OKF: what its extension declares, and nothing
    it merely inherited — that is one link up, in the platform bundle."""
    root = Path(root)
    from pf.ontology.model import load_group_ontology, load_ontology

    onto = load_group_ontology(root, group)
    platform = load_ontology()
    declared = group_terms(root, group)
    bundle = group_bundle(root, group)
    up = root / PLATFORM_REL

    classes = [onto.classes[n] for n in sorted(declared["classes"]) if n in onto.classes]
    roles = [onto.roles[n] for n in sorted(declared["roles"]) if n in onto.roles]
    relations = sorted((r for r in onto.relations if r.name in declared["relations"]), key=lambda r: r.name)

    def concept_link(name: str) -> str:
        if name in declared["classes"]:
            return f"[{name}](/concepts/{name}.md)"
        return f"[{name}]({_link(bundle, up, f'concepts/{name}.md')})"

    front = {
        "okf_version": "0.1",
        "name": f"{group} ontology",
        "okf_x_scope": "group",
        "okf_x_group": group,
        "okf_x_platform_bundle": _link(bundle, up, "index.md"),
        "okf_x_concepts": len(classes),
        "okf_x_roles": len(roles),
        "okf_x_relations": len(relations),
    }
    lines = [
        f"# {group} ontology",
        "",
        f"Generated by `pf tool okf build --group {group}` from `groups/{group}/ontology/`. What",
        "this family declared on top of the platform vocabulary — the terms a steward approved,",
        "or that were written by hand when no platform class described the business. Every",
        f"sister in `{group}` shares exactly this; another family never inherits a word of it.",
        "",
        f"Everything else this family uses is the platform's: [{PLATFORM_NAME}]({front['okf_x_platform_bundle']}).",
        "",
        "# Concepts",
        "",
    ]
    lines += [
        f"* [{c.name}](/concepts/{c.name}.md) - {_one_line(getattr(c, 'description', ''))}" for c in classes
    ] or ["_this family declares no class of its own_"]
    lines += ["", "# Roles", ""]
    lines += [
        f"* [{r.name}](/roles/{r.name}.md) - {_one_line(getattr(r, 'description', ''))}" for r in roles
    ] or ["_no role of its own; the platform's roles carry every column here_"]
    lines += ["", "# Relations", ""]
    lines += [f"* [{r.name}](/relations/{r.name}.md) - {r.describe()}" for r in relations] or [
        "_no relation of its own_"
    ]

    files: dict[str, str] = {"log.md": LOG, "index.md": _front(front) + "\n" + "\n".join(lines) + "\n"}
    for c in classes:
        link = _link(bundle, up, f"concepts/{c.name}.md") if c.name in platform.classes else ""
        files[f"concepts/{c.name}.md"] = _concept_page(onto, c, tier="group", up=link)
    for r in roles:
        link = _link(bundle, up, f"roles/{r.name}.md") if r.name in platform.roles else ""
        files[f"roles/{r.name}.md"] = _role_page(onto, r, tier="group", up=link)
    for rel in relations:
        files[f"relations/{rel.name}.md"] = _relation_page(rel, tier="group", concept_link=concept_link)
    return files


def build_platform(root: str | Path) -> dict[str, str]:
    """The platform ontology itself as an OKF bundle: one concept per class, one per role."""
    root = Path(root)
    from pf.ontology.model import load_ontology

    onto = load_ontology()
    files: dict[str, str] = {"log.md": LOG}
    classes = sorted(onto.classes.values(), key=lambda c: c.name)
    roles = sorted(onto.roles.values(), key=lambda r: r.name)
    relations = sorted(onto.relations, key=lambda r: r.name)
    front = {
        "okf_version": "0.1",
        "name": PLATFORM_NAME,
        "okf_x_scope": "platform",
        "okf_x_concepts": len(classes),
        "okf_x_roles": len(roles),
        "okf_x_relations": len(relations),
    }
    lines = [
        f"# {PLATFORM_NAME}",
        "",
        "Generated by `pf tool okf build --platform` from `platform/src/pf/ontology/`. Every",
        "group's and project's bundle links its concepts here; what a role means is",
        "declared once, for every sister.",
        "",
        "# Concepts",
        "",
    ]
    lines += [f"* [{c.name}](/concepts/{c.name}.md) - {_one_line(getattr(c, 'description', ''))}" for c in classes]
    lines += ["", "# Roles", ""]
    lines += [f"* [{r.name}](/roles/{r.name}.md) - {_one_line(getattr(r, 'description', ''))}" for r in roles]
    lines += ["", "# Relations", ""]
    lines += [f"* [{r.name}](/relations/{r.name}.md) - {r.describe()}" for r in relations]
    files["index.md"] = _front(front) + "\n" + "\n".join(lines) + "\n"
    for c in classes:
        files[f"concepts/{c.name}.md"] = _concept_page(onto, c, tier="platform")
    for r in roles:
        files[f"roles/{r.name}.md"] = _role_page(onto, r, tier="platform")
    for rel in relations:
        files[f"relations/{rel.name}.md"] = _relation_page(
            rel, tier="platform", concept_link=lambda n: f"[{n}](/concepts/{n}.md)"
        )
    return files


# ------------------------------------------------------------------ write ---
def _sync(out: Path, files: dict[str, str]) -> tuple[list[Path], list[Path]]:
    """Write what differs; remove concept files the bundle no longer has."""
    written, removed = [], []
    for rel, text in files.items():
        p = out / rel
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(text, encoding="utf-8")
            written.append(p)
    for sub in ("tables", "concepts", "metrics", "roles", "relations"):
        d = out / sub
        if not d.is_dir():
            continue
        for p in sorted(d.glob("*.md")):
            if f"{sub}/{p.name}" not in files:
                p.unlink()
                removed.append(p)
    return written, removed


def write_project(root: str | Path, group: str, project: str) -> dict[str, Any]:
    root = Path(root)
    out = root / "groups" / group / "projects" / project / OKF_REL
    files = build_project(root, group, project)
    written, removed = _sync(out, files)
    return {
        "path": out,
        "tables": sum(1 for k in files if k.startswith("tables/")),
        "concepts": sum(1 for k in files if k.startswith("concepts/")),
        "metrics": sum(1 for k in files if k.startswith("metrics/")),
        "written": len(written),
        "removed": len(removed),
    }


def write_group(root: str | Path, group: str) -> dict[str, Any]:
    root = Path(root)
    out = group_bundle(root, group)
    files = build_group(root, group)
    written, removed = _sync(out, files)
    return {
        "path": out,
        "concepts": sum(1 for k in files if k.startswith("concepts/")),
        "roles": sum(1 for k in files if k.startswith("roles/")),
        "relations": sum(1 for k in files if k.startswith("relations/")),
        "written": len(written),
        "removed": len(removed),
    }


def write_platform(root: str | Path) -> dict[str, Any]:
    root = Path(root)
    out = root / PLATFORM_REL
    files = build_platform(root)
    written, removed = _sync(out, files)
    return {
        "path": out,
        "concepts": sum(1 for k in files if k.startswith("concepts/")),
        "roles": sum(1 for k in files if k.startswith("roles/")),
        "relations": sum(1 for k in files if k.startswith("relations/")),
        "written": len(written),
        "removed": len(removed),
    }


# ------------------------------------------------------------------ check ---
_FRONT = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def conformance(bundle_dir: str | Path) -> list[str]:
    """OKF v0.1 §8: every non-reserved file has parseable frontmatter with a non-empty `type`."""
    d = Path(bundle_dir)
    problems = []
    if not (d / "index.md").is_file():
        return [f"{d}: no index.md"]
    for p in sorted(d.rglob("*.md")):
        rel = p.relative_to(d).as_posix()
        if rel in RESERVED:
            continue
        m = _FRONT.match(p.read_text(encoding="utf-8"))
        if not m:
            problems.append(f"{rel}: no YAML frontmatter")
            continue
        try:
            meta = yaml.safe_load(m.group(1)) or {}
        except yaml.YAMLError as exc:
            problems.append(f"{rel}: frontmatter is not YAML ({exc})")
            continue
        if not str(meta.get("type") or "").strip():
            problems.append(f"{rel}: frontmatter has no `type`")
    return problems


def _drift(out: Path, files: dict[str, str]) -> list[str]:
    problems = []
    for rel, text in files.items():
        p = out / rel
        if not p.is_file():
            problems.append(f"{rel}: missing")
        elif p.read_text(encoding="utf-8") != text:
            problems.append(f"{rel}: stale")
    for sub in ("tables", "concepts", "metrics", "roles", "relations"):
        d = out / sub
        for p in sorted(d.glob("*.md")) if d.is_dir() else []:
            if f"{sub}/{p.name}" not in files:
                problems.append(f"{sub}/{p.name}: no longer in the semantic layer")
    return problems


def check_project(root: str | Path, group: str, project: str) -> list[str]:
    """Empty when the committed bundle is what the semantic layer projects, and conformant."""
    root = Path(root)
    out = root / "groups" / group / "projects" / project / OKF_REL
    if not out.is_dir():
        return [f"{group}/{project}: no okf/ — run `pf tool okf build {group} {project}`"]
    problems = [f"{group}/{project}: {x}" for x in _drift(out, build_project(root, group, project))]
    problems += [f"{group}/{project}: {x}" for x in conformance(out)]
    problems += [f"{group}/{project}: {x}" for x in reconcile(root, group, project).problems]
    return problems


# ------------------------------------------------------------------- join ---
#: The frontmatter key every page uses to name its graph node.
KG_NODE_KEY = "okf_x_kg_node"


def page_rel(kind: str, name: str) -> str:
    """Where a graph node of this kind is documented, by convention.

    One definition of the convention, so the graph side can answer "where is
    this written down" without importing the projection or storing a path on a
    node — a path stored in the graph is one build behind the day a project
    gains its first model, and wrong forever if the bundle is rebuilt without it.
    """
    folder = {"Model": "tables", "Concept": "concepts", "Metric": "metrics"}.get(kind, "")
    return f"{OKF_REL}/{folder}/{name}.md" if folder and name else ""


def frontmatter(path: str | Path) -> dict[str, Any]:
    """A page's YAML frontmatter, or {} for anything unparseable."""
    m = _FRONT.match(Path(path).read_text(encoding="utf-8"))
    if not m:
        return {}
    try:
        return yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        return {}


@dataclass
class Join:
    """How the committed bundle and the committed graph line up.

    `exercised` is the honest third answer, for the same reason `GraphDrift` has
    one: a project with no graph or no bundle cannot be judged, and reporting
    that as "joined" would be the green tick for "found nothing" that every gate
    here refuses to give.
    """

    group: str
    project: str
    exercised: bool
    reason: str = ""
    pages: int = 0
    resolved: int = 0
    dangling: list[str] = field(default_factory=list)
    undocumented: list[str] = field(default_factory=list)

    @property
    def problems(self) -> list[str]:
        """Only a dangling node is a problem. A graph model with no page is the
        design — the bundle documents what the semantic layer projects to BI,
        and the graph reaches every staging model behind it."""
        return [
            f"{rel}: names `{node}`, which kg/graph.json does not hold — "
            f"the bundle and the graph were rebuilt independently"
            for rel, node in (d.split(" -> ", 1) for d in self.dangling)
        ]

    def render(self) -> str:
        who = f"{self.group}/{self.project}"
        if not self.exercised:
            return f"?  {who} — not exercised: {self.reason}"
        if self.dangling:
            lines = [f"⛔ {who} — {len(self.dangling)} page(s) name a node the graph does not hold"]
            lines += [f"     {d}" for d in sorted(self.dangling)[:8]]
            lines.append("     run `pf kg build` then `pf tool okf build`, and commit both")
            return "\n".join(lines)
        named = self.resolved + len(self.dangling)
        bits = [f"{self.resolved}/{named} page(s) resolve in the graph"]
        # A page with no node id at all is not a failure and not a success: the
        # graph did not hold its subject when the bundle was built. Saying so is
        # the difference between "joined" and "nothing to join".
        if self.pages > named:
            bits.append(f"{self.pages - named} name no node")
        if self.undocumented:
            bits.append(f"{len(self.undocumented)} graph model(s) below the documented layer")
        return f"✓  {who} — " + " · ".join(bits)


def reconcile(root: str | Path, group: str, project: str) -> Join:
    """Read the committed bundle against the committed graph. Neither is rebuilt.

    `check_project` rebuilds the bundle and compares, which catches a stale
    bundle by definition. This asks the other question: do the two artefacts
    agree *as committed*? A graph rebuilt after a model was renamed, committed
    without its bundle, leaves pages pointing at nodes that no longer exist —
    and every agent that follows one reads a file about a model the warehouse
    does not have.
    """
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    out = pdir / OKF_REL
    if not out.is_dir():
        return Join(group, project, False, f"no okf/ — run `pf tool okf build {group} {project}`")
    gf = load_graph(pdir)
    if gf is None:
        return Join(group, project, False, "no kg/graph.json; the graph has never been built")

    join = Join(group, project, True)
    for page in sorted(out.rglob("*.md")):
        rel = page.relative_to(out).as_posix()
        if rel in RESERVED:
            continue
        join.pages += 1
        node = str(frontmatter(page).get(KG_NODE_KEY) or "")
        if not node:
            continue  # a page the graph did not reach when the bundle was built
        if gf.has(node):
            join.resolved += 1
        else:
            join.dangling.append(f"{rel} -> {node}")
    documented = {p.stem for p in (out / "tables").glob("*.md")} if (out / "tables").is_dir() else set()
    join.undocumented = [n for n in gf.named("Model") if n not in documented]
    return join


def check_platform(root: str | Path) -> list[str]:
    root = Path(root)
    out = root / PLATFORM_REL
    if not out.is_dir():
        return ["platform: no platform/okf/ — run `pf tool okf build --platform`"]
    return [f"platform: {x}" for x in _drift(out, build_platform(root))] + [f"platform: {x}" for x in conformance(out)]


def check_group(root: str | Path, group: str) -> list[str]:
    """Is the family's bundle what its extension declares?

    The gate that makes approval mean something: `pf semantic approve` merges a
    term into `extension.yaml` and rebuilds everything downstream, and this is
    what notices when one of those rebuilds did not happen.
    """
    root = Path(root)
    out = group_bundle(root, group)
    if not out.is_dir():
        return [f"{group}: no groups/{group}/okf/ — run `pf tool okf build --group {group}`"]
    return [f"{group}: {x}" for x in _drift(out, build_group(root, group))] + [
        f"{group}: {x}" for x in conformance(out)
    ]
