"""Project the ontology, topology and annotations into OpenMetadata entities.

## What this is, and what it deliberately is not

OpenMetadata is a **projection target**, exactly like the MDL and OWL exports
beside this module. The ontology stays canonical in YAML, under git, judged by
`pf check` and the gate — the same decision the governance layer already made
when it put owner edits behind an audit row and left the file authoritative.
Nothing here reads *from* OpenMetadata, and nothing here is a two-way sync. A
catalogue that can silently redefine a concept is a second source of truth, and
then neither side can be trusted to say what `Customer` means.

So the flow is one-way and idempotent:

    concepts.yaml  ->  Glossary + GlossaryTerms
    roles          ->  Classification + Tags   (PII roles included)
    topology       ->  relatedTerms between glossary terms
    policies       ->  term descriptions carrying the constraint
    annotations    ->  tagLabels on columns
    metrics        ->  Metric entities

## Tables: excluded on principle until the principle stopped holding

This module used to end with "what this does NOT emit, on purpose: tables,
columns and lineage", because `metadata ingest-dbt` ingests those from the dbt
artefacts, column-level lineage included, better than a re-derivation could.
Emitting from both sides would give the catalogue two descriptions of one table,
drifting apart, showing whichever ran last. That argument is still correct and
still governs — where the dbt connector can run.

It cannot run here. OpenMetadata's dbt ingestion *enriches* tables a database
service already catalogued, and cataloguing them needs a live warehouse
connection. This platform develops on DuckDB, for which OpenMetadata 1.13 ships
no connector at all: the plugin list is clickhouse, postgres, snowflake, dbt and
datalake-*. So a developer with 2,176 real tables on their laptop could put none
of them in the catalogue and had to wait on production credentials to look at
their own project.

`build_database_entities` closes that gap and is careful not to reopen the one
the old rule guarded. It reads the same two files the dbt connector reads —
`manifest.json` for models, schemas, descriptions and column docs,
`catalog.json` for the types the warehouse actually produced — so there is one
source, not two. And it publishes under a **CustomDatabase** service, which is
OpenMetadata's own type for metadata pushed by its owner rather than crawled:
the catalogue never claims a connection it does not have, and a real connector
pointed at the same service later supersedes it rather than fighting it.

## Conformance

Every payload is validated against the vendored JSON Schemas in
`vendor/openmetadata-standards/schemas/api/`, which is why that submodule is
pinned with `kind: schema` in the vendor registry: if upstream adds a required
field, the test fails here rather than at ingestion time against a live server.

Names are constrained by OpenMetadata's `entityName`: 1-256 characters and no
`::`, because `::` is the separator in the `entityLink` grammar. `_om_name`
enforces it rather than trusting our identifiers to be safe by luck.
"""

from __future__ import annotations

import re
from typing import Any

from pf.ontology.model import Ontology

#: OpenMetadata's `entityName` forbids `::` — it separates fields in entityLink.
_ILLEGAL = re.compile(r"::+")

#: Ours, not OpenMetadata's. Kept as constants because the ingestion workflow and
#: the tests both have to name the same glossary, and a literal in two files is a
#: rename waiting to break one of them.
GLOSSARY_NAME = "Platform Ontology"
ROLE_CLASSIFICATION = "PlatformRole"


def _om_name(value: str) -> str:
    """A string safe to use as an OpenMetadata entityName."""
    cleaned = _ILLEGAL.sub("_", (value or "").strip())
    return cleaned[:256] or "unnamed"


def _description(text: str, fallback: str) -> str:
    """`description` is required on glossaries, terms, tags and classifications.

    An empty string satisfies the schema and tells a reader nothing, so an
    undocumented concept says so explicitly. That reads as a gap in the ontology,
    which it is, rather than as a blank someone might assume was intentional.
    """
    return (text or "").strip() or fallback


# ------------------------------------------------------------------ glossary --
def build_glossary(onto: Ontology) -> dict[str, Any]:
    """The glossary itself. One per platform, not per group.

    Sisters share the ontology by construction — that is what makes them
    sisters — so a glossary per group would publish the same concepts several
    times and invite them to diverge in the catalogue.
    """
    return {
        "name": _om_name(GLOSSARY_NAME),
        "displayName": GLOSSARY_NAME,
        "description": (
            f"Business vocabulary projected from this platform's ontology "
            f"(version {onto.version}). Generated by `pf openmetadata sync` — "
            f"edit `platform/src/pf/ontology/concepts.yaml`, not the catalogue."),
        "provider": "user",
        "mutuallyExclusive": False,
    }


def _term_fqn(onto: Ontology, name: str) -> str:
    """A glossary term's fully-qualified name, parents included.

    OpenMetadata nests a term under its parent, so `Customer` — a `Party` —
    lives at `Platform Ontology.Party.Customer`, not `Platform Ontology.Customer`.
    Every reference to a term has to use that full path or the server 404s on it.

    This was flat, and the flaw was invisible because nothing ever sent the
    payload: the glossary was built, written to `catalog/openmetadata.json`, and
    never published. The first real publish rejected 13 of 26 terms' relations
    with "glossaryTerm instance for Platform Ontology.Customer not found" — the
    term existed, one level deeper than the reference claimed.

    `parent` had the same defect and got away with it, because every parent in
    the current ontology is top-level, so one hop and the full path agree. A
    three-level hierarchy would have broken it the same way.

    The walk is guarded against a cycle in the parent chain. A class that is its
    own ancestor is a broken ontology, but it should surface as a validation
    error from `pf check`, not as an infinite loop inside a projection.
    """
    chain: list[str] = []
    seen: set[str] = set()
    current: str | None = name
    while current and current not in seen and onto.has_class(current):
        seen.add(current)
        chain.append(_om_name(current))
        current = onto.classes[current].parent
    return ".".join([_om_name(GLOSSARY_NAME), *reversed(chain)])


def build_glossary_terms(onto: Ontology) -> list[dict[str, Any]]:
    """One term per ontology class, carrying its identity, properties and relations.

    Abstract classes are included. A reader looking up `Customer` needs to know
    it is a `Party`, and dropping the parents would leave the hierarchy with
    holes at exactly the points where the shared meaning lives.
    """
    terms: list[dict[str, Any]] = []
    for name, cls in sorted(onto.classes.items()):
        identity = onto.identity_of(name)
        props = onto.properties_of(name)

        detail = [_description(cls.description, f"{name} — no description in the ontology.")]
        if cls.abstract:
            detail.append("\n\n_Abstract: no instance is recorded directly against it._")
        if identity:
            detail.append(f"\n\n**Identified by:** `{identity}`")
        if props:
            rows = "\n".join(
                f"| `{p}` | {v.datatype} | {v.role or '—'} | "
                f"{'yes' if getattr(v, 'required', False) else 'no'} |"
                for p, v in sorted(props.items()))
            detail.append(
                "\n\n**Properties**\n\n"
                "| Property | Type | Role | Required |\n|---|---|---|---|\n" + rows)

        # Relations become prose in the description as well as structured
        # relatedTerms: the catalogue's term page shows the description first,
        # and "a Customer holds a Subscription" is the sentence a person needs.
        rels = onto.relations_for(name)
        if rels:
            detail.append("\n\n**Relations**\n\n"
                          + "\n".join(f"- {r.describe()}" for r in rels))

        term: dict[str, Any] = {
            "glossary": _om_name(GLOSSARY_NAME),
            "name": _om_name(name),
            "displayName": name,
            "description": "".join(detail),
            "provider": "user",
        }
        if cls.parent:
            term["parent"] = _term_fqn(onto, cls.parent)

        related = sorted({r.range for r in rels if r.range != name}
                         | {r.domain for r in rels if r.domain != name})
        if related:
            term["relatedTerms"] = [
                _term_fqn(onto, x) for x in related if onto.has_class(x)]
        terms.append(term)
    return terms


# ------------------------------------------------------------ classification --
def build_classification() -> dict[str, Any]:
    return {
        "name": _om_name(ROLE_CLASSIFICATION),
        "displayName": "Platform role",
        "description": (
            "Semantic roles this platform assigns to columns — what a column *is*, "
            "independent of what it was named in the source. Drives review "
            "coverage, PII handling and the semantic layer."),
        "provider": "user",
        # Roles are not mutually exclusive: one column can be both a natural key
        # and an event time in different projections.
        "mutuallyExclusive": False,
    }


def build_tags(onto: Ontology) -> list[dict[str, Any]]:
    """One tag per ontology role, with PII called out in the description.

    PII is *also* mapped onto OpenMetadata's built-in `PII.Sensitive` tag by
    `pii_tag_labels`, because that is the tag the catalogue's own policies and
    auto-classification already understand. Publishing our role names only would
    make the platform's PII invisible to every rule OpenMetadata ships with.
    """
    tags: list[dict[str, Any]] = []
    for name, role in sorted(onto.roles.items()):
        desc = _description(role.description, f"Columns carrying the {name} role.")
        if role.pii:
            desc += ("\n\n**Personal data.** Excluded from value-level review "
                     "diffs, and never written into a review artefact.")
        tags.append({
            "classification": _om_name(ROLE_CLASSIFICATION),
            "name": _om_name(name),
            "displayName": name,
            "description": desc,
            "provider": "user",
            "mutuallyExclusive": False,
        })
    return tags


def pii_tag_labels(onto: Ontology) -> dict[str, list[dict[str, Any]]]:
    """Role -> the tagLabels a column with that role should carry.

    Every role gets its platform tag. PII roles additionally get OpenMetadata's
    built-in `PII.Sensitive`, so the catalogue's existing policies apply without
    anyone reconfiguring them against our vocabulary.
    """
    out: dict[str, list[dict[str, Any]]] = {}
    for name, role in sorted(onto.roles.items()):
        labels = [{
            "tagFQN": f"{_om_name(ROLE_CLASSIFICATION)}.{_om_name(name)}",
            "source": "Classification", "labelType": "Automated", "state": "Suggested",
        }]
        if role.pii:
            labels.append({
                "tagFQN": "PII.Sensitive", "source": "Classification",
                "labelType": "Automated", "state": "Suggested",
            })
        out[name] = labels
    return out


# --------------------------------------------------------------------- policy --
def build_policy_terms(onto: Ontology) -> list[dict[str, Any]]:
    """Policies as glossary terms, so a constraint is discoverable beside the concept.

    OpenMetadata's own `policies` are access control — who may read what. Ours
    are data constraints ("no PII in a review artefact"), which is a different
    thing wearing the same word. Publishing them as access policies would be a
    category error with security consequences, so they are published as terms
    and the distinction is stated in the description.
    """
    terms: list[dict[str, Any]] = []
    for p in onto.policies:
        body = [
            f"**Intent:** {_description(p.intent, 'not stated')}",
            f"\n\n**Constraint:** `{p.constraint}`",
            f"\n\n**Severity:** {p.severity}",
        ]
        body.append(
            f"\n\n**Enforced by:** {', '.join(p.enforced_by) or 'nothing yet'}"
            if getattr(p, "enforced_by", None) else "\n\n**Enforced by:** nothing yet")
        body.append(
            "\n\n_This is a data constraint from the platform's policy layer, "
            "not an OpenMetadata access-control policy._")
        terms.append({
            "glossary": _om_name(GLOSSARY_NAME),
            "name": _om_name(f"policy_{p.id}"),
            "displayName": f"Policy: {p.id}",
            "description": "".join(body),
            "provider": "user",
        })
    return terms


# -------------------------------------------------------------------- metrics --
def build_metrics(metrics: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Governed metric definitions as OpenMetadata Metric entities.

    Takes the platform's metric rows rather than reading MetricFlow or the MDL
    directly, so one mapping serves both and this module does not grow a
    dependency on either tool being installed.
    """
    out: list[dict[str, Any]] = []
    for m in metrics:
        name = m.get("name") or ""
        if not name:
            continue
        entry: dict[str, Any] = {
            "name": _om_name(name),
            "displayName": m.get("label") or name,
            "description": _description(
                m.get("description", ""),
                f"{name} — defined in the platform's semantic layer."),
        }
        if m.get("expression"):
            entry["metricExpression"] = {
                "language": "SQL", "code": str(m["expression"])}
        if m.get("metric_type"):
            entry["metricType"] = m["metric_type"]
        if m.get("unit"):
            entry["unitOfMeasurement"] = m["unit"]
        out.append(entry)
    return out


# ---------------------------------------------------------------------- bundle --
def build_all(onto: Ontology,
              metrics: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    """Everything this platform publishes to the catalogue, in one payload.

    Ordered as it must be applied: a term cannot reference a glossary that does
    not exist, and a tag cannot reference a missing classification. The consumer
    walks the keys in this order rather than re-deriving the dependency.
    """
    return {
        "glossary": build_glossary(onto),
        "glossary_terms": build_glossary_terms(onto) + build_policy_terms(onto),
        "classification": build_classification(),
        "tags": build_tags(onto),
        "column_tag_labels": pii_tag_labels(onto),
        "metrics": build_metrics(metrics or []),
    }


# ---------------------------------------------------------------- tables --
#: Warehouse column types mapped onto OpenMetadata's `dataType` enum. Longest
#: prefixes first, so DOUBLE is not matched by DATE and TIMESTAMP not by TIME.
#: Anything unmatched becomes UNKNOWN and keeps its original spelling in
#: `dataTypeDisplay` — a type this table has not met is then visible in the
#: catalogue rather than silently recorded as a string.
COLUMN_TYPES: tuple[tuple[str, str], ...] = (
    ("TIMESTAMP", "TIMESTAMP"), ("DATETIME", "DATETIME"), ("DATE", "DATE"),
    ("TIME", "TIME"), ("INTERVAL", "INTERVAL"),
    ("BIGINT", "BIGINT"), ("HUGEINT", "BIGINT"), ("SMALLINT", "SMALLINT"),
    ("TINYINT", "TINYINT"), ("INTEGER", "INT"), ("INT", "INT"),
    ("DOUBLE", "DOUBLE"), ("FLOAT", "FLOAT"), ("REAL", "FLOAT"),
    ("DECIMAL", "DECIMAL"), ("NUMERIC", "NUMERIC"),
    ("BOOLEAN", "BOOLEAN"), ("BOOL", "BOOLEAN"),
    ("JSON", "JSON"), ("UUID", "UUID"), ("BLOB", "BINARY"),
    ("STRUCT", "STRUCT"), ("MAP", "MAP"), ("ARRAY", "ARRAY"), ("LIST", "ARRAY"),
    ("VARCHAR", "VARCHAR"), ("CHAR", "CHAR"), ("TEXT", "TEXT"), ("STRING", "STRING"),
)

#: dbt resource types that become a catalogue table. A source is `External`
#: because dbt does not build it — dlt or a seed lands it — and the catalogue
#: should not imply this project owns its production.
TABLE_TYPES: dict[str, str] = {
    "model": "Regular", "snapshot": "Regular", "seed": "Regular",
    "source": "External",
}


#: Types OpenMetadata refuses without a `dataLength`:
#: "For column data types char, varchar, binary, varbinary dataLength must not
#: be null". DuckDB's VARCHAR is unbounded and carries no length at all, so
#: there is nothing true to send and one has to be chosen.
LENGTH_REQUIRED = frozenset({"CHAR", "VARCHAR", "BINARY", "VARBINARY"})

#: Used only when the warehouse states no length. Deliberately large: it is a
#: declared "unbounded" rather than a guess at the data, and a reader who sees
#: 65535 on every string column can tell it is a convention. A small number
#: would look measured and be wrong.
UNBOUNDED_LENGTH = 65535


def column_type(raw: str) -> tuple[str, str, int | None]:
    """(dataType, dataTypeDisplay, dataLength) for one warehouse type string.

    The length is parsed out of the declaration when the warehouse gives one —
    `VARCHAR(50)` — and falls back to `UNBOUNDED_LENGTH` for the types
    OpenMetadata insists on a length for. `None` for everything else, so an
    INTEGER is not given a meaningless width.
    """
    up = (raw or "").upper().strip()
    for needle, mapped in COLUMN_TYPES:
        if not up.startswith(needle):
            continue
        length: int | None = None
        if mapped in LENGTH_REQUIRED:
            declared = re.search(r"\((\d+)", up)
            length = int(declared.group(1)) if declared else UNBOUNDED_LENGTH
        return mapped, raw or mapped, length
    return "UNKNOWN", raw or "UNKNOWN", None


def build_database_entities(
    manifest: dict[str, Any],
    catalog: dict[str, Any],
    *,
    service: str,
    fallback_database: str,
    column_roles: dict[str, str] | None = None,
    column_tag_labels: dict[str, list[dict[str, Any]]] | None = None,
) -> dict[str, Any]:
    """dbt artefacts -> the database / schema / table entities OpenMetadata wants.

    Pure: takes parsed JSON, returns entity dictionaries, touches no network and
    no filesystem. That is what makes it testable without a server, and it is
    why the HTTP half lives in `pf.tools.openmetadata` instead.

    `column_roles` maps a column name to its ontology role and
    `column_tag_labels` maps a role to the tag labels for it. Together they put
    `PlatformRole.pii_email` on the column, which is the join the catalogue
    exists for: "where is personal data" gets answered from the ontology rather
    than from a naming convention.

    A table with no columns is returned anyway, with an empty list. The API
    rejects it, and the caller decides whether that is a skip or a failure — a
    model that has been parsed but never built genuinely has no columns, and
    inventing one to satisfy a schema would put a fiction in the catalogue.
    """
    roles = column_roles or {}
    labels = column_tag_labels or {}
    nodes = {**(manifest.get("nodes") or {}), **(manifest.get("sources") or {})}
    cat_nodes = {**(catalog.get("nodes") or {}), **(catalog.get("sources") or {})}

    database = ""
    schemas: set[str] = set()
    tables: list[dict[str, Any]] = []

    for key, node in sorted(nodes.items()):
        table_type = TABLE_TYPES.get(str(node.get("resource_type")))
        name = str(node.get("name") or "")
        if not table_type or not name:
            continue
        database = database or str(node.get("database") or fallback_database)
        schema = str(node.get("schema") or "main")
        schemas.add(schema)

        # catalog.json is authoritative for types and ordering because it is
        # read back from the built warehouse; manifest.json is authoritative for
        # documentation. A model that is parsed but not built appears only in
        # the manifest, so fall back to its documented columns.
        built = (cat_nodes.get(key) or {}).get("columns") or {}
        documented = node.get("columns") or {}
        columns = []
        for i, cname in enumerate(built or documented):
            dtype, display, length = column_type(
                str((built.get(cname) or {}).get("type") or ""))
            col: dict[str, Any] = {
                "name": cname,
                "dataType": dtype,
                "dataTypeDisplay": display,
                "ordinalPosition": i + 1,
            }
            if length is not None:
                col["dataLength"] = length
            described = (documented.get(cname) or {}).get("description")
            if described:
                col["description"] = described
            tag_labels = labels.get(roles.get(cname, ""))
            if tag_labels:
                col["tags"] = tag_labels
            columns.append(col)

        tables.append({
            "name": name,
            "databaseSchema": f"{service}.{database}.{schema}",
            "tableType": table_type,
            "description": node.get("description") or "",
            "columns": columns,
        })

    return {
        "service": service,
        "database": database or fallback_database,
        "schemas": sorted(schemas),
        "tables": tables,
    }
