"""Project the ontology into OWL / RDF-XML.

Microsoft's Ontology-Playground imports and exports RDF/XML and checks fidelity
with round-trip tests, so RDF/XML is the interchange format if this vocabulary is
ever to be edited, visualised or reviewed outside this repo.

The mapping is the standard one:

    ontology class          -> owl:Class (rdfs:subClassOf for the parent)
    datatype property       -> owl:DatatypeProperty (rdfs:domain, rdfs:range xsd:*)
    topology relation       -> owl:ObjectProperty (rdfs:domain, rdfs:range)
    inverse name            -> owl:inverseOf, as its own named property
    cardinality             -> owl:FunctionalProperty / owl:InverseFunctionalProperty

Cardinality is where a naive export loses information, so it is spelled out:
MANY_TO_ONE means the property is functional (one value per subject);
ONE_TO_MANY means its inverse is functional. MANY_TO_MANY asserts neither, and
ONE_TO_ONE asserts both.
"""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from pf.ontology.model import Ontology, load_ontology

HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
         xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
         xmlns:owl="http://www.w3.org/2002/07/owl#"
         xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
         xmlns:{prefix}="{ns}"
         xml:base="{base}">

  <owl:Ontology rdf:about="{base}">
    <rdfs:label>Data platform ontology</rdfs:label>
    <rdfs:comment>Generated by `pf ontology export`. The knowledge graph is the
    source of truth; this file is a projection of it.</rdfs:comment>
    <owl:versionInfo>{version}</owl:versionInfo>
  </owl:Ontology>
"""

FOOTER = "</rdf:RDF>\n"


def _uri(ns: str, name: str) -> str:
    return f"{ns}{name}"


def to_rdf_xml(onto: Ontology | None = None) -> str:
    o = onto or load_ontology()
    ns = o.namespace or "https://data-platform.local/ontology#"
    base = ns.rstrip("#")
    out = [HEADER.format(prefix=o.prefix, ns=ns, base=base, version=o.version)]

    # -- classes -----------------------------------------------------------
    out.append("\n  <!-- Classes -->\n")
    for name, cls in o.classes.items():
        out.append(f'  <owl:Class rdf:about="{_uri(ns, name)}">\n')
        out.append(f"    <rdfs:label>{escape(cls.label or name)}</rdfs:label>\n")
        if cls.description:
            out.append(f"    <rdfs:comment>{escape(cls.description.strip())}</rdfs:comment>\n")
        if cls.parent:
            out.append(f'    <rdfs:subClassOf rdf:resource="{_uri(ns, cls.parent)}"/>\n')
        identity = o.identity_of(name)
        if identity:
            # Not standard OWL, but round-trips as an annotation and is the one
            # fact a consumer needs to build a join.
            out.append(f'    <{o.prefix}:identity>{escape(identity)}</{o.prefix}:identity>\n')
        if cls.abstract:
            out.append(f'    <{o.prefix}:abstract>true</{o.prefix}:abstract>\n')
        out.append("  </owl:Class>\n\n")

    # -- datatype properties -----------------------------------------------
    out.append("  <!-- Datatype properties -->\n")
    emitted: set[str] = set()
    for name, cls in o.classes.items():
        for pname, prop in cls.properties.items():
            pid = f"{name}_{pname}"
            if pid in emitted:
                continue
            emitted.add(pid)
            out.append(f'  <owl:DatatypeProperty rdf:about="{_uri(ns, pid)}">\n')
            out.append(f"    <rdfs:label>{escape(pname)}</rdfs:label>\n")
            out.append(f'    <rdfs:domain rdf:resource="{_uri(ns, name)}"/>\n')
            out.append(f'    <rdfs:range rdf:resource="http://www.w3.org/2001/XMLSchema#'
                       f'{prop.xsd_type.split(":")[1]}"/>\n')
            if prop.role:
                out.append(f'    <{o.prefix}:role>{escape(prop.role)}</{o.prefix}:role>\n')
            if prop.required:
                out.append(f'    <{o.prefix}:required>true</{o.prefix}:required>\n')
            out.append("  </owl:DatatypeProperty>\n\n")

    # -- object properties --------------------------------------------------
    out.append("  <!-- Object properties (topology relations) -->\n")
    for rel in o.relations:
        out.append(f'  <owl:ObjectProperty rdf:about="{_uri(ns, rel.name)}">\n')
        out.append(f"    <rdfs:label>{escape(rel.label or rel.name)}</rdfs:label>\n")
        if rel.description:
            out.append(f"    <rdfs:comment>{escape(rel.description.strip())}</rdfs:comment>\n")
        out.append(f'    <rdfs:domain rdf:resource="{_uri(ns, rel.domain)}"/>\n')
        out.append(f'    <rdfs:range rdf:resource="{_uri(ns, rel.range)}"/>\n')
        out.append(f'    <{o.prefix}:cardinality>{rel.cardinality}</{o.prefix}:cardinality>\n')
        if rel.cardinality in ("MANY_TO_ONE", "ONE_TO_ONE"):
            out.append('    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#'
                       'FunctionalProperty"/>\n')
        if rel.cardinality in ("ONE_TO_MANY", "ONE_TO_ONE"):
            out.append('    <rdf:type rdf:resource="http://www.w3.org/2002/07/owl#'
                       'InverseFunctionalProperty"/>\n')
        if rel.inverse:
            out.append(f'    <owl:inverseOf rdf:resource="{_uri(ns, _inverse_id(rel.name))}"/>\n')
        out.append("  </owl:ObjectProperty>\n\n")

        if rel.inverse:
            inv = _inverse_id(rel.name)
            out.append(f'  <owl:ObjectProperty rdf:about="{_uri(ns, inv)}">\n')
            out.append(f"    <rdfs:label>{escape(rel.inverse)}</rdfs:label>\n")
            out.append(f'    <rdfs:domain rdf:resource="{_uri(ns, rel.range)}"/>\n')
            out.append(f'    <rdfs:range rdf:resource="{_uri(ns, rel.domain)}"/>\n')
            out.append(f'    <{o.prefix}:cardinality>{rel.inverse_cardinality}'
                       f'</{o.prefix}:cardinality>\n')
            out.append(f'    <owl:inverseOf rdf:resource="{_uri(ns, rel.name)}"/>\n')
            out.append("  </owl:ObjectProperty>\n\n")

    out.append(FOOTER)
    return "".join(out)


def _inverse_id(name: str) -> str:
    return f"{name}_inverse"


def export(out: str | Path, onto: Ontology | None = None) -> Path:
    path = Path(out)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(to_rdf_xml(onto), encoding="utf-8")
    return path


def stats(onto: Ontology | None = None) -> dict[str, int]:
    o = onto or load_ontology()
    datatype_props = sum(len(c.properties) for c in o.classes.values())
    inverses = sum(1 for r in o.relations if r.inverse)
    return {
        "classes": len(o.classes),
        "datatype_properties": datatype_props,
        "object_properties": len(o.relations) + inverses,
    }
