{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `stripe.subscriptions` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: Subscription · Grain: one subscription
#}

with renamed as (
    select
        {{ pf_clean('id', 'natural_key') }} as subscription_id,
        {{ pf_clean('plan', 'status_enum') }} as plan_tier,
        {{ pf_clean('status', 'status_enum') }} as subscription_status,
        {{ pf_clean('mrr_amount', 'money_amount') }} as mrr_amount,
        {{ pf_clean('currency', 'currency_code') }} as currency_code,
        {{ pf_clean('started_at', 'event_time') }} as started_at,
        {{ pf_clean('canceled_at', 'valid_to') }} as canceled_at,
        {{ pf_clean('customer_id', 'foreign_key') }} as customer_id,  -- → Customer
        _dlt_load_id
    from {{ source('stripe', 'subscriptions') }}
)

select * exclude (_dlt_load_id)
from renamed
where subscription_id is not null
{{ pf_dedupe('subscription_id') }}
