{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `stripe.customers` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: Customer · Grain: one customer account
#}

with renamed as (
    select
        {{ pf_clean('id', 'natural_key') }} as customer_id,
        {{ pf_clean('email', 'pii_email') }} as customer_email,
        {{ pf_clean('name', 'pii_name') }} as customer_name,
        {{ pf_clean('country', 'geo_country') }} as country_code,
        {{ pf_clean('segment', 'status_enum') }} as customer_segment,
        {{ pf_clean('created', 'event_time') }} as created_at,
        {{ pf_clean('organization_id', 'foreign_key') }} as organization_id,  -- → Organization
        _dlt_load_id
    from {{ source('stripe', 'customers') }}
)

select * exclude (_dlt_load_id)
from renamed
where customer_id is not null
{{ pf_dedupe('customer_id') }}
