-- metric: gross_payment_volume (simple) — generated by `pf report build`
-- All payment attempts regardless of outcome.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
select
    paid_at as metric_time,
    payment_status,
    customer_segment,
    plan_tier,
    sum(amount) as gross_payment_volume
from main_marts.fct_payments
group by 1, 2, 3, 4
order by 1
