-- metric: payment_count (simple) — generated by `pf report build`
-- Count of succeeded payments.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
select
    paid_at as metric_time,
    payment_status,
    customer_segment,
    plan_tier,
    count(payment_id) as payment_count
from main_marts.fct_payments
where payment_status = 'succeeded'
group by 1, 2, 3, 4
order by 1
