-- metric: revenue (simple) — generated by `pf report build`
-- Net revenue — succeeded payments only. The single definition.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
select
    paid_at as metric_time,
    payment_status,
    customer_segment,
    plan_tier,
    sum(amount) as revenue
from main_marts.fct_payments
where payment_status = 'succeeded'
group by 1, 2, 3, 4
order by 1
