"""Toolkit registration, checked rather than remembered.

A toolkit is three things that have to agree: a directory under
`platform/toolkits/`, an entry in `.claude-plugin/marketplace.json`, and a
section in `TOOLKITS.md`. Nothing at runtime forces the three to match, and the
failure is silent in the worst direction — a skill that exists on disk but is
unregistered is simply never offered, so the agent does the work the skill exists
to prevent and no error is ever raised.

TOOLKITS.md carries a "GENERATED by `pf context build`" header, but no such
command exists today, so in practice it is hand-maintained and drifts. That is
exactly the condition these checks are for.

WHY TWO OF THESE ARE RATCHETS. Four toolkits were already unregistered when this
file was written. Asserting the invariant outright would have meant either a red
suite or writing catalogue entries for toolkits whose rules the author had not
read — so the known gaps are named in `UNREGISTERED` / `UNCATALOGUED` and the
test fails the moment the set *grows*. The lists are debt, not policy: deleting a
name from one as it gets registered is the intended direction of travel.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[2]
TOOLKITS = ROOT / "platform" / "toolkits"
MARKETPLACE = ROOT / "platform" / ".claude-plugin" / "marketplace.json"

#: Toolkits that exist on disk but are not yet in marketplace.json. Shrink me.
UNREGISTERED = {"forge-ui", "recce-review"}

#: Toolkits with no section in TOOLKITS.md. Shrink me.
#: (project-onboarding left this list when its section landed — the ratchet
#: now defends that section instead of tolerating its absence.)
UNCATALOGUED = {"dbt-snowflake", "forge-ui", "recce-review"}


def toolkits() -> list[Path]:
    return sorted(p for p in TOOLKITS.iterdir() if p.is_dir())


def skills(toolkit: Path) -> list[Path]:
    d = toolkit / "skills"
    return sorted(d.glob("*/SKILL.md")) if d.exists() else []


def registered() -> dict[str, str]:
    doc = json.loads(MARKETPLACE.read_text())
    return {p["name"]: p["source"] for p in doc["plugins"]}


def catalogue() -> str:
    return (TOOLKITS / "TOOLKITS.md").read_text()


# ------------------------------------------------------------------ plugin ----
@pytest.mark.parametrize("tk", toolkits(), ids=lambda p: p.name)
def test_toolkit_is_a_plugin(tk: Path):
    """Without a manifest the directory is not a toolkit, it is a folder."""
    manifest = tk / ".claude-plugin" / "plugin.json"
    assert manifest.exists(), f"{tk.name} has no plugin.json"
    assert json.loads(manifest.read_text())["name"] == tk.name


@pytest.mark.parametrize("tk", toolkits(), ids=lambda p: p.name)
def test_skill_frontmatter_is_addressable(tk: Path):
    """Skills are invoked by name, so the name in the frontmatter has to be the
    one the directory advertises, and a missing description makes a skill
    un-routable — TOOLKITS.md is built from these two fields."""
    for sk in skills(tk):
        fm = re.match(r"^---\n(.*?)\n---\n", sk.read_text(), re.S)
        assert fm, f"{sk} has no frontmatter"
        doc = yaml.safe_load(fm.group(1)) or {}
        assert doc.get("name") == sk.parent.name, f"{sk}: name != directory"
        assert (doc.get("description") or "").strip(), f"{sk}: empty description"


# ------------------------------------------------------------ registration ----
def test_marketplace_points_at_real_toolkits():
    names = {p.name for p in toolkits()}
    dangling = {n for n in registered() if n not in names}
    assert not dangling, f"marketplace.json references missing toolkits: {dangling}"


def test_marketplace_sources_resolve():
    # A marketplace source is relative to the marketplace root — the directory
    # holding `.claude-plugin/`, i.e. platform/ — not to `.claude-plugin/` itself.
    root = MARKETPLACE.parent.parent
    for name, source in registered().items():
        assert source == f"./toolkits/{name}", f"{name}: odd source {source}"
        assert (root / source).is_dir(), f"{name}: {source} does not exist"


def test_no_new_unregistered_toolkit():
    missing = {p.name for p in toolkits()} - set(registered())
    assert missing <= UNREGISTERED, (
        f"new toolkit(s) not in marketplace.json: {sorted(missing - UNREGISTERED)}")


def test_no_new_uncatalogued_toolkit():
    listed = set(re.findall(r"^## ([\w-]+) ", catalogue(), re.M))
    missing = {p.name for p in toolkits()} - listed
    assert missing <= UNCATALOGUED, (
        f"new toolkit(s) absent from TOOLKITS.md: {sorted(missing - UNCATALOGUED)}")


def test_catalogued_toolkits_list_their_skills():
    """A section that names the toolkit but not its skills routes to nothing."""
    listed = set(re.findall(r"`([\w-]+)`", catalogue()))
    for tk in toolkits():
        if tk.name in UNCATALOGUED:
            continue
        for sk in skills(tk):
            assert sk.parent.name in listed, f"{tk.name}/{sk.parent.name} not in TOOLKITS.md"


# ------------------------------------------------------------ viz-standards ----
def test_viz_standards_is_wired_end_to_end():
    """The toolkit this suite shipped with — every hop, so a later refactor that
    drops one of the three registrations fails here rather than in silence."""
    tk = TOOLKITS / "viz-standards"
    assert (tk / "skills" / "charts-and-diagrams" / "SKILL.md").exists()
    assert "viz-standards" in registered()
    assert "## viz-standards" in catalogue()
    assert "viz-standards" in (TOOLKITS / "ROUTING.md").read_text()
