{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `reference.commodities` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: Commodity · Grain: one tracked commodity
#}

with renamed as (
    select
        {{ pf_clean('commodity_id', 'natural_key') }} as commodity_id,
        {{ pf_clean('commodity_name', 'free_text') }} as commodity_name,
        {{ pf_clean('category', 'status_enum') }} as category,
        {{ pf_clean('segment', 'status_enum') }} as segment,
        {{ pf_clean('exchange', 'status_enum') }} as exchange,
        {{ pf_clean('quote_unit', 'unit_of_measure') }} as quote_unit,
        {{ pf_clean('price_basis', 'status_enum') }} as price_basis,
        {{ pf_clean('yahoo_symbol', 'free_text') }} as yahoo_symbol,
        {{ pf_clean('spot_symbol', 'free_text') }} as spot_symbol,
        _dlt_load_id
    from {{ source('reference', 'commodities') }}
)

select * exclude (_dlt_load_id)
from renamed
where commodity_id is not null
{{ pf_dedupe('commodity_id') }}
