#!/usr/bin/env python3
"""One hook entry point for every agent harness.

    agent_hook.py <harness> <event>

    harness   claude | codex | gemini | copilot | cursor | opencode
    event     pre | post | session | stop | prompt

stdin is the harness's own hook payload; stdout, stderr and the exit code are
in that harness's own dialect. Everything between — the gate, permissions,
provenance, the formatter, the turn-one context, the session capture — is
`pf.agenthook`, the same code for every harness. The per-harness configs that
call this are generated by `pf context refresh` (`pf.harness`); the dialects
are in `pf.harness_adapters`.

Never fails closed on its own bug: anything unexpected exits 0 with nothing
printed, because a hook that crashes closed blocks every tool call in the
editor, and a hook that gets removed for that enforces nothing.
"""

from __future__ import annotations

import sys
from pathlib import Path


def _root() -> Path:
    here = Path(__file__).resolve().parent
    for p in [here, *here.parents]:
        if (p / "platform").is_dir() and (p / "groups").is_dir():
            return p
    return here.parent.parent


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        return 0
    raw = sys.stdin.read()
    sys.path.insert(0, str(_root() / "platform" / "src"))
    try:
        from pf.harness_adapters import run
    except Exception:  # noqa: BLE001 — platform not importable: do not block
        return 0
    try:
        out, err, code = run(argv[1], argv[2], raw)
    except Exception:  # noqa: BLE001
        return 0
    if out:
        sys.stdout.write(out if out.endswith("\n") else out + "\n")
    if err:
        sys.stderr.write(err if err.endswith("\n") else err + "\n")
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv))
