#!/usr/bin/env bash
# Commit what `pf context refresh --paths-to` reported, the way the gate accepts it.
#
#   commit_refreshed.sh <paths-file> <max-files-per-commit> <subject>
#
# Used by CI wherever generated context is healed — a pull request's branch and
# `main` after a merge — so both commit the same way:
#
#   * only the listed paths, deletions included (`git add -A -- <path>`), never
#     whatever else the runner's checkout happens to hold;
#   * at most `maxFiles` paths per commit, so every commit passes the same
#     per-commit cap a person's does, with no `Gate-Exempt` needed;
#   * harness maps first: the gate denies a commit to a scope while that
#     scope's regenerated HARNESS.md sits unstaged beside it.
#
# Prints the number of commits made. Makes none for an empty or missing list.
set -euo pipefail

list="$1"
cap="$2"
subject="$3"

if [ ! -s "$list" ]; then
  echo 0
  exit 0
fi

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
{
  grep -E '(^|/)HARNESS\.md$' "$list" || true
  grep -vE '(^|/)HARNESS\.md$' "$list" || true
} | split -l "$cap" - "$work/slice."

n=0
for slice in "$work"/slice.*; do
  n=$((n + 1))
  xargs git add -A -- < "$slice"
  git commit -q -m "$subject ($n)" -m "Regenerated by \`pf context refresh\`: generated files only, no hand edits."
done
echo "$n"
