#!/usr/bin/env python3
"""Cursor hook adapter — kept for configs and callers that still name it.

Cursor's hooks now run `agent_hook.py cursor <event>` (see `.cursor/hooks.json`,
generated by `pf context refresh`), which is the same core every harness uses.
This file forwards to it: `shell` and `edit`, the two events the first Cursor
config wired, map onto `pre` and `post`.

`bypasses_hooks` is re-exported from the core, where the flag-position-aware
`--no-verify` matcher now lives for every harness.
"""

from __future__ import annotations

import runpy
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from pf.agenthook import bypasses_hooks  # noqa: E402,F401 — the public name

if __name__ == "__main__":
    event = {"shell": "pre", "edit": "post"}.get(sys.argv[1] if len(sys.argv) > 1 else "", "")
    sys.argv = [str(Path(__file__).with_name("agent_hook.py")), "cursor", event]
    runpy.run_path(sys.argv[0], run_name="__main__")
