-- source extract for fct_mcx_commodity_rollup_daily (PII columns excluded by the MDL projection)
-- Columns are enumerated, never `select *`: the extract's shape is a
-- contract with the pages reading it, and a star changes shape silently.
select
    commodity_day_id,
    mcx_commodity,
    commodity_id,
    trade_date,
    flagship_close_price,
    var_garman_klass,
    turnover_inr,
    open_interest_value_inr,
    volume_flagship_lots,
    segment,
    is_latest,
    flagship_contract_code,
    is_liquid,
    return_1d,
    log_return_1d,
    sq_log_return_1d,
    var_parkinson,
    var_rogers_satchell,
    is_up_session,
    rsi_14,
    garman_klass_vol_30d,
    roll_yield_annualised,
    is_contango_session,
    is_backwardation_session,
    trend_regime,
    volatility_regime,
    stance,
    premium_to_landed_pct,
    codes_trading,
    mini_turnover_inr,
    put_oi_notional_inr,
    call_oi_notional_inr,
    option_premium_turnover_inr,
    option_notional_turnover_inr
from main_marts.fct_mcx_commodity_rollup_daily
