-- source extract for fct_mcx_futures_daily (PII columns excluded by the MDL projection)
-- Columns are enumerated, never `select *`: the extract's shape is a
-- contract with the pages reading it, and a star changes shape silently.
select
    session_id,
    contract_id,
    contract_code,
    mcx_commodity,
    commodity_id,
    trade_date,
    expiry_date,
    open_price,
    high_price,
    low_price,
    close_price,
    volume_lots,
    open_interest_lots,
    turnover_inr,
    oi_buildup,
    contract_name,
    segment,
    is_flagship,
    days_to_expiry,
    expiry_rank,
    expiry_bucket,
    quote_size,
    quote_unit,
    lot_size,
    lot_unit,
    quote_units_per_lot,
    is_traded,
    previous_close_price,
    price_change,
    price_change_pct,
    open_interest_change_lots,
    notional_per_lot_inr,
    open_interest_value_inr,
    implied_quote_units_per_lot,
    is_spec_verified,
    volume_to_oi_ratio
from main_marts.fct_mcx_futures_daily
