{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `kaggle_mh.ecg_recordings` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: EcgRecording · Grain: one 12-lead ECG segment
#}

with renamed as (
    select
        {{ pf_clean('recording_id', 'natural_key') }} as recording_id,
        {{ pf_clean('diagnosis_code', 'foreign_key') }} as diagnosis_code,
        {{ pf_clean('disorder_group', 'status_enum') }} as disorder_group,
        {{ pf_clean('n_samples', 'quantity') }} as n_samples,
        {{ pf_clean('n_leads', 'quantity') }} as n_leads,
        {{ pf_clean('signal_mean', 'quantity') }} as signal_mean,
        {{ pf_clean('signal_std', 'quantity') }} as signal_std,
        {{ pf_clean('signal_min', 'quantity') }} as signal_min,
        {{ pf_clean('signal_max', 'quantity') }} as signal_max,
        {{ pf_clean('signal_rms', 'quantity') }} as signal_rms,
        {{ pf_clean('lead2_mean', 'quantity') }} as lead2_mean,
        {{ pf_clean('lead2_std', 'quantity') }} as lead2_std,
        _dlt_load_id
    from {{ source('kaggle_mh', 'ecg_recordings') }}
)

select * exclude (_dlt_load_id)
from renamed
where recording_id is not null
{{ pf_dedupe('recording_id') }}
