{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `kaggle_mh.treatment_episodes` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: TreatmentEpisode · Grain: one treatment episode per patient
#}

with renamed as (
    select
        {{ pf_clean('episode_id', 'natural_key') }} as episode_id,
        {{ pf_clean('patient_id', 'foreign_key') }} as patient_id,
        {{ pf_clean('diagnosis_code', 'foreign_key') }} as diagnosis_code,
        {{ pf_clean('age', 'quantity') }} as age,
        {{ pf_clean('gender', 'status_enum') }} as gender,
        {{ pf_clean('diagnosis', 'status_enum') }} as diagnosis,
        {{ pf_clean('symptom_severity', 'quantity') }} as symptom_severity,
        {{ pf_clean('mood_score', 'quantity') }} as mood_score,
        {{ pf_clean('sleep_quality', 'quantity') }} as sleep_quality,
        {{ pf_clean('physical_activity_hrs_week', 'quantity') }} as physical_activity_hrs_week,
        {{ pf_clean('medication', 'status_enum') }} as medication,
        {{ pf_clean('therapy_type', 'status_enum') }} as therapy_type,
        {{ pf_clean('treatment_started_at', 'event_time') }} as treatment_started_at,
        {{ pf_clean('treatment_duration_weeks', 'quantity') }} as treatment_duration_weeks,
        {{ pf_clean('stress_level', 'quantity') }} as stress_level,
        {{ pf_clean('outcome', 'status_enum') }} as outcome,
        {{ pf_clean('treatment_progress', 'quantity') }} as treatment_progress,
        {{ pf_clean('emotional_state', 'status_enum') }} as emotional_state,
        {{ pf_clean('adherence_pct', 'quantity') }} as adherence_pct,
        _dlt_load_id
    from {{ source('kaggle_mh', 'treatment_episodes') }}
)

select * exclude (_dlt_load_id)
from renamed
where episode_id is not null
{{ pf_dedupe('episode_id') }}
