{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `kaggle_mh.registry_annual` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: PopulationStatistic · Grain: one statistic x year x sex x ICD-10 diagnostic group
#}

with renamed as (
    select
        {{ pf_clean('statistic_id', 'natural_key') }} as statistic_id,
        {{ pf_clean('statistic_code', 'status_enum') }} as statistic_code,
        {{ pf_clean('statistic_label', 'free_text') }} as statistic_label,
        {{ pf_clean('year', 'quantity') }} as year,
        {{ pf_clean('year_date', 'event_time') }} as year_date,
        {{ pf_clean('sex', 'status_enum') }} as sex,
        {{ pf_clean('icd10_group_code', 'status_enum') }} as icd10_group_code,
        {{ pf_clean('icd10_group', 'status_enum') }} as icd10_group,
        {{ pf_clean('unit', 'status_enum') }} as unit,
        {{ pf_clean('value', 'quantity') }} as value,
        _dlt_load_id
    from {{ source('kaggle_mh', 'registry_annual') }}
)

select * exclude (_dlt_load_id)
from renamed
where statistic_id is not null
{{ pf_dedupe('statistic_id') }}
