// GENERATED by `pf context refresh` from platform/src/pf/harnesses/opencode.py — do not hand-edit.
// Every decision is platform/hooks/agent_hook.py; this file only carries
// OpenCode's events to it and its answers back.
import { spawnSync } from "node:child_process";

export const PfGate = async ({ directory, worktree }) => {
  const root = worktree || directory;
  const hook = (event, payload) =>
    spawnSync(
      "uv",
      ["run", "--quiet", "--project", root, "python", `${root}/platform/hooks/agent_hook.py`,
       "opencode", event],
      {
        input: JSON.stringify({ cwd: directory, ...payload }),
        encoding: "utf8",
        env: { ...process.env, PF_AGENT: process.env.PF_AGENT || "opencode" },
      },
    );
  const context = new Map();
  return {
    "tool.execute.before": async (input, output) => {
      const r = hook("pre", { tool: input.tool, args: output.args, sessionID: input.sessionID, callID: input.callID });
      if (r.status === 2) throw new Error((r.stderr || "refused by gate.yaml").trim());
    },
    "tool.execute.after": async (input, output) => {
      const r = hook("post", {
        tool: input.tool, args: input.args, sessionID: input.sessionID, callID: input.callID, output: output?.output,
      });
      const advice = (r.stdout || "").trim();
      if (advice && output && typeof output.output === "string") output.output += `\n\n${advice}`;
    },
    "experimental.chat.system.transform": async (input, output) => {
      const sid = input?.sessionID || "";
      if (!context.has(sid)) context.set(sid, (hook("session", { sessionID: sid }).stdout || "").trim());
      if (context.get(sid)) output.system.push(context.get(sid));
    },
    event: async ({ event }) => {
      if (event?.type === "session.idle") hook("stop", { sessionID: event.properties?.sessionID || "" });
    },
  };
};
