{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `stripe.charges` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: Payment · Grain: one payment attempt
#}

with renamed as (
    select
        {{ pf_clean('id', 'natural_key') }} as payment_id,
        {{ pf_clean('amount', 'money_amount') }} as amount,
        {{ pf_clean('currency', 'currency_code') }} as currency_code,
        {{ pf_clean('status', 'status_enum') }} as payment_status,
        {{ pf_clean('created', 'event_time') }} as paid_at,
        {{ pf_clean('receipt_email', 'pii_email') }} as receipt_email,
        {{ pf_clean('customer_id', 'foreign_key') }} as customer_id,  -- → Customer
        {{ pf_clean('subscription_id', 'foreign_key') }} as subscription_id,  -- → Subscription
        _dlt_load_id
    from {{ source('stripe', 'charges') }}
)

select * exclude (_dlt_load_id)
from renamed
where payment_id is not null
{{ pf_dedupe('payment_id') }}
