"""Design one project's architecture map, from the project itself.

Every project in this repository has the same shape and different contents: a
dlt ingest, a dbt transform, a semantic layer, a governance overlay, a delivery
surface and an operational wiring. An agent arriving at one of them currently
learns that shape by reading it — twenty-odd directories, a dbt project, a
settings file — which costs thousands of tokens to rediscover something the
platform already knows.

This module writes it down instead, per project, as `kg/architecture.md`. It is
a **projection**, never hand-maintained: `pf bootstrap` regenerates it, so a new
project gets one at scaffold time and an existing one gets it on the next
bootstrap, with no per-project work either way.

## Why a feature registry rather than a template

The obvious implementation is a template with the sections someone thought of on
the day. That is exactly how a project feature goes missing: `catalog/` and
`evals/` were both added to the scaffolder long after the first documentation of
it was written, and neither appeared in any overview until somebody noticed.

So the shape of the document is a **registry** and the document is generated
from it. Two consequences make the omission failure structural rather than a
matter of diligence:

  every feature is reported     including the absent ones, which are the ones a
                                  template silently omits and the ones a reader
                                  most needs to see
  everything else is flagged    `unmapped` lists any top-level entry in the
                                  project that no feature claims, so a directory
                                  added by a future capability shows up as a hole
                                  in the map rather than not showing up at all

`pf arch --check` fails on both a stale document and a non-empty `unmapped`, so
the second one is a build error rather than a note nobody reads.

## Why the registry is composed, not listed

`CORE` below is what the *platform* puts in every project. It is not the whole
registry, and `features()` is: it adds whatever the installed capabilities and
tools declare or imply, resolved at call time.

That indirection is the difference between a map that survives a new tool and
one that breaks on it. A tool arrives by installing a package that advertises a
`pf.tools` entry point, and nothing here is supposed to change when one does —
so a tool writing `elementary/` into a project must claim that directory itself.
With a closed list it could not: every project would report an unmapped
directory and fail `pf arch --check`, fixable only by patching platform code.

Contribution costs nothing in the common case. `pf.features.derive` reads what a
capability or tool *already declares* — its `files`, its `dbt.artefacts` — and
adds a row only for territory nothing else claims. `Capability.feature` and
`Tool.features` are there when a derivation would produce a poor title or miss a
`count_kind`.

## Scope

**One project. Never a sister.** Nothing here reads outside the project
directory except the repository-level artefacts that are *about* this project —
its CI workflow and its Dagster code location — and, for a roll-up, the sister
*names* the group already publishes in its group card. Business logic does not
transfer between entities, and neither does an architecture read from the wrong
one.

## Why there is no date in the output

The context card carries a generation date and is rewritten every day because of
it. This document is regenerated by every `pf bootstrap --all`, on eight
projects, and a date would make each of those runs an eight-file diff that says
nothing. Without one, the file changes when the project changes — which is what
makes `pf arch --check` worth wiring into CI.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from pf import viz
from pf.features import LANES, Feature, derive

__all__ = ["ARCHITECTURE_BUDGET", "CORE", "LANES", "Arch", "Feature", "drift",
           "features", "render", "summary", "write"]

#: On-demand tier, not always-on: this is read when an agent needs the map, not
#: loaded into every session. The ceiling is still low enough that reading it is
#: cheaper than the exploration it replaces — around 8,000 tokens of `ls`, `cat`
#: and dbt-project reading, measured while writing `pf new-project --plan`.
ARCHITECTURE_BUDGET = 4000

DOC_REL = Path("kg") / "architecture.md"

HEADER = ("<!-- GENERATED by `pf arch <group> <project>`, and by every "
          "`pf bootstrap`. Never hand-edit: the next bootstrap overwrites it, "
          "and `pf arch --check` fails on the drift in the meantime. -->")

#: Build output, caches and editor droppings. Not features, and not holes in the
#: map either — they are excluded from `unmapped` rather than claimed by a
#: feature, so nothing pretends they are part of the architecture.
#:
#: Deliberately short, and it is not the place to silence a directory a tool
#: writes: that belongs in the tool's own `features`, where it is documented and
#: counted rather than hidden.
IGNORED = {
    "__pycache__", ".DS_Store", ".git", ".gitignore", ".venv", "node_modules",
    "target", "target-base", "dbt_packages", "logs", ".ruff_cache",
    ".pytest_cache", "uv.lock", ".python-version", "reviews",
}


#: What the platform itself puts in every project. Not the whole registry —
#: `features()` is, and it adds what the installed capabilities and tools bring.
CORE: tuple[Feature, ...] = (
    # ------------------------------------------------------------- ingest --
    # `[!_]` skips `__init__.py`. Counting the package marker as a source made
    # every project look like it had one, including the two that have none.
    Feature("sources", "dlt sources", "ingest",
            "the only place raw data enters; each declares its ontology concept",
            ("src/*/sources/[!_]*.py",), made_by="/create-sql-pipeline"),
    Feature("dlt_config", "dlt config", "ingest",
            "pipeline settings and destination; secrets live beside it, ungitted",
            (".dlt/config.toml",), made_by="pf new-project"),
    Feature("annotations", "ontology annotations", "ingest",
            "concept and column roles — drives staging, PII policy and monitors",
            ("contracts/annotations.yaml",), made_by="pf semantic annotate"),
    Feature("raw_tables", "raw tables", "ingest",
            "what the pipeline actually landed",
            ("data/*.duckdb",), count_kind="Table", made_by="pf seed"),
    # ---------------------------------------------------------- transform --
    Feature("dbt_project", "dbt project", "transform",
            "the transform runtime; macro-paths reach the platform's macros",
            ("transform/dbt_project.yml",), made_by="pf new-project"),
    Feature("profiles", "dbt targets", "transform",
            "dev, base and prod; base is what Recce diffs against",
            ("transform/profiles.yml",), made_by="pf bootstrap"),
    Feature("staging", "staging models", "transform",
            "one per raw table, generated from the annotations",
            ("transform/models/staging/**/*.sql",), made_by="pf gen-staging"),
    Feature("marts", "marts", "transform",
            "business entities at a declared grain — what metrics are built on",
            ("transform/models/marts/**/*.sql",), made_by="/using-dbt"),
    Feature("dbt_tests", "data tests", "transform",
            "the assumptions the models are allowed to make",
            ("transform/models/**/*.yml", "transform/tests/**/*.sql"),
            count_kind="Test", made_by="/add-tests"),
    Feature("macros", "project macros", "transform",
            "project-local SQL; dialect macros come from the platform toolkits",
            ("transform/macros/**/*.sql",), optional=True, made_by="/using-dbt"),
    Feature("snapshots", "snapshots", "transform",
            "slowly-changing dimensions captured over time",
            ("transform/snapshots/**/*.sql",), optional=True, made_by="/using-dbt"),
    Feature("packages", "dbt packages", "transform",
            "the group's shared dbt package, plus any upstream ones",
            ("transform/packages.yml",), made_by="pf new-project"),
    # ---------------------------------------------------------- semantics --
    Feature("metrics", "metrics", "semantics",
            "the governed answer to a business question; never ad-hoc SQL",
            ("transform/models/semantic/**/*.yml",),
            count_kind="Metric", made_by="/build-semantic-layer"),
    Feature("dimensions", "dimensions", "semantics",
            "how a metric may be sliced; conformed ones come from the group",
            ("transform/models/semantic/**/*.yml",),
            count_kind="Dimension", made_by="/build-semantic-layer"),
    Feature("graph", "knowledge graph", "semantics",
            "kg_search, kg_neighbors and impact analysis read this, not the files",
            ("kg/graph.duckdb", "kg/graph.json"), made_by="pf kg build"),
    Feature("card", "context card", "semantics",
            "the always-on index; ~400 tokens, budgeted by `pf tokens`",
            ("kg/context_card.md",), made_by="pf kg card"),
    Feature("architecture", "architecture map", "semantics",
            "this document — the on-demand map, regenerated never hand-edited",
            ("kg/architecture.md",), made_by="pf arch", self_reporting=True),
    Feature("mdl", "MDL manifest", "semantics",
            "the semantic contract an external consumer reads (WrenAI, BI)",
            ("mdl/mdl.json", "mdl/connection.json"), made_by="pf semantic mdl"),
    Feature("catalog", "catalog export", "semantics",
            "OpenMetadata ingestion, for a company that runs one",
            ("catalog/openmetadata.json", "catalog/ingestion/**"),
            optional=True, made_by="pf bootstrap"),
    # --------------------------------------------------------- governance --
    Feature("policy", "project policy", "governance",
            "the third ontology layer; may only tighten platform and group",
            ("governance/policy.yaml",), count_kind="Policy",
            made_by="pf new-project"),
    Feature("otop", "otop manifest", "governance",
            "policy and evidence as an OpenTopology graph, schema-validated",
            ("governance/otop.json",), count_kind="Evidence",
            made_by="pf semantic otop"),
    Feature("claude_md", "project rules", "governance",
            "the rules the graph cannot encode; loaded every session",
            ("CLAUDE.md",), made_by="pf new-project"),
    Feature("settings", "agent permissions", "governance",
            "the deny list and the PreToolUse hook — sisters unreadable by policy",
            (".claude/settings.json",), made_by="pf new-project"),
    Feature("decisions", "decision records", "governance",
            "why this project is shaped the way it is, where code cannot say so",
            ("decisions/*.md",), optional=True, made_by="written by hand"),
    # ----------------------------------------------------------- delivery --
    Feature("exposures", "exposures", "delivery",
            "who reads the output — impact analysis stops at the mart without them",
            ("transform/models/**/*.yml",), count_kind="Exposure",
            made_by="/using-dbt"),
    Feature("reporting", "Evidence BI", "delivery",
            "dashboards as a projection of the metrics, never restating logic",
            ("reporting/pages/**/*.md", "reporting/evidence.config.yaml"),
            optional=True, made_by="pf report build"),
    Feature("docs", "capability docs", "delivery",
            "one page per capability, explaining what it wired in",
            ("docs/*.md",), made_by="pf capability-add"),
    # ------------------------------------------------------------ operate --
    Feature("dagster", "Dagster definitions", "operate",
            "assets come from the runtime factory; the project supplies logic",
            ("src/*/definitions.py",), made_by="pf new-project"),
    Feature("code_location", "Dagster registration", "operate",
            "an unregistered project silently never runs",
            repo_paths=("platform/workspace.yaml",), made_by="pf bootstrap"),
    Feature("ci", "CI workflow", "operate",
            "one workflow per project, composed from its capabilities' jobs",
            repo_paths=(".github/workflows/{project}.yml",), made_by="pf bootstrap"),
    Feature("evals", "eval cases", "operate",
            "does an agent still answer this project's questions correctly",
            ("evals/cases/**/*.yaml", "evals/cases/**/*.yml"),
            made_by="pf evals-gen"),
    Feature("memory", "agent memory", "operate",
            "session notes that survive a compaction",
            (".memory/notes/**",), optional=True, made_by="written by the agent"),
    Feature("duckdb_skills", "duckdb memories", "operate",
            "query patterns the duckdb-ops toolkit reuses",
            (".duckdb-skills/**",), optional=True, made_by="pf bootstrap"),
    # Optional because absence means "inherits the group's", not "missing". The
    # eight projects that predate the scaffolder writing one have no file and
    # are correctly configured; a fresh scaffold has an empty one.
    Feature("tool_overrides", "tool overrides", "operate",
            "opt out of a group tool or retune one; merged over the group's",
            ("tools.yaml",), optional=True, made_by="pf tool enable"),
    Feature("pyproject", "project deps", "operate",
            "the project's own Python dependencies, on top of the platform's",
            ("pyproject.toml",), made_by="pf new-project"),
)


# ------------------------------------------------------------- composition ---
def _installed_capabilities() -> list:
    """Every registered capability, tools' ones included.

    `CAPABILITIES` is a mutable global that tool registration adds to by side
    effect, so what it holds depends on whether discovery has run. The CLI
    triggers it at import and a bare `import pf.architecture` does not, which is
    how the same project produced two different maps depending on who asked.
    """
    try:
        from pf.capabilities import CAPABILITIES
        from pf.tools import register_capabilities

        register_capabilities()
        return sorted(CAPABILITIES.values(), key=lambda c: c.name)
    except Exception:  # noqa: BLE001 — a broken registry must not stop the map
        return []


def _installed_tools() -> list:
    try:
        from pf.tools import all_tools

        return sorted(all_tools().values(), key=lambda t: t.name)
    except Exception:  # noqa: BLE001
        return []


def features() -> tuple[Feature, ...]:
    """The registry: platform features, plus what the installed extras bring.

    Order is reading order — `CORE` as declared, then contributions by name —
    and it is stable for a fixed installation, which is what lets the rendered
    map be byte-compared for drift.

    A key already present wins. That makes `CORE` authoritative over a
    derivation, and an explicitly declared `Capability.feature` authoritative
    over the derivation for the same capability.
    """
    out: dict[str, Feature] = {f.key: f for f in CORE}
    claimed: set[str] = {s for f in CORE for s in f.segments}

    def add(f: Feature | None) -> None:
        if f is None or f.key in out:
            return
        out[f.key] = f
        claimed.update(f.segments)

    for cap in _installed_capabilities():
        add(getattr(cap, "feature", None))
        add(derive(cap.name, cap.description, tuple(cap.files),
                   source=f"capability:{cap.name}",
                   made_by=f"pf capability-add {cap.name}",
                   optional=not cap.default_enabled, claimed=claimed))

    for tool in _installed_tools():
        for f in getattr(tool, "features", ()):
            add(f)
        paths = tuple(getattr(tool.capability, "files", {}) or {})
        paths += tuple(getattr(tool.dbt, "artefacts", ()) or ())
        add(derive(tool.name, tool.summary, paths, source=f"tool:{tool.name}",
                   made_by=f"pf tool enable {tool.name}",
                   optional=not tool.default_enabled, claimed=claimed))

    return tuple(out.values())


@dataclass
class Presence:
    """One feature, as found in one project."""

    feature: Feature
    count: int = 0
    #: Only ever the first matching path, for the reader to open. Not a list:
    #: forty staging models are a count, not thirty-nine lines of noise.
    where: str = ""

    @property
    def present(self) -> bool:
        return self.count > 0

    @property
    def countable(self) -> bool:
        """Is `count` a quantity, or just how many of a fixed file set exist?

        `mdl/` holds exactly two files and always will; printing "2" beside it
        says nothing. `transform/models/marts/**/*.sql` holding 996 is the
        single most useful number on the page. The difference is whether the
        globs name specific files or a set, so that is what is asked.
        """
        f = self.feature
        return bool(f.count_kind) or all("*" in g for g in f.paths + f.repo_paths)

    @property
    def state(self) -> str:
        if self.present:
            return "ok"
        return "optional" if self.feature.optional else "gap"


@dataclass
class Chain:
    """A real path through the project, as (kind, name) upstream to downstream."""

    steps: list[tuple[str, str]] = field(default_factory=list)
    note: str = ""
    #: The walk hit its hop limit with lineage still above it. Said out loud in
    #: the diagram, because a chain that starts at a mart otherwise reads as a
    #: project whose marts have no sources.
    truncated: bool = False


@dataclass
class Arch:
    group: str
    project: str
    pdir: Path
    root: Path
    is_rollup: bool = False
    sisters: list[str] = field(default_factory=list)
    warehouse: str = ""
    module: str = ""
    counts: dict[str, int] = field(default_factory=dict)
    found: list[Presence] = field(default_factory=list)
    unmapped: list[str] = field(default_factory=list)
    tools: list[str] = field(default_factory=list)
    caps: list[str] = field(default_factory=list)
    pii: int = 0
    chain: Chain = field(default_factory=Chain)

    def by_key(self, key: str) -> Presence:
        """A feature by key, or an empty stand-in.

        Never raises. The registry is composed from what is installed, so a
        renderer that names a key cannot assume it exists — and a spine that
        crashes because someone removed a capability is worse than one that
        draws the stage as empty, which is what it is.
        """
        for p in self.found:
            if p.feature.key == key:
                return p
        return Presence(Feature(key, key, "operate", "not registered",
                                (f"{key}/**",), made_by="—"), 0)

    def n(self, key: str) -> int:
        return self.by_key(key).count

    @property
    def gaps(self) -> list[Presence]:
        return [p for p in self.found if p.state == "gap"]


# ----------------------------------------------------------------- gather ----
def _count(base: Path, globs: tuple[str, ...]) -> tuple[int, str]:
    """How many paths match, and the one to print.

    Glob order is honoured for the printed path and ignored for the count: the
    first glob is the feature's most descriptive location (`mdl/mdl.json`, not
    the `mdl/connection.json` that sorts before it), while the count has to be
    de-duplicated across globs that overlap.
    """
    seen: set[Path] = set()
    where = ""
    for g in globs:
        hits = sorted(base.glob(g), key=str)
        if hits and not where:
            where = str(hits[0].relative_to(base))
        seen.update(hits)
    return len(seen), where


def _graph_counts(pdir: Path) -> tuple[dict[str, int], int]:
    """Node counts by kind, and how many columns carry PII.

    Absent graph is a normal answer, not an error: a project is scaffolded
    before it is built, and this runs at scaffold time.
    """
    gp = pdir / "kg" / "graph.duckdb"
    if not gp.exists():
        return {}, 0
    try:
        from pf.kg.store import open_graph

        with open_graph(gp, read_only=True) as g:
            counts = dict(g.counts())
            pii = sum(1 for c in g.nodes("Column") if c.props.get("pii"))
        return counts, pii
    except Exception:  # noqa: BLE001 — a locked or half-built graph is not fatal
        return {}, 0


#: Lineage edges only. `has_column` and the semantic edges are true and would
#: turn a five-step example into a forty-step one.
_FLOW = ("feeds", "measures")


def _chain(pdir: Path, limit: int = 6) -> Chain:
    """One real path through the project, chosen as the most consequential.

    Preference runs downstream-first — an exposure is what somebody actually
    reads, so the chain that ends at one is the chain worth showing. Falling
    back through metric, mart and table means an empty project still gets an
    honest answer rather than a diagram of nothing.
    """
    gp = pdir / "kg" / "graph.duckdb"
    if not gp.exists():
        return Chain(note="no graph yet — run `pf seed`, then `pf kg build`")
    try:
        from pf.kg.store import open_graph

        with open_graph(gp, read_only=True) as g:
            target = None
            for kind in ("Exposure", "Metric", "Model", "Table"):
                pool = sorted(g.nodes(kind), key=lambda n: n.name)
                if kind == "Model":
                    pool = [m for m in pool if m.layer == "marts"] or pool
                if pool:
                    target = pool[0]
                    break
            if target is None:
                return Chain(note="the graph holds no tables yet — run `pf seed`")

            steps = [(target.kind, target.name)]
            seen, cur, more = {target.id}, target, False
            while True:
                parents = sorted(
                    (e for e in g.in_edges(cur.id)
                     if e.kind in _FLOW and e.src not in seen),
                    key=lambda e: e.src)
                if not parents:
                    break
                if len(steps) >= limit:
                    more = True
                    break
                nxt = g.node(parents[0].src)
                if nxt is None:
                    break
                seen.add(nxt.id)
                steps.append((nxt.kind, nxt.name))
                cur = nxt
            steps.reverse()
            if len(steps) == 1:
                return Chain(steps=steps,
                             note="nothing upstream — this node has no lineage yet")
            return Chain(steps=steps, truncated=more)
    except Exception as exc:  # noqa: BLE001 — the map must render without a graph
        return Chain(note=f"graph unreadable ({type(exc).__name__})")


def _warehouse(pdir: Path) -> str:
    """What `prod` actually points at, which is not always what it claims to."""
    p = pdir / "transform" / "profiles.yml"
    if not p.exists():
        return ""
    try:
        from pf.scaffold.generator import target_type

        return target_type(p.read_text(), "prod") or ""
    except Exception:  # noqa: BLE001
        return ""


def _tools(root: Path, group: str, project: str) -> list[str]:
    try:
        from pf.tools import enabled_names

        return sorted(enabled_names(root, group, project))
    except Exception:  # noqa: BLE001 — a broken tool registry must not stop the map
        return []


def _capabilities(root: Path, pdir: Path, group: str, project: str) -> list[str]:
    """Which capabilities this project actually has, judged by their own files.

    Asked rather than assumed: `defaults()` says what a *new* project would get,
    which is a different question from what this one has. A project scaffolded
    before a capability became a default has none of its files, and reporting it
    as enabled would be the map agreeing with the registry instead of with the
    project.

    Most capabilities do not earn a row in the coverage table — nine of them
    write one documentation page each — so this line is where they are named.
    """
    try:
        from pf.capabilities import CAPABILITIES, render

        ctx = {"group": group, "project": project,
               "module": project.replace("-", "_")}
        out = []
        for name, cap in sorted(CAPABILITIES.items()):
            targets = [(root if rel.startswith(".github/") else pdir) / rel
                       for rel in (render(r, ctx) for r in cap.files)]
            if targets and all(t.exists() for t in targets):
                out.append(name)
        return out
    except Exception:  # noqa: BLE001
        return []


def _unmapped(pdir: Path, registry: tuple[Feature, ...]) -> list[str]:
    """Top-level entries no feature claims.

    Top level only, and that is the point rather than a limitation: a platform
    feature earns a directory. `catalog/`, `evals/` and `mdl/` each arrived that
    way, and each would have appeared here on the day it was added.

    The registry is passed in rather than recomputed so this answers the same
    question the rest of the map does. Asking a second time would let a tool
    registered between the two calls produce a document that claims a directory
    its own unmapped list still reports.
    """
    claimed = {s for f in registry for s in f.segments}
    out = []
    for p in sorted(pdir.iterdir()):
        if p.name in IGNORED or p.name in claimed:
            continue
        out.append(p.name + ("/" if p.is_dir() else ""))
    return out


def gather(root: str | Path, group: str, project: str) -> Arch:
    """Everything the map needs, read only from this project."""
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    counts, pii = _graph_counts(pdir)

    a = Arch(group=group, project=project, pdir=pdir, root=root,
             is_rollup=project.endswith("-rollup"),
             warehouse=_warehouse(pdir),
             module=project.replace("-", "_"),
             counts=counts, pii=pii,
             tools=_tools(root, group, project),
             caps=_capabilities(root, pdir, group, project),
             chain=_chain(pdir))

    if a.is_rollup:
        # Names only, from the group's own directory listing — the same thing
        # the group card publishes. No sister file is opened here or anywhere.
        sisters_dir = root / "groups" / group / "projects"
        if sisters_dir.exists():
            a.sisters = sorted(p.name for p in sisters_dir.iterdir()
                               if p.is_dir() and p.name != project
                               and not p.name.startswith("."))

    registry = features()
    for f in registry:
        n, where = _count(pdir, f.paths) if f.paths else (0, "")
        if f.repo_paths:
            rn, rwhere = _count(root, tuple(g.format(project=project, group=group)
                                            for g in f.repo_paths))
            n, where = n + rn, where or rwhere
        # A graph, when there is one, is the authority — including when its
        # answer is zero. Falling back to the file count on a missing *kind*
        # rather than a missing *graph* reported "raw tables: 1" for a roll-up
        # whose graph holds no tables at all, because one `data/*.duckdb` file
        # existed. The file count is only ever a stand-in for a project that has
        # not been built yet.
        if f.count_kind and counts:
            n = counts.get(f.count_kind, 0)
        if f.self_reporting:
            n = 1
        a.found.append(Presence(f, n, where or (f.paths or f.repo_paths or ("",))[0]))

    a.unmapped = _unmapped(pdir, registry) if pdir.exists() else []
    return a


# ----------------------------------------------------------------- render ----
def _node(nid: str, label: str, cls: str, count: int | None = None,
          indent: str = "    ", present: bool | None = None) -> str:
    """One box. Grey and stated as absent when it is not there.

    Drawn rather than dropped: the shape of the map is then the same in every
    project, so a reader who knows one knows them all, and a hole is visible as
    a hole instead of as an absence they have to notice.

    `count` for a quantity, `present` for a fixed artefact — a two-file manifest
    labelled "2" answers a question nobody asked.
    """
    if count is not None:
        cls = cls if count else "neutral"
        label = f"{label}<br/>{count}" if count else f"{label}<br/>none yet"
    elif present is not None and not present:
        cls, label = "neutral", f"{label}<br/>none yet"
    return f'{indent}{nid}["{label}"]:::{cls}'


def _spine(a: Arch) -> list[str]:
    """Ingest to delivery, with this project's real counts on every stage."""
    src_dir = a.pdir / "src" / a.module / "sources"
    src_names = ", ".join(sorted(p.stem for p in src_dir.glob("[!_]*.py"))[:3])
    pages = len(list((a.pdir / "reporting" / "pages").rglob("*.md")))
    inner = "        "

    out = [
        "```mermaid", "flowchart LR",
        '    subgraph LI["ingest"]',
        f"{inner}direction TB",
        _node("I1", "dlt sources" + (f"<br/>{viz.esc(src_names, 34)}" if src_names else ""),
              "ingress", a.n("sources"), inner),
        _node("I2", f"pipeline<br/>{viz.esc(a.module, 24)}", "platform", indent=inner),
        _node("I3", "raw tables", "raw", a.n("raw_tables"), inner),
        "    end",
        '    subgraph LT["transform · dbt"]',
        f"{inner}direction TB",
        _node("T1", "staging", "model", a.n("staging"), inner),
        _node("T2", "marts", "model", a.n("marts"), inner),
        _node("T3", "data tests", "model", a.n("dbt_tests"), inner),
        "    end",
        '    subgraph LS["semantics"]',
        f"{inner}direction TB",
        _node("S1", "metrics", "metric", a.n("metrics"), inner),
        _node("S2", "dimensions", "metric", a.n("dimensions"), inner),
        _node("S3", "MDL contract", "platform", indent=inner,
              present=a.by_key("mdl").present),
        "    end",
        '    subgraph LD["delivery"]',
        f"{inner}direction TB",
        _node("D1", "exposures", "exposure", a.n("exposures"), inner),
        _node("D2", "Evidence pages", "exposure", pages, inner),
        "    end",
        "    I1 --> I2 --> I3 --> T1 --> T2",
        "    T2 --> S1 --> D1 --> D2",
        "    T2 --> S2",
        "    S1 -.published as.-> S3",
        "    T2 -.asserted by.-> T3",
    ]
    if a.is_rollup:
        # The one legitimate cross-entity read in the platform, and the only
        # reason a sister name appears anywhere in this document.
        out.append(_node("RU", "sisters attached READ_ONLY<br/>"
                               f"{viz.esc(', '.join(a.sisters) or 'none yet', 40)}",
                         "project"))
        out.append("    RU --> T1")
    out += viz.classdefs(["ingress", "platform", "raw", "model", "metric",
                          "exposure", "neutral", "project", "lane"])
    out += ["    class LI,LT,LS,LD lane", "```"]
    return out


def _example(a: Arch) -> list[str]:
    """The same spine, but with this project's own names on it.

    A generic diagram teaches the shape; only a real chain teaches that
    `stg_stripe__charges` is what `revenue` is actually built from. That is the
    fact an agent would otherwise reconstruct by reading four files.
    """
    if not a.chain.steps:
        return [f"_{a.chain.note}_"]

    cls = {"Source": "ingress", "Table": "raw", "Model": "model",
           "Metric": "metric", "Exposure": "exposure", "Dimension": "metric"}
    used = {cls.get(k, "neutral") for k, _ in a.chain.steps}
    out = ["```mermaid", "flowchart LR"]
    ids = []
    if a.chain.truncated:
        ids.append("XU")
        used.add("neutral")
        out.append(_node("XU", "… further upstream", "neutral"))
    for i, (kind, name) in enumerate(a.chain.steps):
        nid = f"X{i}"
        ids.append(nid)
        out.append(_node(nid, f"{viz.esc(kind, 14)}<br/>{viz.esc(name, 34)}",
                         cls.get(kind, "neutral")))
    out.append("    " + " --> ".join(ids))
    out += viz.classdefs(sorted(used))
    out.append("```")
    if a.chain.note:
        out.append("")
        out.append(f"_{a.chain.note}_")
    return out


def _control(a: Arch) -> list[str]:
    """What stops a bad change, and what each thing is reading when it does.

    Worth drawing separately from the spine because the enforcement path runs
    *across* it: one annotation file decides a staging model, a PII policy and a
    monitor, and no left-to-right pipeline shows that.
    """
    ci = a.by_key("ci")
    inner = "        "
    out = ["```mermaid", "flowchart TB",
           _node("A", "annotations<br/>contracts/annotations.yaml", "platform",
                 a.n("annotations")),
           _node("O", "ontology<br/>platform + group + project", "platform"),
           _node("P", "policy rules", "platform", a.n("policy")),
           # Deliberately not a node count. Columns are backfilled from
           # `information_schema`, so the total differs between a machine with a
           # warehouse and a CI runner without one — and a number that moves
           # with the environment turns `pf arch --check` into a coin toss. The
           # spine's counts all come from annotations and the dbt manifest,
           # which travel with the checkout.
           _node("K", "knowledge graph<br/>kg_search · impact_analysis",
                 "platform" if a.counts else "neutral"),
           '    subgraph LG["what it stops"]',
           f"{inner}direction TB",
           _node("E1", "pf check<br/>conformance", "good", indent=inner),
           _node("E2", "PreToolUse hook<br/>denies secrets + generated files",
                 "good" if a.by_key("settings").present else "neutral", indent=inner),
           _node("E3", "pre-commit<br/>blast radius", "good", indent=inner),
           _node("E4", f"CI<br/>{viz.esc(Path(ci.where).name if ci.where else 'none', 28)}",
                 "good" if ci.present else "neutral", indent=inner),
           "    end",
           "    A --> O --> P",
           "    A --> K",
           "    P -.governs.-> K",
           "    K --> E2",
           "    K --> E3",
           "    K --> E4",
           "    O --> E1",
           ]
    out += viz.classdefs(["platform", "good", "neutral", "lane"])
    out += ["    class LG lane", "```"]
    return out


_STATE = {"ok": "✓", "gap": "**gap**", "optional": "—"}


def _coverage(a: Arch) -> list[str]:
    """Every feature, present or not, grouped by lane.

    The absent rows are the ones that earn this table. A reader can see that a
    project has no exposures — and therefore that impact analysis stops at its
    marts — without discovering it by running an impact query that comes back
    empty and looking safe.
    """
    out = ["| feature | | where | what it is |", "|---|---|---|---|"]
    for lane in LANES:
        rows = [p for p in a.found if p.feature.lane == lane]
        if not rows:
            continue
        out.append(f"| **{lane}** | | | |")
        for p in rows:
            mark = _STATE[p.state]
            n = f" {p.count}" if p.present and p.countable and p.count > 1 else ""
            where = f"`{p.where}`" if p.where else ""
            why = p.feature.why if p.present else f"{p.feature.why} — `{p.feature.made_by}`"
            out.append(f"| {p.feature.title} | {mark}{n} | {where} | {why} |")
    return out


def render(a: Arch) -> str:
    """The map. Deterministic for a fixed project: no dates, everything sorted."""
    kind = "roll-up" if a.is_rollup else "entity"
    lines = [
        HEADER,
        f"# {a.project} — architecture",
        "",
        f"**{a.group}** group · {kind} · warehouse `{a.warehouse or 'unset'}` · "
        f"module `{a.module}`"
        + (f" · sisters attached: {', '.join(a.sisters) or 'none'}" if a.is_rollup else ""),
        "",
        ("Generated from this project alone. Sister projects are never read; "
         "cross-entity questions belong in the roll-up."),
        "",
        "## The spine",
        "",
    ]
    lines += _spine(a)
    lines += ["", "## A real path through it", ""]
    lines += _example(a)
    lines += ["", "## What enforces what", ""]
    lines += _control(a)
    lines += ["", "## Every feature, present or not", ""]
    lines += _coverage(a)

    # Named here rather than given rows: nine capabilities that each write one
    # documentation page would be nine near-identical lines in the table. One
    # that writes somewhere nothing else claims does earn a row — see
    # `pf.features.derive`.
    if a.caps:
        lines += ["", f"**Capabilities:** {', '.join(f'`{c}`' for c in a.caps)}"]
    if a.tools:
        lines += ["", f"**Tools enabled:** {', '.join(f'`{t}`' for t in a.tools)}"]
    if a.pii:
        lines += ["", (f"**PII columns:** {a.pii} — masked by policy, "
                       "never selected into a mart unaggregated")]

    gaps = a.gaps
    if gaps:
        lines += ["", "## Gaps", ""]
        lines += [f"- **{p.feature.title}** — {p.feature.why}. Fix: `{p.feature.made_by}`"
                  for p in gaps]

    if a.unmapped:
        lines += ["", "## Unmapped", "",
                  ("Present in the project and claimed by no feature in "
                   "`pf.architecture.FEATURES`. Either it belongs in the "
                   "registry or it does not belong in the project:"), ""]
        lines += [f"- `{u}`" for u in a.unmapped]

    lines += ["", "---", "",
              ("Query before reading: `kg_search`, `kg_neighbors`, `kg_path`, "
               "`impact_analysis`. Regenerate this file with "
               f"`pf arch {a.group} {a.project}`.")]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ write ----
def write(root: str | Path, group: str, project: str) -> tuple[Path, Arch]:
    a = gather(root, group, project)
    out = a.pdir / DOC_REL
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(a))
    return out, a


@dataclass
class Drift:
    """Is the committed map still what the project would produce?"""

    project: str
    missing: bool = False
    stale: bool = False
    unmapped: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not (self.missing or self.stale or self.unmapped)

    def __str__(self) -> str:
        if self.missing:
            return f"{self.project}: no architecture map — run `pf arch`"
        bits = []
        if self.stale:
            bits.append("map is stale — the project changed since it was written")
        if self.unmapped:
            bits.append(f"{len(self.unmapped)} unmapped entry(ies): "
                        + ", ".join(self.unmapped))
        if not bits:
            return f"{self.project}: ok"
        return f"{self.project}: " + "; ".join(bits)


def drift(root: str | Path, group: str, project: str) -> Drift:
    a = gather(root, group, project)
    out = a.pdir / DOC_REL
    d = Drift(project=f"{group}/{project}", unmapped=list(a.unmapped))
    if not out.exists():
        d.missing = True
        return d
    d.stale = out.read_text() != render(a)
    return d


def lint_doc(text: str) -> list[str]:
    """Every mermaid block in a rendered map, checked. Empty means clean."""
    problems: list[str] = []
    for i, b in enumerate(viz.blocks(text), 1):
        problems += [f"diagram {i}: {p}" for p in viz.lint(b)]
    return problems


def summary(a: Arch) -> dict[str, object]:
    """Machine-readable, for the UI and for `pf pr report`."""
    return {
        "group": a.group, "project": a.project, "rollup": a.is_rollup,
        "warehouse": a.warehouse,
        "capabilities": a.caps, "tools": a.tools,
        "features": {p.feature.key: {"state": p.state, "count": p.count,
                                     "source": p.feature.source}
                     for p in a.found},
        "gaps": [p.feature.key for p in a.gaps],
        "unmapped": a.unmapped,
        "nodes": sum(a.counts.values()),
    }


def as_json(a: Arch) -> str:
    return json.dumps(summary(a), indent=2, sort_keys=True)
