"""The repository, drawn from the repository.

An architecture diagram is stale the day it is drawn, and a stale map is worse
than none: it sends a reader confidently to a path that moved. So this one is
not drawn. Every count, every path and every list below is read from the thing
it describes, and `pf arch check` fails the build when the committed copy and
the repository disagree.

That is the same rule as `kg/context_card.md` and `platform/tests/README.md`,
for the same reason — everything here is a projection, never a parallel
hand-maintained file.

What it is *for*: an agent that would otherwise grep. "Where do capabilities
live", "what actually runs on a pull request", "which of these eight projects
has metrics" are questions with fixed answers that cost a dozen tool calls to
rediscover. The diagrams carry the shape; the tables carry the paths.

Diagrams are capped deliberately. `platform/toolkits/viz-standards` is explicit
that a node-link diagram past a handful of nodes is read by nobody, so anything
that grows with the repo — 22 toolkits, 18 upstreams, 8 projects — is a table,
and only the fixed structure is drawn.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

import yaml

#: Node fill/stroke per plane, matching `docs/KG-ATLAS.md` so the two documents
#: are readable side by side. Pale fill, saturated stroke, near-black ink — the
#: house rule, and the only one that survives GitHub's light and dark pages.
PALETTE = {
    "code":  ("#d9f4ee", "#0f766e"),
    "data":  ("#e9e1fb", "#5b21b6"),
    "gov":   ("#e0e6ed", "#334155"),
    "ext":   ("#fdf6e3", "#8a6d1f"),
}


@dataclass
class Facts:
    """Everything the document asserts, gathered once."""

    groups: dict[str, list[str]] = field(default_factory=dict)
    project_shape: dict[str, dict[str, int]] = field(default_factory=dict)
    capabilities: list[tuple[str, bool, str]] = field(default_factory=list)
    toolkits: list[str] = field(default_factory=list)
    upstreams: int = 0
    ontology: dict[str, int] = field(default_factory=dict)
    kg_kinds: dict[str, int] = field(default_factory=dict)
    cli: dict[str, int] = field(default_factory=dict)
    tests: dict[str, int] = field(default_factory=dict)
    workflows: list[str] = field(default_factory=list)

    @property
    def projects(self) -> int:
        return sum(len(v) for v in self.groups.values())


def gather(root: str | Path) -> Facts:
    """Read the repository. Nothing here is declared; everything is counted."""
    r = Path(root)
    f = Facts()

    gdir = r / "groups"
    if gdir.is_dir():
        for g in sorted(x for x in gdir.iterdir() if x.is_dir() and not x.name.startswith(".")):
            pdir = g / "projects"
            f.groups[g.name] = sorted(
                x.name for x in pdir.iterdir()
                if x.is_dir() and not x.name.startswith(".")
            ) if pdir.is_dir() else []

    # Per-project shape from the committed graph, not the warehouse: graph.json
    # is tracked, so this works in a fresh clone with no DuckDB files.
    for g, projects in f.groups.items():
        for p in projects:
            gj = r / "groups" / g / "projects" / p / "kg" / "graph.json"
            if not gj.exists():
                continue
            nodes = (json.loads(gj.read_text()) or {}).get("nodes") or []
            counts: dict[str, int] = {}
            for n in nodes:
                counts[n.get("kind", "?")] = counts.get(n.get("kind", "?"), 0) + 1
            f.project_shape[f"{g}/{p}"] = counts

    try:
        # `CAPABILITIES` is a mutable global that tools add to by side effect,
        # so what it holds depends on whether tool discovery has run. The CLI
        # triggers it at import; a bare `import pf.archmap` does not. Without
        # this line the document renders eleven capabilities when generated by
        # `pf arch build` and eight when checked from a test process, and the
        # currency check fails against a file nothing is wrong with.
        #
        # Idempotent, and it never overwrites a hand-written capability.
        from pf.tools import register_capabilities
        register_capabilities()
    except Exception:  # noqa: BLE001 — a broken tool must not empty the map
        pass

    try:
        from pf.capabilities import CAPABILITIES
        f.capabilities = sorted(
            (c.name, c.default_enabled, _contributes(c)) for c in CAPABILITIES.values()
        )
    except Exception:  # noqa: BLE001 — a broken registry must not stop the map
        pass

    tdir = r / "platform" / "toolkits"
    if tdir.is_dir():
        f.toolkits = sorted(x.name for x in tdir.iterdir() if x.is_dir())

    reg = r / "platform" / "src" / "pf" / "vendor" / "registry.yaml"
    if reg.exists():
        f.upstreams = len((yaml.safe_load(reg.read_text()) or {}).get("upstreams") or [])

    try:
        from pf.ontology.model import load_ontology
        o = load_ontology()
        f.ontology = {"classes": len(o.classes), "relations": len(o.relations),
                      "policies": len(o.policies), "roles": len(o.roles)}
    except Exception:  # noqa: BLE001
        pass

    try:
        from pf.kg.store import EDGE_KINDS, NODE_KINDS
        f.kg_kinds = {"nodes": len(NODE_KINDS), "edges": len(EDGE_KINDS)}
    except Exception:  # noqa: BLE001
        pass

    try:
        from pf.cli import app
        f.cli = {"commands": len(app.registered_commands),
                 "groups": len(app.registered_groups)}
    except Exception:  # noqa: BLE001
        pass

    try:
        from pf.testmap import scan
        files = scan(r / "platform" / "tests")
        f.tests = {"files": len(files), "tests": sum(x.tests for x in files),
                   "groups": len({x.group for x in files if x.group})}
    except Exception:  # noqa: BLE001
        pass

    wdir = r / ".github" / "workflows"
    if wdir.is_dir():
        f.workflows = sorted(x.name for x in wdir.glob("*.yml"))
    return f


def _contributes(cap) -> str:
    """The short answer to "what does enabling this actually do"."""
    bits = []
    if cap.files:
        bits.append(f"{len(cap.files)} file(s)")
    if cap.ci_jobs:
        bits.append(f"ci: {', '.join(sorted(cap.ci_jobs))}")
    if cap.gate:
        bits.append("gate rules")
    if cap.settings:
        bits.append("settings")
    if cap.env:
        bits.append(f"env: {', '.join(cap.env)}")
    return " · ".join(bits) or "—"


# --------------------------------------------------------------- render -----
def _classdefs(*names: str) -> list[str]:
    return [f"  classDef {n} fill:{PALETTE[n][0]},stroke:{PALETTE[n][1]},"
            f"stroke-width:1.4px,color:#0b0b0b" for n in names]


def _layout(f: Facts) -> str:
    """Where things live. The only diagram that names directories."""
    proj = f.projects
    groups = len(f.groups)
    return "\n".join([
        "```mermaid",
        "flowchart TB",
        '  subgraph SHARED["platform/ — shared by every project, never edited per company"]',
        "    direction LR",
        (f'    ENG["src/pf/<br/>{f.cli.get("commands", 0)} commands · '
         f'{f.cli.get("groups", 0)} groups"]'),
        f'    TK["toolkits/<br/>{len(f.toolkits)} craft toolkits"]',
        (f'    TST["tests/<br/>{f.tests.get("groups", 0)} groups · '
         f'{f.tests.get("tests", 0)} tests"]'),
        '    ENT["entrypoints/<br/>container entrypoints"]',
        "  end",
        "",
        f'  subgraph ENTITIES["groups/ — {groups} groups, {proj} projects"]',
        "    direction LR",
        '    GRP["&lt;group&gt;/ontology/<br/>extension · instance · policy"]',
        '    PRJ["&lt;group&gt;/projects/&lt;project&gt;/<br/>src · transform · kg · governance"]',
        "    GRP --> PRJ",
        "  end",
        "",
        f'  VEN["vendor/<br/>{f.upstreams} pinned upstreams · read-only"]',
        '  GATE["gate.yaml + gate.capabilities.yaml<br/>pre-commit hook and CI"]',
        "",
        "  SHARED --> ENTITIES",
        "  VEN -.provenance.-> SHARED",
        "  GATE -.judges.-> ENTITIES",
        "  GATE -.judges.-> SHARED",
        "",
        *_classdefs("code", "data", "gov", "ext"),
        "  class ENG,TK,TST,ENT code",
        "  class GRP,PRJ data",
        "  class GATE gov",
        "  class VEN ext",
        '  style SHARED fill:#f4fbf9,stroke:#0f766e,stroke-dasharray:5 4,color:#0b0b0b',
        '  style ENTITIES fill:#f8f5fe,stroke:#5b21b6,stroke-dasharray:5 4,color:#0b0b0b',
        "```",
    ])


def _pipeline() -> str:
    """One project, source to consumer. Names are conventions, not one company's."""
    return "\n".join([
        "```mermaid",
        "flowchart LR",
        '  SRC["external source<br/>API · file · database"]',
        '  DLT["src/&lt;module&gt;/sources.py<br/>dlt @resource"]',
        '  ANN["contracts/annotations.yaml<br/>concept · roles · links · grain"]',
        '  DUCK[("data/&lt;project&gt;.duckdb<br/>raw schema")]',
        '  STG["transform/models/staging/<br/>stg_&lt;source&gt;__&lt;table&gt;.sql"]',
        '  MART["transform/models/marts/<br/>fct_* · dim_*"]',
        '  SEM["transform/models/semantic/<br/>MetricFlow measures + metrics"]',
        '  EXP["exposures<br/>dashboard · application"]',
        '  KG[("kg/graph.duckdb<br/>+ graph.json (tracked)")]',
        "",
        "  SRC --> DLT --> DUCK --> STG --> MART --> SEM --> EXP",
        "  DLT -.exports.-> ANN",
        "  ANN --> KG",
        "  MART --> KG",
        "  SEM --> KG",
        "",
        *_classdefs("code", "data", "gov"),
        "  class DLT,STG,MART,SEM code",
        "  class SRC,DUCK,KG data",
        "  class ANN,EXP gov",
        "```",
    ])


def _seams() -> str:
    """How one edit reaches eight projects — the thing worth understanding first."""
    return "\n".join([
        "```mermaid",
        "flowchart LR",
        '  CAP["Capability<br/>pf/capabilities.py"]',
        '  TOOL["Tool<br/>pf.tools entry point"]',
        '  BOOT["pf bootstrap<br/>idempotent, --all"]',
        '  FILES["scaffolded files"]',
        '  SETT[".claude/settings.json"]',
        '  GRULES["gate.capabilities.yaml"]',
        '  CI[".github/workflows/&lt;project&gt;.yml"]',
        '  RUN["Dagster assets · CLI · UI"]',
        "",
        "  CAP --> BOOT",
        "  TOOL --> BOOT",
        "  TOOL --> RUN",
        "  BOOT --> FILES",
        "  BOOT --> SETT",
        "  BOOT --> GRULES",
        "  BOOT --> CI",
        "",
        *_classdefs("code", "gov", "ext"),
        "  class CAP,TOOL,BOOT code",
        "  class GRULES,CI gov",
        "  class FILES,SETT,RUN ext",
        "```",
    ])


def _context() -> str:
    """What an agent is charged for, and what it should ask for instead."""
    return "\n".join([
        "```mermaid",
        "flowchart TB",
        '  subgraph ALWAYS["always on — paid on every request, budgeted by pf tokens"]',
        "    direction LR",
        '    R["CLAUDE.md<br/>the router"]',
        '    PC["&lt;project&gt;/CLAUDE.md<br/>600 tokens"]',
        '    CARD["kg/context_card.md<br/>1500 tokens"]',
        '    GC["kg/group_card.md<br/>400 tokens"]',
        "  end",
        '  subgraph ONDEMAND["on demand — free until the description matches"]',
        "    direction LR",
        '    SK["toolkit skills"]',
        '    DOC["docs/*.md<br/>ARCHITECTURE · KG-ATLAS · POLICY"]',
        "  end",
        '  subgraph ASKED["queried — never loaded"]',
        "    direction LR",
        '    KGQ["kg_search · kg_neighbors · kg_path"]',
        '    IMP["impact_analysis"]',
        '    MF["query_metrics"]',
        "  end",
        "",
        "  ALWAYS --> ONDEMAND --> ASKED",
        "",
        *_classdefs("gov", "code", "data"),
        "  class R,PC,CARD,GC gov",
        "  class SK,DOC code",
        "  class KGQ,IMP,MF data",
        '  style ALWAYS fill:#f4f6f9,stroke:#334155,stroke-dasharray:5 4,color:#0b0b0b',
        '  style ONDEMAND fill:#f4fbf9,stroke:#0f766e,stroke-dasharray:5 4,color:#0b0b0b',
        '  style ASKED fill:#f8f5fe,stroke:#5b21b6,stroke-dasharray:5 4,color:#0b0b0b',
        "```",
    ])


def _merge_path() -> str:
    return "\n".join([
        "```mermaid",
        "flowchart LR",
        '  EDIT["an edit"]',
        '  HOOK["pre-commit<br/>--diff-filter=ACMR"]',
        '  RULES["denylist · impact_required<br/>maxFiles"]',
        '  BLAST["impact_analysis<br/>against the base graph"]',
        '  PRCI["&lt;project&gt;.yml<br/>impact-gate · kg-current · recce"]',
        '  PLCI["platform-tests.yml<br/>ruff · pf test check · pytest"]',
        '  MERGE(["merge"])',
        "",
        "  EDIT --> HOOK --> RULES --> BLAST --> PRCI --> MERGE",
        "  EDIT --> PLCI --> MERGE",
        "",
        *_classdefs("gov", "code"),
        "  class HOOK,RULES,BLAST,MERGE gov",
        "  class PRCI,PLCI code",
        "```",
    ])


def _table(header: list[str], rows: list[list[str]], align: str = "") -> list[str]:
    sep = align or "|".join(["---"] * len(header))
    return ["| " + " | ".join(header) + " |", "|" + sep + "|",
            *["| " + " | ".join(r) + " |" for r in rows], ""]


def render(f: Facts) -> str:
    """The document. Deterministic — it is compared byte for byte."""
    out: list[str] = [
        "# The platform, drawn from the platform",
        "",
        "GENERATED by `pf arch build`. Do not hand-edit — `pf arch check` fails",
        "when this file and the repository disagree, and the repository wins.",
        "",
        (f"{len(f.groups)} groups · {f.projects} projects · "
         f"{len(f.toolkits)} toolkits · {f.upstreams} pinned upstreams · "
         f"{f.tests.get('tests', 0)} tests"),
        "",
        "Read this instead of grepping. Every diagram is the shape; every table",
        "is the path. Where a question has a fixed answer, it is below.",
        "",
        "---",
        "",
        "## Where everything lives",
        "",
        _layout(f),
        "",
        "**The one rule that is not obvious:** `platform/` is shared by every",
        "project and `groups/<g>/projects/<p>/` is not. Business logic never",
        "transfers between entities — an assumption carried across is a bug, and",
        "`gate.yaml`'s `platform_denylist` refuses the write in both directions.",
        "",
        "### Straight to the file",
        "",
        *_table(
            ["Looking for", "Path"],
            [
                ["the CLI, and everything it does", "`platform/src/pf/cli.py`"],
                ["knowledge graph: store, build, query, impact", "`platform/src/pf/kg/`"],
                ["ontology, topology, policy, validation", "`platform/src/pf/ontology/`"],
                ["MDL · OWL · otop · OpenMetadata exports", "`platform/src/pf/projections/`"],
                ["how a feature reaches every project", "`platform/src/pf/capabilities.py`"],
                ["pluggable tools (recce, wren, …)", "`platform/src/pf/tools/`"],
                ["scaffolding and the idempotent bootstrap", "`platform/src/pf/scaffold/`"],
                ["the MCP server an agent actually calls", "`platform/src/pf/mcp/server.py`"],
                ["the pre-commit gate", "`platform/hooks/pre_commit.sh` + `gate.yaml`"],
                ["what the suite guards", "`platform/tests/README.md`"],
                ["what the graph is made of", "`docs/KG-ATLAS.md`"],
                ["how policy layers", "`docs/POLICY.md`"],
                ["the session layer, hooks and commands", "`platform/toolkits/power-tools/`"],
                ["what was taken from each upstream", "`platform/src/pf/vendor/registry.yaml`"],
            ]),
        "---",
        "",
        "## One project, source to consumer",
        "",
        _pipeline(),
        "",
        "Names above are the platform's conventions, not one company's data.",
        "For a real project's tables, marts and metrics, read its card —",
        "`kg/context_card.md`, regenerated by `pf kg card` — or ask the graph.",
        "",
        "### What each project actually holds",
        "",
        "Counted from the tracked `kg/graph.json`, so this works in a fresh",
        "clone. A `0` is the finding: no Model means the dbt manifest was never",
        "parsed and the merge gate cannot run; no Metric means every business",
        "question falls back to raw SQL.",
        "",
    ]

    kinds = ["Table", "Model", "Metric", "Exposure", "Policy"]
    rows = []
    for name in sorted(f.project_shape):
        c = f.project_shape[name]
        rows.append([f"`{name}`", *[str(c.get(k, 0)) for k in kinds],
                     str(sum(c.values()))])
    out += _table(["Project", *kinds, "nodes"], rows,
                  align="---|" + "|".join(["--:"] * (len(kinds) + 1)))

    out += [
        (f"Every graph carries the same {f.ontology.get('classes', 0)} ontology "
         f"classes and {f.ontology.get('relations', 0)} relations — vocabulary "
         f"is shared at the group, so a project instantiates only the part of it "
         f"it needs."),
        "",
        "Policy is the exception: it layers platform → group → project and may",
        "only ever tighten. A project showing more policies than the floor has",
        "declared obligations of its own — see `docs/POLICY.md`.",
        "",
        "---",
        "",
        "## How one edit reaches every project",
        "",
        _seams(),
        "",
        "A **Capability** is declarative: files, settings, gate rules, CI jobs.",
        "A **Tool** is a capability that also runs — Dagster assets, a UI, CLI",
        "verbs — registered through a `pf.tools` entry point in any installed",
        "package. Adding either touches no scaffolder, no CLI and no workflow.",
        "",
        *_table(["Capability", "Default", "Contributes"],
                [[f"`{n}`", "**yes**" if d else "opt-in", c]
                 for n, d, c in f.capabilities]),
        "`pf bootstrap --all` is what carries a new one into projects that",
        "already exist. It refuses a partial backfill — a capability applies only",
        "when every file it writes is absent — so it can never overwrite a file",
        "someone has edited.",
        "",
        "---",
        "",
        "## What context costs",
        "",
        _context(),
        "",
        "`pf tokens` fails the build when an always-on artefact exceeds its",
        "budget, because that tier is paid by every request for the life of the",
        "project. The graph is the opposite: never loaded, only asked.",
        "",
        "---",
        "",
        "## What has to pass before a merge",
        "",
        _merge_path(),
        "",
        *_table(["Workflow", "Runs"],
                [[f"`{w}`", "generated per project — `pf bootstrap`"
                  if w not in {"platform-tests.yml", "claude-review.yml",
                               "bot-findings.yml", "pr-report.yml",
                               "vendor-sync.yml"} else "hand-written, repo-wide"]
                 for w in f.workflows]),
        "---",
        "",
        "## Keeping this true",
        "",
        "```bash",
        "uv run pf arch build      # regenerate this file",
        "uv run pf arch check      # fail if it and the repo disagree",
        "```",
        "",
        "`pf arch check` runs in `platform-tests.yml` and inside the suite, so a",
        "change that alters the shape of this repository cannot merge while this",
        "document still describes the old one.",
        "",
    ]
    return "\n".join(out)


def doc_path(root: str | Path) -> Path:
    return Path(root) / "docs" / "ARCHITECTURE.md"


def drift(root: str | Path) -> str:
    """Empty when the committed document matches the repository."""
    p = doc_path(root)
    if not p.exists():
        return f"{p} does not exist; run `pf arch build`"
    if p.read_text() != render(gather(root)):
        return f"{p} is stale; run `pf arch build`"
    return ""
