"""The whole repository, as one graph you can walk in Neo4j Bloom.

Every project already builds a knowledge graph — `kg/graph.duckdb`, two tables,
fourteen node kinds and fourteen edge kinds. Eight of them exist and none can
see the others, which is correct while you are working on a project and useless
when the question is about the estate: *which projects instantiate this concept*,
*what does this policy govern anywhere*, *where does a column with this name
appear twice under different meanings*.

This module answers that by unioning all eight into one export and shipping the
perspective that makes it readable.

Modelled on `neo4j-graph-examples/bloom`, which is laid out as a loader plus one
`.bloom-perspective.json`. The perspective is the interesting half: without it
Bloom shows grey circles captioned by whatever property happens to be first, and
a 13,000-node graph rendered that way is noise. With it, every kind has a colour
that means something, a caption chosen because it is what a person recognises,
and the questions people actually ask are saved as search phrases.

Three deliberate departures from the reference:

  CSV, not a dump    the reference ships `data/bloom-2026.01.dump`, a binary
                     Neo4j backup. A dump cannot be reviewed in a pull request
                     and cannot be regenerated by anyone without that exact
                     Neo4j version. This writes CSV and the Cypher that loads
                     it, so the whole export is diffable text.

  ids are qualified  `Model:orders` exists in acme-us and in acme-eu and they
                     are different models. Merging on the bare id would silently
                     weld two sisters' lineage together — the precise failure
                     the isolation rule exists to prevent. Every id is prefixed
                     with `group/project`, and the original is kept as `local_id`.

  props are flat     Neo4j properties cannot nest. A nested value is stored as
                     its JSON text rather than dropped, so nothing in `props` is
                     lost even when it cannot be queried structurally.
"""

from __future__ import annotations

import csv
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import duckdb

# --------------------------------------------------------------------- shape --

#: Which plane a node kind belongs to. The three planes are the platform's own
#: division — physical/analytical, semantic, governance — and they are what the
#: colour encodes, so a screenshot reads as three layers rather than fourteen
#: unrelated hues.
PLANE: dict[str, str] = {
    "Source": "physical", "Table": "physical", "Column": "physical",
    "Model": "physical", "Metric": "physical", "Dimension": "physical",
    "Test": "physical", "Exposure": "physical", "Project": "physical",
    "Concept": "semantic", "Property": "semantic", "Relation": "semantic",
    "Policy": "governance", "Evidence": "governance",
}

#: Pale fill, saturated stroke of the same hue. The same three colours the KG
#: Atlas and the per-project atlas already use, so the three views of this graph
#: agree on what a plane looks like.
PLANE_COLOUR = {
    "physical":   "#0f766e",
    "semantic":   "#5b21b6",
    "governance": "#334155",
}

#: A within-plane shade per kind, so `Model` and `Column` are distinguishable
#: without leaving the plane's family. Ordered light to dark by how contained the
#: thing is: a Project holds Models, a Model holds Columns.
KIND_COLOUR: dict[str, str] = {
    "Project":   "#0b4f4a", "Source": "#0f766e", "Table": "#14918a",
    "Model":     "#19a89f", "Column": "#7fd4cc", "Metric": "#0d9488",
    "Dimension": "#2dd4bf", "Test": "#5eead4", "Exposure": "#042f2e",
    "Concept":   "#5b21b6", "Property": "#a78bfa", "Relation": "#7c3aed",
    "Policy":    "#334155", "Evidence": "#64748b",
}

#: What a person recognises this node by. Bloom captions on the first property
#: unless told otherwise, and for a Column that is a surrogate id nobody reads.
CAPTION: dict[str, str] = dict.fromkeys(PLANE, "name")

#: Bloom ships a fixed icon set; these names are the stable ones. A kind with no
#: sensible icon gets none rather than a misleading one.
ICON: dict[str, str] = {
    "Project": "sitemap", "Source": "database", "Table": "table",
    "Model": "cube", "Column": "columns", "Metric": "chart-line",
    "Dimension": "filter", "Test": "check-circle", "Exposure": "tv",
    "Concept": "lightbulb", "Property": "tag", "Relation": "link",
    "Policy": "gavel", "Evidence": "file-alt",
}

#: Edge kinds that carry lineage. Bloom draws every relationship the same; these
#: are called out in the README because direction is a contract here and reading
#: one backwards inverts the answer.
LINEAGE_EDGES = ("feeds", "measures", "grouped_by", "tested_by",
                 "has_column", "contains")

NODE_HEADER = ["id:ID", "local_id", "kind:LABEL", "name", "layer", "label",
               "group", "project", "plane", "props"]
EDGE_HEADER = ["start:START_ID", "end:END_ID", "kind:TYPE", "props"]


@dataclass
class Corpus:
    """Every project's graph, unioned and qualified."""

    nodes: list[dict[str, Any]] = field(default_factory=list)
    edges: list[dict[str, Any]] = field(default_factory=list)
    projects: list[tuple[str, str, int, int]] = field(default_factory=list)
    dangling: list[tuple[str, str]] = field(default_factory=list)

    @property
    def kinds(self) -> dict[str, int]:
        out: dict[str, int] = {}
        for n in self.nodes:
            out[n["kind"]] = out.get(n["kind"], 0) + 1
        return dict(sorted(out.items(), key=lambda kv: -kv[1]))

    @property
    def edge_kinds(self) -> dict[str, int]:
        out: dict[str, int] = {}
        for e in self.edges:
            out[e["kind"]] = out.get(e["kind"], 0) + 1
        return dict(sorted(out.items(), key=lambda kv: -kv[1]))


# ------------------------------------------------------------------ collect --

def _flat(raw: Any) -> str:
    """`props` as something Neo4j will accept, losing nothing.

    A Neo4j property is a scalar or a list of scalars — it cannot nest. Rather
    than drop a nested value, keep its JSON text: unqueryable structurally, but
    present and readable in the node inspector, which is the whole point of an
    export meant for reading.
    """
    if raw in (None, "", "null"):
        return ""
    try:
        val = json.loads(raw) if isinstance(raw, str) else raw
    except (TypeError, ValueError):
        return str(raw)
    return json.dumps(val, sort_keys=True, ensure_ascii=False)


def collect(root: str | Path) -> Corpus:
    """Union every project graph under `root`, qualifying ids by project.

    An edge whose endpoint is missing is recorded rather than written. Neo4j's
    importer rejects a dangling relationship outright and names one row; this
    names all of them, which is the difference between a fixable report and a
    guessing game.
    """
    root = Path(root)
    corpus = Corpus()
    seen: set[str] = set()

    for db in sorted(root.glob("groups/*/projects/*/kg/graph.duckdb")):
        group, project = db.parts[-5], db.parts[-3]
        con = duckdb.connect(str(db), read_only=True)
        try:
            rows = con.execute(
                "SELECT id, kind, name, layer, label, props FROM kg_nodes"
            ).fetchall()
            edges = con.execute(
                "SELECT src, dst, kind, props FROM kg_edges").fetchall()
        finally:
            con.close()

        prefix = f"{group}/{project}#"
        for nid, kind, name, layer, label, props in rows:
            gid = prefix + nid
            seen.add(gid)
            corpus.nodes.append({
                "id": gid, "local_id": nid, "kind": kind, "name": name,
                "layer": layer or "", "label": label or "",
                "group": group, "project": project,
                "plane": PLANE.get(kind, "physical"), "props": _flat(props),
            })
        for src, dst, kind, props in edges:
            corpus.edges.append({
                "start": prefix + src, "end": prefix + dst,
                "kind": kind, "props": _flat(props),
            })
        corpus.projects.append((group, project, len(rows), len(edges)))

    kept = []
    for e in corpus.edges:
        if e["start"] in seen and e["end"] in seen:
            kept.append(e)
        else:
            missing = e["start"] if e["start"] not in seen else e["end"]
            corpus.dangling.append((e["kind"], missing))
    corpus.edges = kept
    return corpus


# -------------------------------------------------------------- perspective --

def templates() -> list[dict[str, Any]]:
    """Saved search phrases — the questions this repository is actually asked.

    Each one is a question somebody has had to answer by reading files. They are
    the reason to load the graph at all, so they ship with it rather than being
    left as an exercise.
    """
    def t(name: str, text: str, cypher: str,
          params: list[dict[str, Any]] | None = None) -> dict[str, Any]:
        return {"id": f"tmpl:{name}", "name": text, "text": text,
                "cypher": cypher.strip(), "hasCypherErrors": False,
                "params": params or [], "createdAt": 0}

    return [
        t("blast-radius",
          "What breaks if I change $model",
          """
          MATCH (m:Model {name: $model})-[:feeds|measures|grouped_by|tested_by*1..6]->(d)
          RETURN m, d
          """,
          [{"name": "model", "dataType": "string",
            "suggestionLabel": "Model", "suggestionProp": "name"}]),

        t("column-consumers",
          "Who consumes column $column",
          """
          MATCH (c:Column {name: $column})<-[:has_column]-(t)-[:feeds*0..4]->(d)
          RETURN c, t, d
          """,
          [{"name": "column", "dataType": "string",
            "suggestionLabel": "Column", "suggestionProp": "name"}]),

        t("concept-across-estate",
          "Where $concept is instantiated, in every project",
          """
          MATCH (k:Concept {name: $concept})<-[:instantiates]-(t)
          RETURN k, t, t.project AS project
          """,
          [{"name": "concept", "dataType": "string",
            "suggestionLabel": "Concept", "suggestionProp": "name"}]),

        t("policy-reach",
          "Everything policy $policy governs",
          """
          MATCH (p:Policy {name: $policy})-[:governs]->(a)
          OPTIONAL MATCH (p)-[:evidenced_by]->(e)
          RETURN p, a, e
          """,
          [{"name": "policy", "dataType": "string",
            "suggestionLabel": "Policy", "suggestionProp": "name"}]),

        t("ungoverned-marts",
          "Marts no policy governs",
          """
          MATCH (m:Model) WHERE m.layer = 'marts'
            AND NOT (m)<-[:governs]-(:Policy)
          RETURN m
          """),

        t("untested-models",
          "Models with no test",
          """
          MATCH (m:Model) WHERE NOT (m)-[:tested_by]->(:Test)
          RETURN m
          """),

        t("unmapped-tables",
          "Physical tables that instantiate no concept",
          """
          MATCH (t) WHERE (t:Table OR t:Model)
            AND NOT (t)-[:instantiates]->(:Concept)
          RETURN t
          """),

        t("exposure-lineage",
          "What feeds exposure $exposure",
          """
          MATCH path = (up)-[:feeds*1..8]->(x:Exposure {name: $exposure})
          RETURN path
          """,
          [{"name": "exposure", "dataType": "string",
            "suggestionLabel": "Exposure", "suggestionProp": "name"}]),

        t("same-name-different-project",
          "One name, two projects — check they mean the same thing",
          """
          MATCH (a), (b)
          WHERE a.name = b.name AND a.project < b.project
            AND labels(a) = labels(b)
          RETURN a, b LIMIT 200
          """),

        t("evidence-chain",
          "Policy to evidence, end to end",
          """
          MATCH (p:Policy)-[:evidenced_by]->(e:Evidence)
          RETURN p, e
          """),
    ]


def perspective(corpus: Corpus, name: str = "data-platform") -> dict[str, Any]:
    """The `.bloom-perspective.json` that makes the export legible."""
    kinds = corpus.kinds
    cats = []
    for i, kind in enumerate(sorted(kinds, key=lambda k: (PLANE.get(k, ""), k)), 1):
        cats.append({
            "id": i,
            "name": kind,
            "labels": [kind],
            "color": KIND_COLOUR.get(kind, PLANE_COLOUR[PLANE.get(kind, "physical")]),
            "icon": ICON.get(kind, "no-icon"),
            "size": 3 if kind in ("Project", "Concept", "Policy") else 2,
            "caption": [{"key": CAPTION.get(kind, "name")}],
            "createdAt": 0, "lastEditedAt": 0,
            "properties": [
                {"name": "name", "exclude": False, "isCaption": True,
                 "dataType": "string"},
                {"name": "local_id", "exclude": False, "isCaption": False,
                 "dataType": "string"},
                {"name": "layer", "exclude": False, "isCaption": False,
                 "dataType": "string"},
                {"name": "group", "exclude": False, "isCaption": False,
                 "dataType": "string"},
                {"name": "project", "exclude": False, "isCaption": False,
                 "dataType": "string"},
                {"name": "plane", "exclude": False, "isCaption": False,
                 "dataType": "string"},
                # The id is a join key, not something a reader needs on a node.
                {"name": "id", "exclude": True, "isCaption": False,
                 "dataType": "string"},
                {"name": "props", "exclude": False, "isCaption": False,
                 "dataType": "string"},
            ],
        })

    return {
        "name": name,
        "id": f"perspective:{name}",
        "version": "2.0.0",
        "parentPerspectiveId": None,
        "createdAt": 0, "lastEditedAt": 0,
        "categories": cats,
        "relationshipTypes": [
            {"name": k, "caption": [{"key": "kind"}],
             # A lineage edge is the one you follow; the rest are structure.
             "size": 2 if k in LINEAGE_EDGES else 1}
            for k in sorted(corpus.edge_kinds)
        ],
        "hiddenRelationshipTypes": [],
        # `Column` is 78% of the graph and swamps any view it is in. Hidden by
        # default and one click from being shown, which is the only setting that
        # makes the first render of this graph readable.
        "hiddenCategories": ["Column"],
        "hideUncategorisedData": False,
        "palette": {"colors": list(dict.fromkeys(KIND_COLOUR.values())),
                    "currentIndex": 0},
        "templates": templates(),
    }


# ------------------------------------------------------------------- cypher --

def load_cypher(node_csv: str = "nodes.csv", edge_csv: str = "edges.csv") -> str:
    """The loader. `neo4j-admin import` is faster; this works on a live database.

    Written against `LOAD CSV` rather than `neo4j-admin database import` on
    purpose: the admin importer only builds an *empty* database and must run on
    the server with filesystem access, which rules out Aura and any instance
    somebody already has data in. This runs from the browser.
    """
    kinds = "\n".join(
        f"  FOREACH (_ IN CASE WHEN row.`kind:LABEL` = '{k}' THEN [1] ELSE [] END |\n"
        f"    SET n:{k})"
        for k in sorted(PLANE)
    )
    return f"""// Load the platform knowledge graph into Neo4j for Bloom.
//
// Generated by `pf bloom build` — do not edit. Regenerate instead, or the file
// will disagree with the graph it claims to describe.
//
// Put nodes.csv and edges.csv in the database's import/ directory, then run
// this whole script in Neo4j Browser or cypher-shell.

// One constraint, and it is what makes the load idempotent: re-running MERGEs
// onto the same nodes instead of doubling the graph.
CREATE CONSTRAINT kg_node_id IF NOT EXISTS
FOR (n:KgNode) REQUIRE n.id IS UNIQUE;

// ---- nodes ----------------------------------------------------------------
// A label per kind, plus :KgNode on everything so the constraint has one thing
// to hold and Bloom still sees fourteen categories.
LOAD CSV WITH HEADERS FROM 'file:///{node_csv}' AS row
CALL {{
  WITH row
  MERGE (n:KgNode {{id: row.`id:ID`}})
  SET n.local_id = row.local_id,
      n.name     = row.name,
      n.layer    = row.layer,
      n.label    = row.label,
      n.group    = row.`group`,
      n.project  = row.project,
      n.plane    = row.plane,
      n.props    = row.props
{kinds}
}} IN TRANSACTIONS OF 1000 ROWS;

// ---- relationships --------------------------------------------------------
// `apoc.merge.relationship` because the type is data, and Cypher cannot
// parameterise a relationship type. APOC ships with Aura and Desktop; if it is
// unavailable, split edges.csv by kind and write one MERGE per kind instead.
LOAD CSV WITH HEADERS FROM 'file:///{edge_csv}' AS row
CALL {{
  WITH row
  MATCH (a:KgNode {{id: row.`start:START_ID`}})
  MATCH (b:KgNode {{id: row.`end:END_ID`}})
  CALL apoc.merge.relationship(a, row.`kind:TYPE`, {{}},
                               {{props: row.props, kind: row.`kind:TYPE`}}, b)
  YIELD rel
  RETURN count(rel) AS _
}} IN TRANSACTIONS OF 1000 ROWS;

// ---- check ----------------------------------------------------------------
// Run this after loading. The numbers must match what `pf bloom build` printed;
// a short count means rows were rejected and the log will say which.
MATCH (n:KgNode) RETURN 'nodes' AS what, count(n) AS n
UNION ALL
MATCH ()-[r]->() RETURN 'edges' AS what, count(r) AS n;
"""


# -------------------------------------------------------------------- write --

def write(root: str | Path, out: str | Path | None = None) -> tuple[Corpus, list[Path]]:
    """Write the whole export. Returns the corpus and what was written."""
    root = Path(root)
    out = Path(out) if out else root / "docs" / "bloom"
    out.mkdir(parents=True, exist_ok=True)
    corpus = collect(root)

    npath = out / "nodes.csv"
    with npath.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        w.writerow(NODE_HEADER)
        for n in corpus.nodes:
            w.writerow([n["id"], n["local_id"], n["kind"], n["name"], n["layer"],
                        n["label"], n["group"], n["project"], n["plane"],
                        n["props"]])

    epath = out / "edges.csv"
    with epath.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh, quoting=csv.QUOTE_MINIMAL)
        w.writerow(EDGE_HEADER)
        for e in corpus.edges:
            w.writerow([e["start"], e["end"], e["kind"], e["props"]])

    cpath = out / "load.cypher"
    cpath.write_text(load_cypher(), encoding="utf-8")

    ppath = out / "data-platform.bloom-perspective.json"
    ppath.write_text(json.dumps(perspective(corpus), indent=2,
                                ensure_ascii=False) + "\n", encoding="utf-8")

    rpath = out / "README.md"
    rpath.write_text(readme(corpus), encoding="utf-8")

    return corpus, [npath, epath, cpath, ppath, rpath]


def readme(corpus: Corpus) -> str:
    """The half of the export a person reads before touching Neo4j."""
    n, e = len(corpus.nodes), len(corpus.edges)
    projects = "\n".join(
        f"| `{g}/{p}` | {nn:,} | {ee:,} |" for g, p, nn, ee in corpus.projects)
    kinds = "\n".join(
        f"| `{k}` | {c:,} | {PLANE.get(k, '—')} |"
        for k, c in corpus.kinds.items())
    edges = "\n".join(f"| `{k}` | {c:,} |" for k, c in corpus.edge_kinds.items())
    phrases = "\n".join(f"- **{t['text']}**" for t in templates())
    dang = (f"\n> {len(corpus.dangling)} edge(s) were dropped for a missing "
            f"endpoint — see `pf bloom build` output.\n"
            if corpus.dangling else "")

    return f"""# The platform graph, in Neo4j Bloom

Generated by `pf bloom build`. **Do not edit** — regenerate, or these files will
disagree with the graph they claim to describe.

Eight projects each build a knowledge graph and none can see the others, which
is right while you are working on a project and useless when the question spans
the estate. This is all eight, unioned: **{n:,} nodes and {e:,} relationships**.
{dang}
## Load it

1. Copy `nodes.csv` and `edges.csv` into your database's `import/` directory
   (Neo4j Desktop: **⋯ → Open folder → Import**; Aura: use a public URL and
   change the `file:///` prefix in `load.cypher` to it).
2. Run `load.cypher` in Neo4j Browser or `cypher-shell`. It is idempotent —
   a unique constraint on `id` means re-running updates rather than doubles.
3. The last statement prints the counts. They must match the numbers above; a
   short count means rows were rejected and the log says which.
4. In Bloom: **Perspective → Import** and choose
   `data-platform.bloom-perspective.json`.

APOC is required for the relationship load, because the relationship type is
data and Cypher cannot parameterise one. It ships with Desktop and Aura.

## What you get

The perspective is the half that matters. Without it Bloom renders grey circles
captioned by whichever property comes first, and {n:,} nodes drawn that way is
noise.

**Colour is the plane**, the same three the KG Atlas uses — teal for the
physical and analytical layer, violet for the semantic one, slate for
governance. Shade within a plane tracks containment: a Project is darker than
the Models it holds, a Model darker than its Columns.

**`Column` is hidden by default.** It is {corpus.kinds.get('Column', 0):,} of
{n:,} nodes — {100 * corpus.kinds.get('Column', 0) // max(n, 1)}% — and any view
containing it is unreadable. One click in the category list brings it back.

**Ten saved search phrases**, each a question somebody has had to answer by
reading files:

{phrases}

## Ids are qualified, on purpose

`Model:orders` exists in `acme-us` and in `acme-eu`, and they are different
models. Merging on the bare id would weld two sisters' lineage together —
exactly what the isolation rule exists to prevent. Every node id here is
`group/project#local_id`, and the original is kept as `local_id` so a Bloom
result can still be traced back to the project graph it came from.

## Per project

| project | nodes | edges |
|---|--:|--:|
{projects}

## Node kinds

| kind | count | plane |
|---|--:|---|
{kinds}

## Relationship kinds

Direction is a contract: **every edge runs upstream → downstream**, so following
one forwards always answers "what depends on this". `feeds` is named for that
direction — a staging model feeds a mart.

| kind | count |
|---|--:|
{edges}

## Modelled on

[`neo4j-graph-examples/bloom`](https://github.com/neo4j-graph-examples/bloom) —
a loader plus one `.bloom-perspective.json`. Three departures, each deliberate:

| | reference | here | why |
|---|---|---|---|
| data | `data/*.dump` | CSV + Cypher | a dump is unreviewable in a PR, and needs that exact Neo4j version |
| ids | bare | `group/project#id` | eight graphs share an id space; merging fuses sisters |
| props | typed columns | flattened JSON | Neo4j cannot nest; dropping loses more than stringifying |
"""
