"""Capability registry — how a new feature reaches every project.

The platform will keep growing sideways: a GitHub integration, a Slack notifier,
a Snowflake target, an eval runner. Each one wants the same four things, and
without a seam they each get bolted onto `new_project()` until the scaffolder is
the union of every feature anyone ever shipped.

A capability is that seam. It declares what it contributes:

    files      what to write into a project (templated, same `{{token}}` syntax)
    settings   permissions and plugins to merge into .claude/settings.json
    gate       path rules to merge into gate.yaml
    env        credentials it needs, so `pf doctor` can tell you what is missing

and nothing else. Adding a capability is one entry in `CAPABILITIES`; it does not
touch the scaffolder, the CLI, or the gate. Removing one is deleting that entry.

Capabilities are **declarative on purpose**. A capability that could run
arbitrary code at scaffold time would be a plugin system, and a plugin system
inside the thing that enforces the safety gate is a way around the safety gate.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pf.scaffold.generator import render


@dataclass(frozen=True)
class Capability:
    """One optional feature a project can be scaffolded with."""

    name: str
    description: str
    files: dict[str, str] = field(default_factory=dict)
    settings: dict[str, Any] = field(default_factory=dict)
    gate: dict[str, list[str]] = field(default_factory=dict)
    env: tuple[str, ...] = ()
    # Capabilities that must be applied first. Kept explicit so ordering is a
    # declared fact rather than dict-insertion luck.
    requires: tuple[str, ...] = ()


# --------------------------------------------------------------- github -----
GITHUB_WORKFLOW = """\
# GENERATED by `pf new-project --with github`. The merge gate, in CI.
#
# This runs the same `pf impact-gate` a developer's pre-commit hook runs, so a
# change that bypasses the local hook (--no-verify, a web edit, a bot commit)
# still cannot merge without its blast radius being reported.
name: impact-gate ({{project}})

on:
  pull_request:
    paths:
      - "groups/{{group}}/projects/{{project}}/transform/models/**"
      - "groups/{{group}}/projects/{{project}}/src/*/sources/**"

jobs:
  impact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # impact needs the merge base, not a shallow clone
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      # The graph is a build artefact, not a commit: rebuild before gating or the
      # gate reports the blast radius of whatever the last committer had locally.
      - run: uv run pf kg build {{group}} {{project}}
      - name: Blast radius of changed models
        run: |
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }}...HEAD \\
            -- 'groups/{{group}}/projects/{{project}}/transform/models/**/*.sql' \\
            | xargs -r -n1 basename | sed 's/\\.sql$//' | sed 's/^/model:/' | paste -sd, -)
          [ -z "$CHANGED" ] && echo "no model changes" && exit 0
          uv run pf impact-gate {{group}} {{project}} "$CHANGED"
"""

GITHUB_README = """\
# GitHub integration — {{group}}/{{project}}

`pf impact-gate` runs on every PR that touches this project's models or sources.
A change with a breaking blast radius fails the check and names the exposure
owners who need to know.

## What it does not do
It does not open PRs, comment on them, or read repository contents beyond the
diff. Those need a token; this needs none, because it runs inside the repo's own
CI. Add write-scoped automation as a separate capability rather than widening
this one — the whole point of the gate is that it cannot be talked out of a
verdict by the thing it is gating.
"""

CAPABILITIES: dict[str, Capability] = {
    "github": Capability(
        name="github",
        description="Run the impact gate on every pull request touching this project.",
        files={
            ".github/workflows/impact-gate-{{project}}.yml": GITHUB_WORKFLOW,
            "docs/github.md": GITHUB_README,
        },
        settings={
            "permissions": {"allow": ["Bash(gh pr view:*)", "Bash(gh pr diff:*)"]},
        },
        gate={
            # CI config is infrastructure: an agent editing the gate that judges
            # it is the same conflict of interest as editing gate.yaml.
            "denylist": ["**/.github/workflows/**"],
        },
    ),
}


class UnknownCapability(KeyError):
    """Raised for a capability name that is not registered."""


def resolve(names: list[str]) -> list[Capability]:
    """Resolve names to capabilities, dependencies first, each applied once."""
    out: list[Capability] = []
    seen: set[str] = set()

    def visit(name: str, chain: tuple[str, ...] = ()) -> None:
        if name in seen:
            return
        if name in chain:
            raise ValueError(f"capability cycle: {' -> '.join((*chain, name))}")
        if name not in CAPABILITIES:
            raise UnknownCapability(
                f"unknown capability '{name}'. Available: "
                f"{', '.join(sorted(CAPABILITIES)) or '(none)'}")
        cap = CAPABILITIES[name]
        for dep in cap.requires:
            visit(dep, (*chain, name))
        seen.add(name)
        out.append(cap)

    for n in names:
        visit(n)
    return out


def apply(cap: Capability, root: Path, project_dir: Path,
          ctx: dict[str, Any]) -> list[Path]:
    """Write one capability's files and merge its settings. Returns what changed.

    Files are written relative to the *project*, except `.github/**`, which
    belongs to the repository — a workflow only runs from the repo root.
    """
    written: list[Path] = []
    for rel, template in cap.files.items():
        rendered_rel = render(rel, ctx)
        base = root if rendered_rel.startswith(".github/") else project_dir
        target = base / rendered_rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(render(template, ctx))
        written.append(target)

    if cap.settings:
        settings_path = project_dir / ".claude" / "settings.json"
        if settings_path.exists():
            settings = json.loads(settings_path.read_text())
            _merge(settings, cap.settings)
            settings_path.write_text(json.dumps(settings, indent=2) + "\n")
            written.append(settings_path)

    return written


def _merge(base: dict[str, Any], extra: dict[str, Any]) -> None:
    """Deep-merge, appending lists rather than replacing them.

    Replacing would let a capability silently drop a permission or plugin that
    another one added — the failure would show up much later as an agent that
    mysteriously cannot run a command.
    """
    for key, value in extra.items():
        if isinstance(value, dict):
            _merge(base.setdefault(key, {}), value)
        elif isinstance(value, list):
            current = base.setdefault(key, [])
            current.extend(v for v in value if v not in current)
        else:
            base[key] = value


def gate_additions(caps: list[Capability]) -> dict[str, list[str]]:
    """Union of the gate rules a set of capabilities contributes."""
    merged: dict[str, list[str]] = {}
    for cap in caps:
        for section, patterns in cap.gate.items():
            bucket = merged.setdefault(section, [])
            bucket.extend(p for p in patterns if p not in bucket)
    return merged


def missing_env(caps: list[Capability]) -> dict[str, list[str]]:
    """Credentials each capability declares that are not set. For `pf doctor`."""
    import os

    return {
        cap.name: [v for v in cap.env if not os.environ.get(v)]
        for cap in caps
        if any(not os.environ.get(v) for v in cap.env)
    }
