"""The harness map: what wraps an agent in one scope of this repository.

Three scopes, three `HARNESS.md`:

    groups/<g>/HARNESS.md                          what every sister inherits
    groups/<g>/projects/<p>/HARNESS.md             one entity, as an agent meets it
    groups/<g>/projects/<p>/reporting/HARNESS.md   the Evidence report inside it

Not `pf.harness`, which is the per-*tool* layer: it renders the Codex, Cursor,
Gemini, VS Code and OpenCode configs from `.mcp.json` and keeps the scorecard
in `docs/HARNESSES.md` — which harness gets what, repository-wide. This is the
per-*scope* layer: which of that reaches one group, one project and one
report, and everything scoped to it that a repository-wide table cannot say —
this project's settings and hooks, the gate's verdicts on its paths, its
workflow, its loops, its tools. The project map carries the scorecard's rows,
computed for the project, so the two agree by construction.

"Harness" here is everything a person or an agent is wrapped in while working
in that scope, in the order they meet it: what a session is handed on turn one,
what it may read and write, what runs around every edit, what a commit must
pass, what every pull request runs, what runs on a schedule, and what is
recorded. None of it is asserted. Every line is read from the file that
enforces it — `.claude/settings.json`, `gate.yaml` and the capability rules
merged over it, the hook scripts, the project's workflow, the group's
`loops.yaml`, `tools.yaml`, `air.yaml` and `notify.yaml` — or from the
registry that declares it. The gate verdicts are not read from `gate.yaml` at
all: they are computed by calling the function the PreToolUse hook calls, on
representative paths, so the map says what the hook would do rather than what
the policy file appears to say. Those two differ, and the difference is
reported as a gap rather than smoothed over.

Two rules keep it honest across machines. Nothing machine-local goes in: not
whether a tool is installed, which Node is on the path, whether the commit
hook is linked or how fresh the graph is — those are the SessionStart hook's
job, on turn one, on that machine. And nothing that moves without the project
moving: no date, no commit, no count of an ignored file. The files are
compared byte for byte, and anything that differs between a laptop and a CI
runner turns `pf harness check` into a coin toss.

Generated on the same terms as `kg/architecture.md`, and beside it in every
way: written by `pf harness <group> <project>` and by every `pf bootstrap`,
denied to hand edits by the gate, carried by git so a pull request that
enables a tool or silences a loop shows what that did to the harness, in the
diff, next to the change.
"""

from __future__ import annotations

import difflib
import json
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

#: On-demand tier, like the architecture map: read when an agent wants to know
#: what will happen to it here, not loaded into every session.
HARNESS_BUDGET = 4000

FILE = "HARNESS.md"

HEADER = (
    "<!-- GENERATED by `pf harness {scope}`, and by every `pf bootstrap`. "
    "Never hand-edit: the next bootstrap overwrites it, and `pf harness check` "
    "fails on the drift in the meantime. -->"
)

#: What each hook script does, by basename. The map names the script the
#: settings actually declare and looks its effect up here; a script this table
#: does not know is listed with its name and no claim about it.
_EFFECTS: dict[str, str] = {
    "pre_tool_use.py": (
        "writes INTENT, asks the gate, writes DECISION; exit 2 with the rule when denied; "
        "prints the blast radius from `kg/graph.duckdb` for an impact-gated path"
    ),
    "post_tool_use.py": "writes EXECUTION — closes the action INTENT opened",
    "format_edit.py": "formats what was written; refuses anything the gate denies or generated",
    "session_start.sh": "turn-one context: scope, graph state, this module's memory notes, dirty tree, commit gate",
    "session_start.py": "points this session's workflow runs at `logs/workflows/`",
    "notify.sh": "desktop notification and a spoken line when the turn ends or asks",
}

#: The session-layer plugin's hooks, as `platform/toolkits/power-tools/hooks/hooks.json`
#: declares them. Read from that file, not from here; this is the fallback
#: when the file is not in the tree (a bare test skeleton).
_POWER_TOOLS = "power-tools@platform"


# ------------------------------------------------------------------ model ---
@dataclass(frozen=True)
class Verdict:
    """One representative path, judged the way the PreToolUse hook judges it."""

    path: str
    verdict: str  # allow | warn | deny
    rule: str


@dataclass(frozen=True)
class Hook:
    event: str
    matcher: str
    script: str
    effect: str
    source: str


@dataclass(frozen=True)
class Loop:
    name: str
    cadence: str
    autonomy: str
    token_budget: int
    writes: bool
    description: str
    waivers: int
    source: str
    overridden: str


@dataclass(frozen=True)
class ToolRow:
    name: str
    title: str
    summary: str
    source: str
    surface: str
    denies: tuple[str, ...]
    impacts: tuple[str, ...]
    ci_jobs: tuple[str, ...]
    assets: bool
    loops: tuple[str, ...]
    artefacts: tuple[str, ...]
    plugins: tuple[str, ...]


@dataclass(frozen=True)
class Job:
    name: str
    source: str
    when: str


@dataclass(frozen=True)
class Workflow:
    name: str
    jobs: tuple[str, ...]
    when: str


@dataclass(frozen=True)
class Sister:
    name: str
    kind: str
    module: str
    prod: str
    overrides: int
    reporting: bool
    notes: int


@dataclass
class Project:
    """The harness of one project, gathered once."""

    group: str
    project: str
    root: Path
    pdir: Path
    module: str = ""
    kind: str = "entity"
    prod: str = ""
    targets: list[tuple[str, str]] = field(default_factory=list)
    plugins: list[tuple[str, str]] = field(default_factory=list)
    skills: list[tuple[str, str]] = field(default_factory=list)
    mcp: list[tuple[str, str]] = field(default_factory=list)
    mcp_tools: list[str] = field(default_factory=list)
    hot_tools: list[str] = field(default_factory=list)
    by_harness: list[tuple[str, str, str, str]] = field(default_factory=list)
    local_servers: list[str] = field(default_factory=list)
    deny: list[str] = field(default_factory=list)
    ask: list[str] = field(default_factory=list)
    allow: list[str] = field(default_factory=list)
    hooks: list[Hook] = field(default_factory=list)
    verdicts: list[Verdict] = field(default_factory=list)
    contributions: list[tuple[str, tuple[str, ...], tuple[str, ...]]] = field(default_factory=list)
    max_files: int = 0
    block_on: str = ""
    platform_denied: list[str] = field(default_factory=list)
    workflow: str = ""
    jobs: list[Job] = field(default_factory=list)
    repo_workflows: list[Workflow] = field(default_factory=list)
    filtered_workflows: list[str] = field(default_factory=list)
    loops: list[Loop] = field(default_factory=list)
    disabled: list[tuple[str, str]] = field(default_factory=list)
    loop_memory: int = 0
    tools: list[ToolRow] = field(default_factory=list)
    caps: list[str] = field(default_factory=list)
    policies: list[str] = field(default_factory=list)
    notes: int = 0
    group_notes: int = 0
    adrs: int = 0
    evals: int = 0
    docs: int = 0
    sources: int = 0
    exposures: int = 0
    air_baseline: int = 0
    air_accepted: int = 0
    notify: list[tuple[str, str]] = field(default_factory=list)
    daily_tokens: int | None = None
    stages: list[tuple[str, str, tuple[str, ...]]] = field(default_factory=list)
    reporting: bool = False
    graph: bool = False
    gaps: list[str] = field(default_factory=list)


@dataclass
class Group:
    """What every sister of one group inherits, gathered once."""

    name: str
    root: Path
    gdir: Path
    display_name: str = ""
    domain: str = ""
    lifecycle: str = ""
    tier: str = ""
    team: str = ""
    residency: str = ""
    retention_days: int | None = None
    erasure_sla_days: int | None = None
    daily_tokens: int | None = None
    tools: list[tuple[str, str]] = field(default_factory=list)
    loops: list[Loop] = field(default_factory=list)
    disabled: list[tuple[str, str]] = field(default_factory=list)
    air_baseline: int = 0
    air_accepted: int = 0
    notify: list[tuple[str, str]] = field(default_factory=list)
    classes: list[str] = field(default_factory=list)
    extension: bool = False
    macros: int = 0
    seeds: int = 0
    shared_tests: int = 0
    package: str = ""
    skills: list[tuple[str, str]] = field(default_factory=list)
    notes: int = 0
    evals: int = 0
    sisters: list[Sister] = field(default_factory=list)
    verdicts: list[Verdict] = field(default_factory=list)
    platform_denied: list[str] = field(default_factory=list)
    gaps: list[str] = field(default_factory=list)


@dataclass
class Report:
    """The Evidence report of one project, as a subproject with its own harness."""

    group: str
    project: str
    root: Path
    pdir: Path
    module: str = ""
    evidence: str = ""
    node: str = ""
    source_type: str = ""
    source_file: str = ""
    generated: list[tuple[str, str]] = field(default_factory=list)
    owned: list[str] = field(default_factory=list)
    metric_pages: int = 0
    extracts: int = 0
    exposures: int = 0
    rules: list[str] = field(default_factory=list)
    skills: list[tuple[str, str]] = field(default_factory=list)
    toolkits: list[str] = field(default_factory=list)
    plugin: bool = False
    allow: list[str] = field(default_factory=list)
    verdicts: list[Verdict] = field(default_factory=list)
    surface: str = ""
    start: str = ""
    loop: Loop | None = None
    gaps: list[str] = field(default_factory=list)


# ---------------------------------------------------------------- readers ---
def _json(path: Path) -> dict[str, Any]:
    try:
        d = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return d if isinstance(d, dict) else {}


def _yaml(path: Path) -> dict[str, Any]:
    try:
        d = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError):
        return {}
    return d if isinstance(d, dict) else {}


def _tracked(base: Path) -> set[str] | None:
    """Paths git tracks or has staged under `base`, relative to it; None outside a repo.

    Same rule as the architecture map: a count that includes an untracked file
    is a count that differs between the laptop that made the file and the
    runner that checks the map.
    """
    from pf.gitenv import git_env

    proc = subprocess.run(
        ["git", "ls-files", "--cached", "--", "."],
        cwd=str(base),
        env=git_env(),
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        return None
    return {line.strip() for line in proc.stdout.splitlines() if line.strip()}


def _glob_re(pattern: str) -> re.Pattern[str]:
    """A path glob as a regex: `*` stops at `/`, `**` does not.

    `fnmatch` lets `*` cross a slash, so `pages/*.md` matched every page under
    `pages/metrics/` too and the report's "yours" list named every generated
    page. This is the glob the rest of the platform means.
    """
    out, i = [], 0
    while i < len(pattern):
        c = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif c == "*":
            out.append("[^/]*")
            i += 1
        elif c == "?":
            out.append("[^/]")
            i += 1
        elif c == "[":
            j = pattern.find("]", i)
            if j == -1:
                out.append(re.escape(c))
                i += 1
            else:
                body = pattern[i + 1 : j]
                body = "^" + body[1:] if body.startswith("!") else body
                out.append(f"[{body}]")
                i = j + 1
        else:
            out.append(re.escape(c))
            i += 1
    return re.compile("^" + "".join(out) + "$")


def _glob(base: Path, pattern: str, tracked: set[str] | None) -> list[str]:
    """Relative paths under `base` matching `pattern`, tracked where there is a repo."""
    rx = _glob_re(pattern)
    if tracked is not None:
        return sorted(p for p in tracked if rx.match(p))
    if not base.is_dir():
        return []
    return sorted(
        str(p.relative_to(base)) for p in base.rglob("*") if p.is_file() and rx.match(str(p.relative_to(base)))
    )


def _count(base: Path, pattern: str, tracked: set[str] | None) -> int:
    return len(_glob(base, pattern, tracked))


def _first(base: Path, pattern: str, tracked: set[str] | None, fallback: str) -> str:
    found = _glob(base, pattern, tracked)
    return found[0] if found else fallback


_FRONT = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)


def _skills(skills_dir: Path) -> list[tuple[str, str]]:
    """(name, description) of every skill under a directory, from its frontmatter."""
    out = []
    if not skills_dir.is_dir():
        return out
    for skill in sorted(skills_dir.glob("*/SKILL.md")):
        m = _FRONT.match(skill.read_text(encoding="utf-8"))
        meta = _yaml_text(m.group(1)) if m else {}
        out.append((str(meta.get("name") or skill.parent.name), str(meta.get("description") or "")))
    return out


def _yaml_text(text: str) -> dict[str, Any]:
    try:
        d = yaml.safe_load(text)
    except yaml.YAMLError:
        return {}
    return d if isinstance(d, dict) else {}


def _rule_heads(rules: Path) -> list[str]:
    """The bold head of every rule in a toolkit's RULES.md."""
    if not rules.is_file():
        return []
    return [m.group(1) for m in re.finditer(r"^- \*\*(.+?)\*\*", rules.read_text(encoding="utf-8"), re.MULTILINE)]


def _notes(module_dir: Path) -> int:
    d = module_dir / ".memory" / "notes"
    return len([p for p in d.glob("*.md") if p.name != "README.md"]) if d.is_dir() else 0


def _list(raw: Any) -> list[Any]:
    return raw if isinstance(raw, list) else []


# ----------------------------------------------------------------- policy ---
def _policy(root: Path) -> dict[str, Any]:
    try:
        from pf.loops.gate import load_policy

        return load_policy(root)
    except Exception:  # noqa: BLE001 — a broken gate must not stop the map from saying so
        return {}


def _registry() -> tuple[dict[str, Any], dict[str, Any]]:
    """Capabilities (tools' included) and tools, by name. Empty when the registry is broken."""
    caps: dict[str, Any] = {}
    tools: dict[str, Any] = {}
    try:
        from pf.capabilities import CAPABILITIES
        from pf.tools import all_tools, register_capabilities

        register_capabilities()
        caps = dict(CAPABILITIES)
        tools = dict(all_tools())
    except Exception:  # noqa: BLE001
        pass
    return caps, tools


def _contributions(caps: dict[str, Any], tools: dict[str, Any]) -> list[tuple[str, tuple[str, ...], tuple[str, ...]]]:
    """Who adds which gate rules: (contributor, denies, impact-gates), sorted."""
    out = []
    for name in sorted(caps):
        gate = getattr(caps[name], "gate", {}) or {}
        denies = tuple(_list(gate.get("denylist")))
        impacts = tuple(_list(gate.get("impact_required")))
        if denies or impacts:
            label = f"tool `{name}`" if name in tools else f"capability `{name}`"
            out.append((label, denies, impacts))
    return out


def _verdict(root: Path, rel: str, *, in_project: bool) -> Verdict:
    try:
        from pf.loops.gate import check_path

        r = check_path(rel, root, in_project=in_project)
        return Verdict(rel, r.verdict, r.rule)
    except Exception:  # noqa: BLE001
        return Verdict(rel, "unknown", "gate not importable")


def _probes(p: Project, tracked: set[str] | None) -> list[str]:
    """Representative paths of this project, real where one exists."""
    b, m = p.pdir, p.module
    return [
        _first(b, f"src/{m}/sources/[!_]*.py", tracked, f"src/{m}/sources/example.py"),
        "contracts/annotations.yaml",
        _first(b, "transform/models/marts/**/*.sql", tracked, "transform/models/marts/example.sql"),
        _first(b, "transform/models/**/*.yml", tracked, "transform/models/marts/_marts__models.yml"),
        "transform/macros/example.sql",
        "transform/tests/expectations/example.yml",
        "transform/recce.yml",
        "transform/recce_state.json",
        "kg/graph.duckdb",
        "kg/context_card.md",
        "kg/architecture.md",
        FILE,
        "mdl/mdl.json",
        "catalog/openmetadata.json",
        "governance/policy.yaml",
        "governance/air-register.md",
        "air.yaml",
        "reporting/pages/index.md",
        "reporting/queries/metrics/example.sql",
        "evals/cases/example.json",
        "evals/cases/generated/example.json",
        "CLAUDE.md",
        f"data/{m}.duckdb",
        f"data/{m}.quack.json",
        ".dlt/secrets.toml",
        "logs/trace/example.jsonl",
    ]


#: Repo-relative paths a project session also meets. Judged with the project's
#: `in_project=True`, which is what makes `platform_denylist` apply.
_REPO_PROBES = ("platform/src/pf/cli.py", "vendor/example/README.md", "gate.yaml")


def _hooks(settings: dict[str, Any], root: Path, source: str) -> list[Hook]:
    out = []
    for event, entries in sorted((settings.get("hooks") or {}).items()):
        for entry in _list(entries):
            matcher = str(entry.get("matcher") or "*")
            for h in _list(entry.get("hooks")):
                cmd = str(h.get("command") or "")
                # The script, not its last argument: `notify.sh stop` is notify.sh.
                words = [Path(w).name for w in cmd.replace('"', "").split()]
                scripts = [w for w in words if w.endswith((".py", ".sh"))]
                script = scripts[-1] if scripts else (words[-1] if words else "")
                out.append(Hook(event, matcher, script, _EFFECTS.get(script, ""), source))
    return out


def _plugin_hooks(root: Path) -> list[Hook]:
    return _hooks(
        _json(root / "platform" / "toolkits" / "power-tools" / "hooks" / "hooks.json"), root, "power-tools plugin"
    )


def _loops(root: Path, group: str, tools: dict[str, Any]) -> tuple[list[Loop], list[tuple[str, str]]]:
    try:
        from pf.loops import config
        from pf.loops.registry import SPECS
    except Exception:  # noqa: BLE001
        return [], []

    owner: dict[str, str] = {}
    for name in sorted(tools):
        try:
            hook = tools[name].hook("loops")
            if hook is not None:
                owner.update(dict.fromkeys(hook(), f"tool `{name}`"))
        except Exception:  # noqa: BLE001 — a broken loop hook is that tool's problem
            continue

    try:
        specs = config.resolve(root, group)
        overrides = config.overrides(root, group)
        disabled = config.disabled(root, group)
    except Exception:  # noqa: BLE001 — a malformed loops.yaml is reported by `pf loop list`
        specs, overrides, disabled = dict(SPECS.items()), {}, {}

    rows = []
    for name in sorted(specs):
        s = specs[name]
        o = overrides.get(name)
        changed = []
        if o is not None:
            for f in ("cadence", "token_budget", "autonomy"):
                if getattr(o, f, None) not in (None, ""):
                    changed.append(f.replace("_", " "))
        source = "registry" if name in SPECS else owner.get(name, "registry")
        rows.append(
            Loop(
                name,
                str(s.cadence),
                str(s.autonomy),
                int(s.token_budget or 0),
                bool(s.writes),
                str(s.description),
                len(getattr(o, "waivers", ()) or ()) if o else 0,
                source,
                ", ".join(changed),
            )
        )
    return rows, sorted(disabled.items())


def _workflow(root: Path, project: str, caps: dict[str, Any], tools: dict[str, Any]) -> tuple[str, list[Job]]:
    rel = f".github/workflows/{project}.yml"
    doc = _yaml(root / rel)
    jobs = doc.get("jobs") if isinstance(doc.get("jobs"), dict) else {}
    if not jobs:
        return "", []
    by_job = {}
    for name in sorted(caps):
        for job in getattr(caps[name], "ci_jobs", {}) or {}:
            by_job.setdefault(job, f"tool `{name}`" if name in tools else f"capability `{name}`")
    out = []
    for job in jobs:
        spec = jobs[job] if isinstance(jobs[job], dict) else {}
        cond = str(spec.get("if") or "")
        outputs = list(dict.fromkeys(re.findall(r"outputs\.(\w+)", cond)))
        if not cond:
            when = "always"
        elif outputs == ["any"]:
            when = "any change in the project"
        else:
            when = " or ".join(outputs) + " changed"
        if job == "changes":
            source, when = "the path filter", "always"
        else:
            source = by_job.get(job, "the workflow")
        out.append(Job(str(job), source, when))
    return rel, out


def _repo_workflows(root: Path, projects: set[str]) -> tuple[list[Workflow], list[str]]:
    """Workflows every pull request runs, and those a path filter narrows."""
    every, filtered = [], []
    wdir = root / ".github" / "workflows"
    if not wdir.is_dir():
        return every, filtered
    for f in sorted(wdir.glob("*.yml")):
        if f.stem in projects or f.stem == "agent-context":
            continue
        doc = _yaml(f)
        on = doc.get("on", doc.get(True))
        if not isinstance(on, dict) or "pull_request" not in on:
            continue
        pr = on.get("pull_request") or {}
        if isinstance(pr, dict) and pr.get("paths"):
            filtered.append(f.stem)
            continue
        when = "every pull request" + (" · daily" if "schedule" in on else "")
        jobs = tuple(str(j) for j in (doc.get("jobs") or {}))
        every.append(Workflow(f.stem, jobs, when))
    return every, filtered


def _stages() -> list[tuple[str, str, tuple[str, ...]]]:
    try:
        from pf.onboard.ladder import STAGES

        return [(s.name, s.title, tuple(s.owns)) for s in STAGES]
    except Exception:  # noqa: BLE001
        return []


def _mcp_tools() -> tuple[list[str], list[str]]:
    try:
        from pf.mcp.server import HOT_TOOLS, TOOLS

        return sorted(TOOLS), list(HOT_TOOLS)
    except Exception:  # noqa: BLE001
        return [], []


def _tool_rows(root: Path, group: str, project: str, tools: dict[str, Any]) -> list[ToolRow]:
    try:
        from pf.tools import resolve

        cfg = resolve(root, group, project) if project else resolve(root, group, "")
    except Exception:  # noqa: BLE001
        return []
    rows = []
    for name in sorted(cfg):
        c = cfg[name]
        if not c.enabled or name not in tools:
            continue
        t = tools[name]
        cap = t.capability
        gate = (getattr(cap, "gate", {}) or {}) if cap else {}
        loops: tuple[str, ...] = ()
        try:
            hook = t.hook("loops")
            loops = tuple(sorted(hook())) if hook is not None else ()
        except Exception:  # noqa: BLE001
            loops = ()
        surface = f"port {t.surface.port}{t.surface.path}" if t.surface else ""
        rows.append(
            ToolRow(
                name,
                t.title,
                t.summary,
                c.source,
                surface,
                tuple(_list(gate.get("denylist"))),
                tuple(_list(gate.get("impact_required"))),
                tuple(sorted(getattr(cap, "ci_jobs", {}) or {})) if cap else (),
                bool(t.dagster),
                loops,
                tuple(getattr(t.dbt, "artefacts", ()) or ()) if t.dbt else (),
                tuple(sorted((getattr(cap, "settings", {}) or {}).get("enabledPlugins") or {})) if cap else (),
            )
        )
    return rows


def _present_caps(root: Path, pdir: Path, group: str, project: str, caps: dict[str, Any]) -> list[str]:
    """Capabilities this project has, judged by their own files, as the architecture map does."""
    try:
        from pf.capabilities import render
    except Exception:  # noqa: BLE001
        return []
    ctx = {"group": group, "project": project, "module": project.replace("-", "_")}
    out = []
    for name in sorted(caps):
        files = getattr(caps[name], "files", {}) or {}
        if not files:
            continue
        targets = [(root if rel.startswith(".github/") else pdir) / render(rel, ctx) for rel in files]
        if all(t.is_file() for t in targets):
            out.append(name)
    return out


def _policies(caps: dict[str, Any], present: list[str]) -> list[str]:
    out = []
    for name in present:
        for p in getattr(caps.get(name), "policies", ()) or ():
            pid = p.get("id") or p.get("name")
            if pid:
                out.append(str(pid))
    return sorted(set(out))


def _targets(pdir: Path) -> list[tuple[str, str]]:
    doc = _yaml(pdir / "transform" / "profiles.yml")
    for value in doc.values():
        if isinstance(value, dict) and isinstance(value.get("outputs"), dict):
            return [
                (str(n), str(spec.get("type") or "")) for n, spec in value["outputs"].items() if isinstance(spec, dict)
            ]
    return []


def _air(path: Path) -> tuple[int, int]:
    doc = _yaml(path)
    return len(_list(doc.get("baseline"))), len(_list(doc.get("accepted")))


def _notify(gdir: Path) -> list[tuple[str, str]]:
    doc = _yaml(gdir / "notify.yaml")
    ch = doc.get("channels") if isinstance(doc.get("channels"), dict) else {}
    return sorted((str(k), str(v)) for k, v in ch.items())


def _manifest(root: Path, group: str) -> Any:
    try:
        from pf import groups as manifests

        if manifests.exists(root, group):
            return manifests.load(root, group)
    except Exception:  # noqa: BLE001 — a malformed manifest is `pf group verify`'s to report
        return None
    return None


def _projects_in(gdir: Path) -> list[str]:
    pdir = gdir / "projects"
    if not pdir.is_dir():
        return []
    return sorted(p.name for p in pdir.iterdir() if p.is_dir() and not p.name.startswith("."))


def _by_harness(p: Project, power_tools: bool) -> list[tuple[str, str, str, str]]:
    """The scorecard's rows, as they hold in this project.

    `pf.harness.HARNESSES` says what each tool gets repository-wide. Two of
    its cells are decided per project: Claude Code's pre-tool gate exists only
    where this project's settings declare the hook, and its graph is the root
    `.mcp.json` plus whatever this project's own `.mcp.json` adds — servers the
    other harnesses' configs, rendered from the root file, never see.
    """
    try:
        from pf.harness import HARNESSES
    except Exception:  # noqa: BLE001 — the scorecard is optional to the map
        return []
    gated = any(h.event == "PreToolUse" and h.script == "pre_tool_use.py" for h in p.hooks)
    rows = []
    for h in HARNESSES:
        if h.name == "Claude Code":
            graph = (
                "`.mcp.json` + power-tools plugin" if power_tools else "`.mcp.json`; no plugin, so no `pf` server"
            ) + (" + this project's " + ", ".join(f"`{s}`" for s in p.local_servers) if p.local_servers else "")
            gate = (
                "hook — `pre_tool_use.py` on every Edit/Write"
                if gated
                else "**none — this project's settings declare no hook**"
            )
            rows.append((h.name, "`CLAUDE.md` + this project's hooks", graph, gate))
        else:
            rows.append((h.name, h.entry, h.graph, h.pre_tool_gate))
    return rows


# ----------------------------------------------------------------- gather ---
def gather_project(root: str | Path, group: str, project: str) -> Project:
    """Everything the project map asserts, read from this project, its group and the registry."""
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    gdir = root / "groups" / group
    p = Project(group, project, root, pdir)
    p.module = project.replace("-", "_")
    p.kind = "roll-up" if project.endswith("-rollup") else "entity"
    tracked = _tracked(pdir) if pdir.is_dir() else set()

    p.targets = _targets(pdir)
    p.prod = next((t for n, t in p.targets if n == "prod"), "")

    settings = _json(pdir / ".claude" / "settings.json")
    p.plugins = sorted((k.split("@", 1)[0], k.split("@", 1)[1]) for k in (settings.get("enabledPlugins") or {}))
    perms = settings.get("permissions") or {}
    p.deny = [str(x) for x in _list(perms.get("deny"))]
    p.ask = [str(x) for x in _list(perms.get("ask"))]
    p.allow = [str(x) for x in _list(perms.get("allow"))]
    p.hooks = _hooks(settings, root, "this project's settings")
    power_tools = any(f"{a}@{b}" == _POWER_TOOLS for a, b in p.plugins)
    if power_tools:
        p.hooks += _plugin_hooks(root)
        p.mcp.append(("pf", "power-tools plugin · `pf mcp`, scoped to this project by `PF_PROJECT_DIR`"))
        p.mcp_tools, p.hot_tools = _mcp_tools()
    for name in sorted(_json(pdir / ".mcp.json").get("mcpServers") or {}):
        p.mcp.append((str(name), "this project's `.mcp.json`"))
        p.local_servers.append(str(name))
    p.skills = _skills(gdir / ".claude" / "skills")
    p.by_harness = _by_harness(p, power_tools)

    caps, tools = _registry()
    policy = _policy(root)
    p.contributions = _contributions(caps, tools)
    p.max_files = int(policy.get("maxFiles") or 0)
    p.block_on = str(policy.get("blockOn") or "")
    p.platform_denied = [str(x) for x in _list(policy.get("platform_denylist"))]
    prefix = f"groups/{group}/projects/{project}/"
    p.verdicts = [_verdict(root, prefix + rel, in_project=True) for rel in _probes(p, tracked)]
    p.verdicts += [_verdict(root, rel, in_project=True) for rel in _REPO_PROBES]

    p.workflow, p.jobs = _workflow(root, project, caps, tools)
    all_projects = {q for g in (root / "groups").glob("*/projects/*") if g.is_dir() for q in [g.name]}
    p.repo_workflows, p.filtered_workflows = _repo_workflows(root, all_projects)
    p.loops, p.disabled = _loops(root, group, tools)
    mem = _yaml(pdir / "decisions" / "loop-memory.yaml")
    p.loop_memory = len(_list(mem.get("entries")))
    p.tools = _tool_rows(root, group, project, tools)
    p.caps = _present_caps(root, pdir, group, project, caps)
    p.policies = _policies(caps, p.caps)

    p.notes = _notes(pdir)
    p.group_notes = _notes(gdir)
    p.adrs = _count(pdir, "decisions/ADR-*.md", tracked)
    p.evals = _count(pdir, "evals/cases/*.json", tracked)
    p.docs = _count(pdir, "docs/*.md", tracked)
    p.sources = _count(pdir, f"src/{p.module}/sources/[!_]*.py", tracked)
    exposures = _yaml(pdir / "transform" / "models" / "_reporting__exposures.yml")
    p.exposures = len(_list(exposures.get("exposures")))
    p.air_baseline, p.air_accepted = _air(pdir / "air.yaml")
    p.notify = _notify(gdir)
    m = _manifest(root, group)
    p.daily_tokens = getattr(m, "daily_tokens", None) if m else None
    p.stages = _stages()
    p.reporting = (pdir / "reporting").is_dir()
    p.graph = "kg/graph.json" in (tracked or set()) or (tracked is None and (pdir / "kg" / "graph.json").is_file())
    p.gaps = _project_gaps(p, power_tools)
    return p


def _project_gaps(p: Project, power_tools: bool) -> list[str]:
    """What this harness does not do, derived from what it declares."""
    gaps = []
    if not any(h.event == "PreToolUse" and h.script == "pre_tool_use.py" for h in p.hooks):
        gaps.append(
            "**No edit gate.** `.claude/settings.json` declares no PreToolUse hook running "
            "`platform/hooks/pre_tool_use.py`: nothing denies a write to a secret or a generated "
            "file before it lands, and no INTENT or DECISION is recorded. `pf bootstrap` restores it."
        )
    if not any(h.event == "PostToolUse" and h.script == "post_tool_use.py" for h in p.hooks):
        gaps.append(
            "**EXECUTION (stage 03) is not declared here.** Neither this project's "
            "`.claude/settings.json` nor the plugin runs `platform/hooks/post_tool_use.py` after a "
            "tool call, so an action INTENT opens is closed only when the gate blocks it, and "
            "`pf provenance verify` reports the rest as dangling. The repository root's settings do "
            "declare that hook; a session opened here with `pf work` reads this file, not that one."
        )
    if not power_tools:
        gaps.append(
            "**No `power-tools` plugin.** Without it there is no `pf` MCP server — `kg_search`, "
            "`impact_analysis` and the rest do not exist in this session — and no session-start, "
            "format or notify hook."
        )
    if not any("projects/**" in d or "../" in d for d in p.deny):
        gaps.append(
            "**Sisters are readable.** `permissions.deny` names no sister or other group; the "
            "isolation `AGENTS.md` §1 describes is discipline only here."
        )
    if not p.graph:
        gaps.append(
            "**No knowledge graph is tracked** (`kg/graph.json`). The impact gate is inert on every "
            "machine that has not run `pf kg build`, and the SessionStart hook says so on turn one."
        )
    if not p.workflow:
        gaps.append(
            f"**No CI workflow.** `.github/workflows/{p.project}.yml` does not exist; nothing judges "
            "a pull request against this project. `pf bootstrap` composes one from the capabilities."
        )
    paper = [
        v.path.split("/projects/", 1)[-1].split("/", 1)[-1]
        for v in p.verdicts
        if v.verdict == "allow" and v.rule.startswith("allowlist:") and _impact_on_paper(v.path, p)
    ]
    if paper:
        gaps.append(
            "**Impact-gated on paper, allowed in practice:** "
            + ", ".join(f"`{x}`" for x in paper)
            + ". `autoMergeAllowlist` is matched before `impact_required`, so the hook allows the edit "
            "and prints no blast radius, and the commit gate runs no impact analysis on it. Only CI's "
            "`impact-gate` job judges the change, and only for models and sources."
        )
    carried = [
        v.path.split("/projects/", 1)[-1].split("/", 1)[-1] if "/projects/" in v.path else v.path
        for v in p.verdicts
        if v.rule == "denylist_except"
    ]
    if carried:
        gaps.append(
            "**Generated, and hand-editable:** "
            + ", ".join(f"`{x}`" for x in carried)
            + ". `denylist_except` is matched before `denylist`, so the hook allows the edit; only the "
            "drift check in CI (`architecture`, `pf harness check`) catches a hand edit, after the fact."
        )
    if not p.evals:
        gaps.append(
            "**No eval case of this project's own.** `evals/cases/` holds nothing hand-written, so "
            "nothing checks that an agent still answers this entity's questions correctly. "
            "`pf evals-gen` grounds the toolkit templates; the cases that matter are written by hand."
        )
    if p.reporting and not any(f"{a}@{b}" == "evidence-bi@platform" for a, b in p.plugins):
        gaps.append(
            "**`reporting/` exists but the `evidence-bi` plugin is off**, so the reporting rules and "
            "the dashboard skills are not loaded in this session."
        )
    return gaps


def _impact_on_paper(rel: str, p: Project) -> bool:
    """Would `impact_required` have matched this path, had the allowlist not won?"""
    policy = _policy(p.root)
    try:
        from pf.loops.gate import _match

        return _match(rel, _list(policy.get("impact_required"))) is not None
    except Exception:  # noqa: BLE001
        return False


def gather_group(root: str | Path, group: str) -> Group:
    root = Path(root)
    gdir = root / "groups" / group
    g = Group(group, root, gdir)
    tracked = _tracked(gdir) if gdir.is_dir() else set()
    m = _manifest(root, group)
    if m is not None:
        g.display_name, g.domain, g.lifecycle, g.tier = m.display_name, m.domain, m.lifecycle, m.tier
        g.team = m.owner.team
        g.residency, g.retention_days, g.erasure_sla_days = (
            m.data.residency,
            m.data.retention_days,
            m.data.erasure_sla_days,
        )
        g.daily_tokens = m.daily_tokens
    _caps, tools = _registry()
    g.tools = [(r.name, r.title) for r in _tool_rows(root, group, "", tools)]
    g.loops, g.disabled = _loops(root, group, tools)
    g.air_baseline, g.air_accepted = _air(gdir / "air.yaml")
    g.notify = _notify(gdir)
    inst = _yaml(gdir / "ontology" / "instance.yaml")
    g.classes = [str(c) for c in _list(inst.get("classes"))]
    g.extension = (gdir / "ontology" / "extension.yaml").is_file()
    g.macros = _count(gdir, "shared/transform/macros/*.sql", tracked)
    g.seeds = _count(gdir, "shared/transform/seeds/*.csv", tracked)
    g.shared_tests = _count(gdir, "shared/transform/tests/*.sql", tracked)
    pkgs = sorted((gdir / "shared" / "python" / "src").glob("*/__init__.py"))
    g.package = pkgs[0].parent.name if pkgs else ""
    g.skills = _skills(gdir / ".claude" / "skills")
    g.notes = _notes(gdir)
    g.evals = _count(gdir, "evals/*.json", tracked)
    policy = _policy(root)
    g.platform_denied = [str(x) for x in _list(policy.get("platform_denylist"))]
    for name in _projects_in(gdir):
        pdir = gdir / "projects" / name
        targets = dict(_targets(pdir))
        overrides = _yaml(pdir / "tools.yaml").get("tools") or {}
        g.sisters.append(
            Sister(
                name,
                "roll-up" if name.endswith("-rollup") else "entity",
                name.replace("-", "_"),
                targets.get("prod", ""),
                len(overrides) if isinstance(overrides, dict) else 0,
                (pdir / "reporting").is_dir(),
                _notes(pdir),
            )
        )
    prefix = f"groups/{group}/"
    probes = [
        "tools.yaml",
        "loops.yaml",
        "air.yaml",
        "notify.yaml",
        "group.yaml",
        "ontology/instance.yaml",
        "ontology/extension.yaml",
        "shared/transform/macros/example.sql",
        "shared/transform/seeds/example.csv",
        ".claude/skills/example/SKILL.md",
        "kg/group_card.md",
        FILE,
        "loop-ledger.json",
        "evals/example.json",
        ".memory/notes/example.md",
        "projects/example/CLAUDE.md",
    ]
    # A session opened in the group directory is not "in a project", which is
    # exactly what the platform rule keys on — so it is judged the way the hook
    # would judge it there, and the consequence is reported below.
    g.verdicts = [_verdict(root, prefix + rel, in_project=False) for rel in probes]
    g.verdicts += [_verdict(root, rel, in_project=False) for rel in _REPO_PROBES]
    g.gaps = _group_gaps(g)
    return g


def _group_gaps(g: Group) -> list[str]:
    gaps = []
    platform_open = [v.path for v in g.verdicts if v.path.startswith(("platform/", "vendor/")) and v.verdict == "allow"]
    if platform_open:
        gaps.append(
            "**A group session may write shared infrastructure.** `platform_denylist` applies only "
            "when the hook resolves the session to a project; a session opened at `groups/"
            f"{g.name}` resolves to none, so "
            + ", ".join(f"`{x}`" for x in platform_open)
            + " are allowed. Open project work with `pf work`, and platform work at the root."
        )
    if not g.sisters:
        gaps.append("**No sister project.** Nothing here can be checked by anything else.")
    if not g.skills:
        gaps.append(
            "**No group skill.** `.claude/skills/` is empty; the group's domain knowledge is in prose and memory only."
        )
    if not g.classes:
        gaps.append(
            "**No ontology instance.** `ontology/instance.yaml` names no classes; `pf check` has nothing to agree with."
        )
    if g.air_baseline == 0:
        gaps.append(
            "**No AI-control baseline.** `air.yaml` commits to nothing, so `pf air gate` passes by "
            "finding nothing to check. `pf air baseline " + g.name + " <project> --suggest` proposes one."
        )
    return gaps


def gather_report(root: str | Path, group: str, project: str) -> Report:
    root = Path(root)
    pdir = root / "groups" / group / "projects" / project
    rdir = pdir / "reporting"
    r = Report(group, project, root, pdir, module=project.replace("-", "_"))
    tracked = _tracked(rdir) if rdir.is_dir() else set()
    pkg = _json(rdir / "package.json")
    r.evidence = str((pkg.get("dependencies") or {}).get("@evidence-dev/evidence") or "")
    nvmrc = rdir / ".nvmrc"
    r.node = nvmrc.read_text(encoding="utf-8").strip() if nvmrc.is_file() else ""
    conn = _yaml(rdir / "sources" / r.module / "connection.yaml")
    r.source_type = str(conn.get("type") or "")
    r.source_file = str((conn.get("options") or {}).get("filename") or "")
    r.metric_pages = _count(rdir, "pages/metrics/*.md", tracked)
    r.extracts = _count(rdir, f"sources/{r.module}/*.sql", tracked)
    exposures = _yaml(pdir / "transform" / "models" / "_reporting__exposures.yml")
    r.exposures = len(_list(exposures.get("exposures")))
    r.generated = [
        ("`queries/metrics/*.sql`", "one per metric, gitignored — the compiled query every page reads"),
        ("`pages/index.md`, `pages/metrics/*.md`", "one page per metric"),
        (f"`sources/{r.module}/`", "the connection and one column-enumerated extract per MDL model"),
        ("`evidence.config.yaml`", "the validated palette; never re-picked by eye"),
        ("`package.json`, `.gitignore`, `README.md`", "the toolchain and the rules"),
        ("`../transform/models/_reporting__exposures.yml`", "one exposure per page, so impact analysis reaches it"),
    ]
    pages = _glob(rdir, "pages/*.md", tracked)
    r.owned = [p for p in pages if p != "pages/index.md"]
    r.owned += [d for d in _glob(rdir, "pages/*/*.md", tracked) if not d.startswith("pages/metrics/")]
    if (rdir / "components").is_dir():
        r.owned.append("components/")
    toolkit = root / "platform" / "toolkits" / "evidence-bi"
    r.rules = _rule_heads(toolkit / "RULES.md")
    r.skills = _skills(toolkit / "skills")
    _caps, tools = _registry()
    ev = tools.get("evidence")
    if ev is not None:
        layer = getattr(ev, "stack_layer", {}) or {}
        r.toolkits = [str(t) for t in _list(layer.get("toolkits"))]
        if ev.surface:
            r.surface = f"port {ev.surface.port}{ev.surface.path}"
            r.start = " ".join(ev.surface.start).replace("{project_dir}/", "")
    settings = _json(pdir / ".claude" / "settings.json")
    r.plugin = bool((settings.get("enabledPlugins") or {}).get("evidence-bi@platform"))
    allow = [str(x) for x in _list((settings.get("permissions") or {}).get("allow"))]
    r.allow = [a for a in allow if "npm" in a or "pf report" in a or "pf ask" in a]
    loops, _disabled = _loops(root, group, tools)
    r.loop = next((lp for lp in loops if lp.name == "dashboard-coverage"), None)
    prefix = f"groups/{group}/projects/{project}/reporting/"
    probes = [
        "pages/index.md",
        "pages/metrics/example.md",
        "pages/example.md",
        "queries/metrics/example.sql",
        f"sources/{r.module}/connection.yaml",
        f"sources/{r.module}/example.sql",
        "evidence.config.yaml",
        "package.json",
        "components/example.svelte",
        ".evidence/template/example.js",
        "build/index.html",
        "node_modules/example/index.js",
        FILE,
    ]
    r.verdicts = [_verdict(root, prefix + rel, in_project=True) for rel in probes]
    r.gaps = _report_gaps(r)
    return r


def _report_gaps(r: Report) -> list[str]:
    gaps = []
    if not r.plugin:
        gaps.append(
            "**The `evidence-bi` plugin is off** in `.claude/settings.json`: the rules above and "
            "the two skills are not loaded; `pf tool enable evidence` turns it on."
        )
    pages = [v for v in r.verdicts if "/pages/" in v.path and v.verdict == "allow"]
    if pages:
        gaps.append(
            "**A page edit is judged by nothing before CI.** `pf.tools.evidence` impact-gates "
            "`reporting/pages/**`, but `**/*.md` in `autoMergeAllowlist` is matched first, so the "
            "hook allows the edit and prints no blast radius. `pf report audit` is the check that "
            "exists; run it before calling a page done."
        )
    if not r.owned:
        gaps.append(
            "**Every page here is generated.** Nothing under `pages/` is hand-written yet; the "
            "index and one page per metric are what `pf report build` produces, and the narrative "
            "a reader needs lives in the metric `description` or in a page of your own."
        )
    if not r.exposures:
        gaps.append(
            "**No exposure reaches these pages.** `transform/models/_reporting__exposures.yml` is "
            "absent or empty, so impact analysis stops at the marts and a page can go stale without "
            "a warning. `pf report build` writes one exposure per page."
        )
    if not r.source_file:
        gaps.append("**No source connection.** `sources/<module>/connection.yaml` names no warehouse file.")
    return gaps


# ----------------------------------------------------------------- render ---
def _md_table(header: list[str], rows: list[list[str]]) -> list[str]:
    cell = lambda s: s.replace("|", "\\|").replace("\n", " ")  # noqa: E731
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(cell(c) for c in row) + " |" for row in rows]
    return out


def _cmds(allow: list[str]) -> str:
    """`Bash(pf report:*)` → `pf report`, joined."""
    names = []
    for a in allow:
        m = re.match(r"Bash\((.+?)(?::\*)?\)$", a)
        names.append(m.group(1) if m else a)
    return ", ".join(f"`{n}`" for n in sorted(dict.fromkeys(names)))


def _verdict_rows(verdicts: list[Verdict], strip: str) -> list[list[str]]:
    mark = {"deny": "**denied**", "warn": "impact first", "allow": "allowed", "unknown": "?"}
    rows = []
    for v in verdicts:
        rel = v.path[len(strip) :] if strip and v.path.startswith(strip) else v.path
        rule = v.rule
        if ":" in rule:
            section, pat = rule.split(":", 1)
            rule = f"{section} `{pat}`"
        rows.append([f"`{rel}`", mark.get(v.verdict, v.verdict), rule])
    return rows


def _n(n: int, word: str, plural: str = "") -> str:
    return f"{n} {word if n == 1 else (plural or word + 's')}"


def render_project(p: Project) -> str:
    """The project map. Deterministic for a fixed project: no dates, everything sorted."""
    scope = f"{p.group} {p.project}"
    prefix = f"groups/{p.group}/projects/{p.project}/"
    lines = [
        HEADER.format(scope=scope),
        f"# {p.project} — harness",
        "",
        f"**{p.group}** group · {p.kind} · module `{p.module}` · prod `{p.prod or 'unset'}` · "
        f"[the group's harness](../../{FILE})"
        + (f" · [the report's harness](reporting/{FILE})" if p.reporting else ""),
        "",
        (
            "What sits between an agent and this project, in the order it meets it. Every line is read "
            "from the file that enforces it; every gate verdict was computed by the function the "
            "PreToolUse hook calls. Nothing here is machine-local — that is the SessionStart hook's "
            "report, on turn one."
        ),
        "",
        "## 1. Entering",
        "",
        f"`uv run pf work {p.group} {p.project}` opens a session in this directory. Turn one loads:",
        "",
    ]
    lines += _md_table(
        ["loaded", "from", "carrying"],
        [
            [
                "project rules",
                "`CLAUDE.md` → `kg/context_card.md`",
                "business rules the graph cannot encode; the always-on index",
            ],
            ["group rules", "`../../CLAUDE.md` → `../../kg/group_card.md`", "the sister roster; never read a sister"],
            ["the protocol", "`AGENTS.md`", "you are its Session scope (§0); leave a note before you finish (§5)"],
            [
                "memory",
                "`.memory/notes/`",
                f"{_n(p.notes, 'note')} here, {_n(p.group_notes, 'note')} in the group — `pf memory show`",
            ],
        ],
    )
    plat = [a for a, b in p.plugins if b == "platform"]
    other = [f"`{a}@{b}`" for a, b in p.plugins if b != "platform"]
    lines += [
        "",
        f"**Plugins** (`.claude/settings.json`, {len(p.plugins)}): "
        + ", ".join(f"`{a}`" for a in plat)
        + (" from the platform marketplace; " + ", ".join(other) + " from the group's" if other else "")
        + ".",
    ]
    if p.skills:
        lines += [
            "",
            f"**Group skills** ({len(p.skills)}, through the group plugin; the group's map describes them): "
            + ", ".join(f"`{n}`" for n, _d in p.skills)
            + ".",
        ]
    if p.mcp:
        lines += ["", "**MCP servers:**", ""]
        lines += [f"- `{n}` — {s}" for n, s in p.mcp]
        if p.mcp_tools:
            lines += [
                "",
                f"The `pf` server exposes {len(p.mcp_tools)} tools; hot: "
                + ", ".join(f"`{t}`" for t in p.hot_tools)
                + ". Ask the graph before reading files.",
            ]
    if p.by_harness:
        lines += [
            "",
            (
                "**By harness** — `docs/HARNESSES.md`'s rows, as they hold here. *Rule* means nothing checks; "
                "the commit gate is the backstop."
            ),
            "",
        ]
        lines += _md_table(
            ["harness", "entry point", "graph", "pre-tool gate"],
            [[f"**{n}**", e, g, x] for n, e, g, x in p.by_harness],
        )
        if p.local_servers:
            lines += [
                "",
                "This project's own `.mcp.json` adds "
                + ", ".join(f"`{s}`" for s in p.local_servers)
                + " for Claude Code only; the other harnesses' configs are rendered from the root `.mcp.json`.",
            ]
    lines += [
        "",
        "## 2. Reading and writing",
        "",
        "**Denied to read** (`permissions.deny`): " + ", ".join(f"`{d}`" for d in p.deny) + ".",
        "",
        "**Asks first:** " + (_cmds(p.ask) or "nothing") + ".",
        "",
        f"**Allowed without asking** ({len(p.allow)}): " + (_cmds(p.allow) or "nothing") + ".",
        "",
        (
            "**The gate**, as it judges this project: `gate.yaml` plus `gate.capabilities.yaml`, applied "
            "to representative paths (real where the project has them) as a `pf work` session is judged. "
            "*Denied*: the hook exits 2 and the commit gate refuses. *Impact first*: the hook prints the "
            "blast radius and the commit gate runs impact analysis."
        ),
        "",
    ]
    lines += _md_table(["path", "verdict", "by"], _verdict_rows(p.verdicts, prefix))
    lines += [
        "",
        f"A commit may touch at most **{p.max_files} files** (`maxFiles`) and is blocked at severity "
        f"`{p.block_on}` (`blockOn`). In a project session `platform_denylist` also denies "
        + ", ".join(f"`{x}`" for x in p.platform_denied)
        + ": shared infrastructure is changed from the root, never from here.",
    ]
    lines += ["", "## 3. Around every edit, and every commit", ""]
    lines += _md_table(
        ["event", "matcher", "script", "declared in", "effect"],
        [[h.event, f"`{h.matcher}`", f"`{h.script}`", h.source, h.effect] for h in p.hooks],
    )
    lines += [
        "",
        (
            "**Commit:** `.git/hooks/pre-commit` → `platform/hooks/pre_commit.sh` → `pf gate --paths` over "
            "the staged paths: the denylist, `platform_denylist`, `maxFiles`, and impact analysis on every "
            f"impact-gated path, blocking on `{p.block_on}`. Git does not clone hooks; `pf install-hook` "
            "puts it in place."
        ),
        "",
        (
            "**Travels with the change** (`harness_required`): a run that changes this project must leave "
            f"this map, the report's and the group's current, or the commit gate refuses it; `pf harness "
            f"{p.group} {p.project}` regenerates them."
        ),
        "",
        "## 4. Every pull request",
        "",
    ]
    if p.workflow:
        lines += [
            (
                f"`{p.workflow}`, composed by `pf bootstrap` from its capabilities' jobs, narrowed by the "
                "`changes` filter:"
            ),
            "",
        ]
        lines += _md_table(["job", "from", "runs when"], [[f"`{j.name}`", j.source, j.when] for j in p.jobs])
    else:
        lines += [f"No `.github/workflows/{p.project}.yml`."]
    if p.repo_workflows:
        lines += ["", "Repository-wide, whatever the change touches:", ""]
        lines += [f"- `{w.name}` ({w.when}): " + ", ".join(f"`{j}`" for j in w.jobs) for w in p.repo_workflows]
        lines += [
            (
                "- `agent-context` (every pull request): entry points, memory and test indexes, repo map, "
                "guide and these maps are current"
            )
        ]
    if p.filtered_workflows:
        lines += ["", "Only when platform paths change: " + ", ".join(f"`{w}`" for w in p.filtered_workflows) + "."]
    lines += ["", "## 5. On a schedule — the loops", ""]
    lines += [
        (
            f"The registry through `groups/{p.group}/loops.yaml`, which may lower a level, never raise one. "
            "Findings go to `STATE.md`; a proposal becomes a pull request once the loop has earned it."
        ),
        "",
    ]
    lines += _md_table(
        ["loop", "cadence", "level", "budget", "from", "this group changed"],
        [
            [
                f"`{lp.name}`",
                lp.cadence,
                lp.autonomy + (" · writes" if lp.writes else ""),
                f"{lp.token_budget:,}",
                lp.source,
                ", ".join(
                    [*([lp.overridden] if lp.overridden else []), *([_n(lp.waivers, "waiver")] if lp.waivers else [])]
                )
                or "—",
            ]
            for lp in p.loops
        ],
    )
    if p.disabled:
        lines += ["", "Off for this group: " + "; ".join(f"`{n}` — {why}" for n, why in p.disabled) + "."]
    lines += [
        "",
        f"Loop memory: `decisions/loop-memory.yaml`, {_n(p.loop_memory, 'entry', 'entries')}. "
        f"Delivery: `groups/{p.group}/notify.yaml` names "
        + ", ".join(f"`{c}` → `{e}`" for c, e in p.notify)
        + (f". The family's daily token ceiling is {p.daily_tokens:,}." if p.daily_tokens else "."),
        "",
        "## 6. Recorded and judged",
        "",
        (
            "- **Provenance.** The hooks write INTENT, DECISION and EXECUTION into `provenance/` — gitignored, "
            "denied, hash-chained, time-anchored; `pf provenance verify` audits it."
        ),
        (
            f"- **AI controls.** `air.yaml` commits to {_n(p.air_baseline, 'control')} and accepts "
            f"{p.air_accepted}, merged over the group's; `pf air gate {p.group} {p.project}` blocks on a "
            "failing baseline control. The register is generated to `governance/air-register.md`."
        ),
        "- **Policy.** `governance/policy.yaml` layers over the group's and the platform floor and may "
        "only tighten"
        + ("; the capabilities present add " + ", ".join(f"`{x}`" for x in p.policies) if p.policies else "")
        + ".",
        (
            f"- **Evals.** {_n(p.evals, 'hand-written case')} in `evals/cases/`, generated ones gitignored; "
            f"`pf evals {p.group} {p.project}` runs them, `pf evals-gate` on an agent-surface change."
        ),
        f"- **The onboarding ladder.** `pf align {p.group} {p.project}`: "
        + " → ".join(f"`{n}`" for n, _t, _o in p.stages)
        + "; each stage may write only its own globs.",
        f"- **Decisions.** {_n(p.adrs, 'ADR')} in `decisions/`; {_n(p.docs, 'capability page')} in `docs/`.",
        "",
        "## 7. The subprojects, and their harness",
        "",
    ]
    lines += _md_table(
        ["subproject", "where", "what wraps it"],
        [
            [
                "dlt pipeline",
                f"`src/{p.module}/`",
                (
                    f"{_n(p.sources, 'source')}, each `@annotate`d against `contracts/annotations.yaml`; "
                    "`sources/*.py` impact-gated; `.dlt/secrets.toml` unreadable and unwritable; "
                    "`definitions.py` is the Dagster code location"
                ),
            ],
            [
                "dbt project",
                "`transform/`",
                "targets " + ", ".join(f"{n} `{t}`" for n, t in p.targets) + "; `target/` and "
                "`dbt_packages/` denied; "
                + (
                    "bound to its manifest: " + ", ".join(f"`{t.name}`" for t in p.tools if t.artefacts)
                    if any(t.artefacts for t in p.tools)
                    else "no tool bound to its manifest"
                ),
            ],
            [
                "semantic layer",
                "`transform/models/semantic/`",
                (
                    "MetricFlow metrics, projected to `mdl/mdl.json` (denied, carried) by `pf semantic mdl`; "
                    "queried by `mf`, `pf ask` and the `query_metrics` MCP tool"
                ),
            ],
            [
                "knowledge graph",
                "`kg/`",
                (
                    "`graph.json` tracked and `graph.duckdb` denied (`pf kg build`); `context_card.md` denied "
                    "(`pf kg card`); `architecture.md` carried (`pf arch`); CI `kg-current` and `architecture`"
                ),
            ],
            [
                "Evidence report",
                "`reporting/`",
                f"its own [`HARNESS.md`](reporting/{FILE}); {_n(p.exposures, 'exposure')} reach its pages"
                if p.reporting
                else "not enabled — `pf tool enable evidence`",
            ],
            ["evals", "`evals/cases/`", "hand-written cases tracked; `generated/` ignored and denied"],
            [
                "governance",
                "`governance/`, `air.yaml`, `decisions/`",
                (
                    "the policy overlay and the AIR declaration are impact-gated; the register is denied; "
                    "decisions are free to write"
                ),
            ],
            ["memory", "`.memory/notes/`", f"free to write; `pf memory add groups/{p.group}/projects/{p.project} …`"],
        ],
    )
    if p.tools:
        lines += ["", "**Tools enabled**, and what each wires in:", ""]
        for t in p.tools:
            bits = [f"from the {t.source}"]
            if t.denies:
                bits.append(f"denies {len(t.denies)}")
            if t.impacts:
                bits.append(f"impact-gates {len(t.impacts)}")
            if t.ci_jobs:
                bits.append("CI " + ", ".join(f"`{j}`" for j in t.ci_jobs))
            if t.assets:
                bits.append("a Dagster asset")
            if t.loops:
                bits.append("loop " + ", ".join(f"`{x}`" for x in t.loops))
            if t.surface:
                bits.append(f"a dev server on {t.surface}")
            if t.plugins:
                bits.append("plugin " + ", ".join(f"`{x}`" for x in t.plugins))
            lines.append(f"- `{t.name}` — {t.summary} ({'; '.join(bits)})")
    if p.caps:
        lines += ["", "**Capabilities present:** " + ", ".join(f"`{c}`" for c in p.caps) + "."]
    if p.gaps:
        lines += ["", "## Gaps", ""]
        lines += [f"- {g}" for g in p.gaps]
    lines += [
        "",
        "---",
        "",
        (
            f"Regenerate with `pf harness {p.group} {p.project}`; `pf harness check` fails when this file "
            "and the files it is read from disagree."
        ),
    ]
    return "\n".join(lines) + "\n"


def _group_loops_cell(g: Group) -> str:
    changed = []
    for lp in g.loops:
        bits = [lp.overridden] if lp.overridden else []
        if lp.waivers:
            bits.append(_n(lp.waivers, "waiver"))
        if bits:
            changed.append(f"`{lp.name}` ({', '.join(bits)})")
    cell = ", ".join(changed) or "the registry as shipped"
    if g.disabled:
        cell += "; off: " + ", ".join(f"`{n}`" for n, _w in g.disabled)
    return cell


def render_group(g: Group) -> str:
    prefix = f"groups/{g.name}/"
    lines = [
        HEADER.format(scope=g.name),
        f"# {g.name} — harness",
        "",
        (
            f"**{g.display_name or g.name}** · domain `{g.domain or 'unset'}` · lifecycle `{g.lifecycle or 'unset'}` · "
            f"tier `{g.tier or 'unset'}` · owner team `{g.team or 'unset'}` · {_n(len(g.sisters), 'sister')}"
        ),
        "",
        (
            "What every sister project inherits, decided once for the family. A sister may opt out of a "
            "tool, lower a loop's level or commit to more controls; it may not read another sister, and "
            "only the roll-up attaches sister warehouses, read-only."
        ),
        "",
        "## Inherited by every sister",
        "",
    ]
    lines += _md_table(
        ["decision", "file", "effect"],
        [
            [
                "tools",
                "`tools.yaml`",
                (", ".join(f"`{n}`" for n, _t in g.tools) or "none") + " — each sister may set `enabled: false`",
            ],
            ["loops", "`loops.yaml`", _group_loops_cell(g)],
            [
                "AI controls",
                "`air.yaml`",
                f"baseline {g.air_baseline}, accepted {g.air_accepted}; a sister's baseline is a union with this one",
            ],
            ["delivery", "`notify.yaml`", ", ".join(f"`{c}` → `{e}`" for c, e in g.notify) or "no channel"],
            [
                "budget and data",
                "`group.yaml`",
                (f"{g.daily_tokens:,} tokens a day" if g.daily_tokens else "no token ceiling")
                + f"; residency `{g.residency or 'unset'}`"
                + (f", retention {g.retention_days} d" if g.retention_days else "")
                + (f", erasure SLA {g.erasure_sla_days} d" if g.erasure_sla_days else ""),
            ],
            [
                "ontology",
                "`ontology/instance.yaml`" + (" + `extension.yaml`" if g.extension else ""),
                ("classes " + ", ".join(f"`{c}`" for c in g.classes) if g.classes else "no classes")
                + "; validated by `pf check`",
            ],
            [
                "shared dbt",
                "`shared/transform/`",
                (
                    f"{_n(g.macros, 'macro')}, {_n(g.seeds, 'seed')}, {_n(g.shared_tests, 'test')}; "
                    "identical in every sister"
                ),
            ],
            ["shared python", "`shared/python/`", f"`{g.package}`" if g.package else "none"],
            [
                "skills",
                "`.claude/skills/`",
                (", ".join(f"`{n}`" for n, _d in g.skills) if g.skills else "none")
                + f" — the `{g.name}-group` plugin, enabled in every sister's settings",
            ],
            ["memory", "`.memory/notes/`", f"{_n(g.notes, 'note')}; `pf memory add groups/{g.name} …`"],
            ["evals", "`evals/`", f"{_n(g.evals, 'case')} the whole family must pass"],
        ],
    )
    if g.skills:
        lines += ["", "The skills:", ""]
        lines += [f"- `{n}` — {d}" for n, d in g.skills]
    lines += ["", "## The sisters", ""]
    lines += _md_table(
        ["project", "kind", "module", "prod", "tool overrides", "report", "memory", "harness"],
        [
            [
                f"`{s.name}`",
                s.kind,
                f"`{s.module}`",
                f"`{s.prod or 'unset'}`",
                str(s.overrides),
                "yes" if s.reporting else "no",
                str(s.notes),
                f"[`projects/{s.name}/HARNESS.md`](projects/{s.name}/{FILE})",
            ]
            for s in g.sisters
        ],
    )
    lines += [
        "",
        "## The gate, from the group directory",
        "",
        (
            "Judged the way the PreToolUse hook judges a session opened here — which is *not* inside a "
            "project, and that matters for the last rows."
        ),
        "",
    ]
    lines += _md_table(["path", "verdict", "by"], _verdict_rows(g.verdicts, prefix))
    lines += [
        "",
        "`platform_denylist` — " + ", ".join(f"`{x}`" for x in g.platform_denied) + " — applies only "
        "when the session resolves to a project.",
        "",
        (
            "**These maps travel with the change** (`harness_required`): a run that changes a group-level "
            "file must leave every map in the family current, and a run that changes a sister must leave "
            f"the sister's, its report's and this one current. `pf harness {g.name}` regenerates them all."
        ),
    ]
    if g.gaps:
        lines += ["", "## Gaps", ""]
        lines += [f"- {x}" for x in g.gaps]
    lines += [
        "",
        "---",
        "",
        (
            f"Regenerate with `pf harness {g.name}`; every `pf bootstrap` of a sister does too. "
            "`pf harness check` fails on the drift."
        ),
    ]
    return "\n".join(lines) + "\n"


def render_report(r: Report) -> str:
    prefix = f"groups/{r.group}/projects/{r.project}/reporting/"
    lines = [
        HEADER.format(scope=f"{r.group} {r.project}"),
        f"# {r.project} — reporting harness (Evidence)",
        "",
        (
            f"**{r.group}/{r.project}** · Evidence `{r.evidence or 'unpinned'}` · Node `{r.node or 'unpinned'}` "
            f"(`.nvmrc`) · reads `{r.source_type or 'unset'}` at `{r.source_file or 'unset'}` · "
            f"[the project's harness](../{FILE})"
        ),
        "",
        (
            "The report is a subproject with its own runtime, its own generated/owned split and its own "
            "loop. It is a projection of the semantic layer: `dbt marts → MetricFlow metrics → MDL → "
            "queries/metrics/*.sql → pages/*.md`. Nothing here invents a number."
        ),
        "",
        "## Generated and owned",
        "",
        (
            "`pf report build` (also `pf tool evidence build`, the `reporting` bootstrap step and the "
            "`reporting` Dagster asset) rewrites the generated half in full; a stale file for a metric "
            "that no longer exists is removed, not kept."
        ),
        "",
    ]
    lines += _md_table(["generated — never edit", "what it is"], [[a, b] for a, b in r.generated])
    lines += [
        "",
        (
            f"Right now: {_n(r.metric_pages, 'metric page')}, {_n(r.extracts, 'extract')}, "
            f"{_n(r.exposures, 'exposure')} back into dbt."
        ),
        "",
        "**Yours:** " + (", ".join(f"`{o}`" for o in r.owned) if r.owned else "nothing yet") + ". A page you "
        "write reads a compiled metric query; a figure with no metric is a metric pull request, not "
        "page SQL.",
        "",
        "## The rules a session is under",
        "",
    ]
    if r.plugin:
        lines += [
            "The `evidence-bi` plugin is enabled in `../.claude/settings.json`; its `RULES.md` is always on:",
            "",
        ]
    else:
        lines += ["The `evidence-bi` plugin is **not** enabled here; these are its rules, unloaded:", ""]
    lines += [f"- {x}" for x in r.rules]
    if r.skills:
        lines += ["", "Skills:", ""]
        lines += [f"- `{n}` — {d}" for n, d in r.skills]
    if r.toolkits:
        lines += ["", "Toolkits on this layer: " + ", ".join(f"`{t}`" for t in r.toolkits) + "."]
    lines += [
        "",
        "**Allowed without asking:** " + (_cmds(r.allow) or "no reporting verb is pre-allowed") + ".",
        "",
        "## The gate, inside `reporting/`",
        "",
    ]
    lines += _md_table(["path", "verdict", "by"], _verdict_rows(r.verdicts, prefix))
    lines += [
        "",
        (
            "**This map travels with the change** (`harness_required`): a run that changes anything under "
            f"`reporting/` must leave it current — `pf harness {r.group} {r.project}` — or the commit gate "
            "refuses it."
        ),
        "",
        "## Running it",
        "",
    ]
    lines += _md_table(
        ["do", "with"],
        [
            ["regenerate from the semantic layer", f"`pf report build {r.group} {r.project}`"],
            ["score it (errors exit 1)", f"`pf report audit {r.group} {r.project}`"],
            ["ask the same metrics a question", f'`pf ask {r.group} {r.project} "…"`'],
            ["extract, then serve", "`cd reporting && npm install && npm run sources && npm run dev`"],
            ["the dev server `pf ui` → Review embeds", f"{r.surface or 'unset'} — `{r.start or 'unset'}`"],
            ["is the toolchain right", "`pf tool evidence doctor` (Node 20 is the runtime boundary)"],
        ],
    )
    if r.loop is not None:
        lines += [
            "",
            (
                f"**Loop:** `{r.loop.name}` — {r.loop.description} Cadence {r.loop.cadence}, level "
                f"{r.loop.autonomy}, {'writes' if r.loop.writes else 'read-only'}; a score under 90 is a finding."
            ),
        ]
    lines += [
        "",
        (
            "**Dagster:** the `reporting` asset is downstream of every mart its metrics read, so a metric "
            "change shows its pages going stale in the asset graph; the audit score rides on it as metadata."
        ),
        "",
        (
            "**CI:** no job of its own. `impact-gate` runs on models and sources; the exposures "
            "`pf report build` writes are how a model change reaches a page in that report."
        ),
    ]
    if r.gaps:
        lines += ["", "## Gaps", ""]
        lines += [f"- {x}" for x in r.gaps]
    lines += [
        "",
        "---",
        "",
        f"Regenerate with `pf harness {r.group} {r.project}`, which writes this beside the project's map.",
    ]
    return "\n".join(lines) + "\n"


# ------------------------------------------------------------------ paths ---
def group_path(root: str | Path, group: str) -> Path:
    return Path(root) / "groups" / group / FILE


def project_path(root: str | Path, group: str, project: str) -> Path:
    return Path(root) / "groups" / group / "projects" / project / FILE


def report_path(root: str | Path, group: str, project: str) -> Path:
    return Path(root) / "groups" / group / "projects" / project / "reporting" / FILE


@dataclass(frozen=True)
class Scope:
    """One HARNESS.md: where it goes and how it is made."""

    kind: str  # group | project | report
    group: str
    project: str = ""

    @property
    def label(self) -> str:
        return (
            self.group
            if not self.project
            else f"{self.group}/{self.project}" + ("/reporting" if self.kind == "report" else "")
        )

    def path(self, root: str | Path) -> Path:
        if self.kind == "group":
            return group_path(root, self.group)
        if self.kind == "report":
            return report_path(root, self.group, self.project)
        return project_path(root, self.group, self.project)

    def render(self, root: str | Path) -> str:
        if self.kind == "group":
            return render_group(gather_group(root, self.group))
        if self.kind == "report":
            return render_report(gather_report(root, self.group, self.project))
        return render_project(gather_project(root, self.group, self.project))


def scope_for(root: str | Path, rel: str) -> Scope | None:
    """The scope a map path describes, or None when that scope does not exist.

    `groups/g/HARNESS.md` is the group's, `groups/g/projects/p/HARNESS.md` the
    project's, `.../reporting/HARNESS.md` the report's — and only while the
    directory each describes is there, so a rule that reaches a report map for
    a project with no `reporting/` gets nothing to judge rather than a map to
    demand.
    """
    root = Path(root)
    parts = rel.replace("\\", "/").split("/")
    if len(parts) < 3 or parts[0] != "groups" or parts[-1] != FILE:
        return None
    group = parts[1]
    if len(parts) == 3:
        return Scope("group", group) if (root / "groups" / group).is_dir() else None
    if len(parts) == 5 and parts[2] == "projects":
        pdir = root / "groups" / group / "projects" / parts[3]
        return Scope("project", group, parts[3]) if pdir.is_dir() else None
    if len(parts) == 6 and parts[2] == "projects" and parts[4] == "reporting":
        rdir = root / "groups" / group / "projects" / parts[3] / "reporting"
        return Scope("report", group, parts[3]) if rdir.is_dir() else None
    return None


def scopes(root: str | Path, group: str = "", project: str = "") -> list[Scope]:
    """Every HARNESS.md the tree calls for, narrowed by group and project.

    A project's scopes are itself and its report, when it has one. A group's are
    itself and every sister's. The report is a scope only while `reporting/`
    exists: a project that never opted into Evidence gets no map claiming it did.
    """
    root = Path(root)
    gdir = root / "groups"
    out: list[Scope] = []
    if not gdir.is_dir():
        return out
    groups = [group] if group else sorted(g.name for g in gdir.iterdir() if g.is_dir() and not g.name.startswith("."))
    for g in groups:
        if not project:
            out.append(Scope("group", g))
        for p in [project] if project else _projects_in(gdir / g):
            out.append(Scope("project", g, p))
            if (gdir / g / "projects" / p / "reporting").is_dir():
                out.append(Scope("report", g, p))
    return out


# ------------------------------------------------------------------ write ---
def write_scope(root: str | Path, scope: Scope) -> tuple[Path, bool]:
    """Write one map; return its path and whether it changed."""
    path = scope.path(root)
    content = scope.render(root)
    changed = not path.exists() or path.read_text(encoding="utf-8") != content
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path, changed


def write(root: str | Path, group: str = "", project: str = "") -> list[tuple[Scope, Path, bool]]:
    """Write every scope selected; return (scope, path, changed)."""
    return [(s, *write_scope(root, s)) for s in scopes(root, group, project)]


@dataclass
class Drift:
    scope: Scope
    missing: bool = False
    stale: bool = False
    diff: str = ""

    @property
    def ok(self) -> bool:
        return not (self.missing or self.stale)

    def __str__(self) -> str:
        if self.missing:
            verb = f"pf harness {self.scope.group} {self.scope.project}".rstrip()
            return f"{self.scope.label}: no harness map — run `{verb}`"
        if self.stale:
            return f"{self.scope.label}: harness map is stale — the harness changed since it was written\n{self.diff}"
        return f"{self.scope.label}: ok"


DIFF_LINES = 60


def _diff(committed: str, fresh: str) -> str:
    lines = list(
        difflib.unified_diff(
            committed.splitlines(), fresh.splitlines(), fromfile="committed", tofile="would render", lineterm="", n=1
        )
    )
    if len(lines) > DIFF_LINES:
        lines = [*lines[:DIFF_LINES], f"... {len(lines) - DIFF_LINES} more line(s)"]
    return "\n".join(lines)


def drift(root: str | Path, group: str = "", project: str = "") -> list[Drift]:
    """One verdict per scope; all `ok` when every committed map matches its territory."""
    out = []
    for s in scopes(root, group, project):
        d = Drift(s)
        path = s.path(root)
        if not path.exists():
            d.missing = True
        else:
            committed, fresh = path.read_text(encoding="utf-8"), s.render(root)
            d.stale = committed != fresh
            if d.stale:
                d.diff = _diff(committed, fresh)
        out.append(d)
    return out
