"""Skills, commands and subagents — written once as Claude plugins, reached by every harness.

The toolkits under `platform/toolkits/` are Claude Code plugins: 48 skills, the
power-tools commands (`/ship`, `/blast-radius`, …) and its read-only reviewer
subagents. A plugin is Claude's packaging, not the content's; every harness
this repo supports now reads the same `SKILL.md` format, and each has its own
file for a subagent. So the content stays where it is and this module renders
the packaging, the way `pf.harness` renders the MCP layer:

    skills      `.agents/skills/<name>` — the one directory Codex, Copilot (CLI,
                VS Code, cloud agent), Gemini CLI, Cursor, OpenCode and Junie
                all discover. Each entry is a relative symlink into the toolkit,
                so the skill's supporting files come with it and there is no
                copy to drift. A group's skills are linked under
                `groups/<g>/.agents/skills`, where only a session inside that
                group finds them — a sister group never does.

    commands    `.agents/skills/<command>/SKILL.md`, generated. Codex has
                deprecated prompt files for skills and Copilot CLI has neither,
                so a skill is the one form every harness can invoke by name.
                `$ARGUMENTS` is kept and defined in the header.

    subagents   per harness, in its own format, rendered by the harness's
                module (`pf.harnesses.<name>`, `Spec.agents`). A Claude agent
                with `disallowedTools: Write, Edit, …` is read-only everywhere,
                in whatever word that harness has for it.

Two skills sharing a name (they do: `add-anomaly-tests`) cannot both own
`.agents/skills/<name>`. Neither wins: both are published as
`<toolkit>-<name>`, as a generated pointer, because a symlink cannot rename the
`name:` inside the file it points at.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path

import yaml

TOOLKITS = "platform/toolkits"
COMMANDS = "platform/toolkits/power-tools/commands"
AGENTS = "platform/toolkits/power-tools/agents"
SKILLS_DIR = ".agents/skills"

GENERATED = "GENERATED by `pf context refresh` from {src} — do not hand-edit."
WRITE_TOOLS = {"Write", "Edit", "MultiEdit", "NotebookEdit"}


# ------------------------------------------------------------ frontmatter --
@dataclass(frozen=True)
class Doc:
    src: str  # repo-relative
    meta: dict
    body: str

    @property
    def name(self) -> str:
        return str(self.meta.get("name") or Path(self.src).stem)

    @property
    def description(self) -> str:
        return " ".join(str(self.meta.get("description") or "").split())


def read_doc(root: Path, rel: str) -> Doc:
    text = (root / rel).read_text(encoding="utf-8")
    meta: dict = {}
    body = text
    if text.startswith("---\n"):
        end = text.find("\n---", 4)
        if end != -1:
            try:
                meta = yaml.safe_load(text[4:end]) or {}
            except yaml.YAMLError:
                meta = {}
            body = text[end + 4 :].lstrip("\n")
    return Doc(rel, meta if isinstance(meta, dict) else {}, body)


def _docs(root: Path, rel_dir: str) -> list[Doc]:
    d = root / rel_dir
    if not d.is_dir():
        return []
    return [read_doc(root, f"{rel_dir}/{p.name}") for p in sorted(d.glob("*.md"))]


def readonly(doc: Doc) -> bool:
    raw = doc.meta.get("disallowedTools") or ""
    names = {t.strip() for t in (raw if isinstance(raw, list) else str(raw).split(","))}
    return bool(WRITE_TOOLS & names)


def frontmatter(fields: dict) -> str:
    return "---\n" + yaml.safe_dump(fields, sort_keys=False, allow_unicode=True, width=1000) + "---\n"


# ------------------------------------------------------------------ skills --
@dataclass(frozen=True)
class Skill:
    name: str  # the name it is published under
    src: Path  # the skill directory, repo-relative
    toolkit: str


def toolkit_skills(root: Path) -> list[Skill]:
    base = root / TOOLKITS
    found: list[Skill] = []
    if not base.is_dir():
        return found
    for tk in sorted(p for p in base.iterdir() if p.is_dir()):
        sd = tk / "skills"
        if not sd.is_dir():
            continue
        for s in sorted(p for p in sd.iterdir() if (p / "SKILL.md").is_file()):
            found.append(Skill(s.name, s.relative_to(root), tk.name))
    return found


def _split_collisions(skills: list[Skill], reserved: set[str]) -> tuple[list[Skill], list[Skill]]:
    counts: dict[str, int] = {}
    for s in skills:
        counts[s.name] = counts.get(s.name, 0) + 1
    plain = [s for s in skills if counts[s.name] == 1 and s.name not in reserved]
    renamed = [Skill(f"{s.toolkit}-{s.name}", s.src, s.toolkit) for s in skills if s not in plain]
    return plain, renamed


def skill_links(root: Path) -> dict[str, str]:
    """`{link path: relative target}` for every symlinked skill — the root
    mirror of the toolkits, and each group's own."""
    commands = {d.name for d in _docs(root, COMMANDS)}
    plain, _ = _split_collisions(toolkit_skills(root), commands)
    out = {f"{SKILLS_DIR}/{s.name}": os.path.relpath(root / s.src, root / SKILLS_DIR) for s in plain}
    groups = root / "groups"
    if groups.is_dir():
        for g in sorted(p for p in groups.iterdir() if p.is_dir()):
            sd = g / ".claude" / "skills"
            if not sd.is_dir():
                continue
            for s in sorted(p for p in sd.iterdir() if (p / "SKILL.md").is_file()):
                link = g / SKILLS_DIR / s.name
                out[link.relative_to(root).as_posix()] = os.path.relpath(s, link.parent)
    return out


def _pointer_skill(root: Path, s: Skill) -> str:
    doc = read_doc(root, f"{s.src.as_posix()}/SKILL.md")
    return (
        frontmatter({"name": s.name, "description": doc.description})
        + f"<!-- {GENERATED.format(src=s.src.as_posix() + '/SKILL.md')} -->\n\n"
        + f"This is the `{s.toolkit}` toolkit's `{doc.name}` skill, published under a longer name because\n"
        + "another toolkit has a skill with the same short name.\n\n"
        + f"Read `{s.src.as_posix()}/SKILL.md` and the files beside it, and follow it exactly.\n"
    )


def _command_skill(doc: Doc) -> str:
    fields: dict = {"name": doc.name, "description": doc.description}
    if str(doc.meta.get("disable-model-invocation", "")).lower() in ("yes", "true"):
        fields["disable-model-invocation"] = True
    return (
        frontmatter(fields)
        + f"<!-- {GENERATED.format(src=doc.src)} -->\n\n"
        + "> Invoked as a command. `$ARGUMENTS` below is whatever the person wrote after\n"
        + "> the command's name — empty if they wrote nothing.\n\n"
        + doc.body
    )


# --------------------------------------------------------------- subagents --
def readonly_line(doc: Doc) -> str:
    """For a harness whose agent format has no read-only switch: say it."""
    return "You are read-only: you never create, edit or delete a file. You report.\n\n" if readonly(doc) else ""


def generated_note(doc: Doc) -> str:
    return f"<!-- {GENERATED.format(src=doc.src)} -->\n\n"


# ----------------------------------------------------------------- targets --
def targets(root: Path) -> dict[str, str]:
    """Every generated text file: command skills, renamed skills, subagents."""
    root = Path(root)
    out: dict[str, str] = {}
    commands = _docs(root, COMMANDS)
    for d in commands:
        out[f"{SKILLS_DIR}/{d.name}/SKILL.md"] = _command_skill(d)
    _, renamed = _split_collisions(toolkit_skills(root), {d.name for d in commands})
    for s in renamed:
        out[f"{SKILLS_DIR}/{s.name}/SKILL.md"] = _pointer_skill(root, s)
    from pf.harnesses import specs

    formats = {pattern: render for s in specs() for pattern, render in s.agents.items()}
    for d in _docs(root, AGENTS):
        for pattern, render in formats.items():
            out[pattern.format(d.name)] = render(d)
    return out


def agent_names(root: Path) -> list[str]:
    return [d.name for d in _docs(root, AGENTS)]


# ------------------------------------------------------------------- links --
def check_links(root: Path) -> list[str]:
    root = Path(root)
    problems = []
    for rel, target in skill_links(root).items():
        p = root / rel
        if not p.is_symlink():
            problems.append(
                f"{rel} is missing — that skill is invisible to every harness but Claude; run `pf context refresh`"
            )
        elif str(p.readlink()) != target:
            problems.append(f"{rel} points at {p.readlink()}, not {target} — run `pf context refresh`")
    for d in _managed_dirs(root):
        for p in sorted(d.iterdir()):
            rel = p.relative_to(root).as_posix()
            if p.is_symlink() and rel not in skill_links(root):
                problems.append(f"{rel} links a skill that no longer exists — run `pf context refresh`")
    return problems


def _managed_dirs(root: Path) -> list[Path]:
    dirs = [root / SKILLS_DIR, *sorted((root / "groups").glob(f"*/{SKILLS_DIR}"))]
    return [d for d in dirs if d.is_dir()]


def write_links(root: Path) -> list[Path]:
    root = Path(root)
    want = skill_links(root)
    changed: list[Path] = []
    for rel, target in want.items():
        p = root / rel
        if p.is_symlink() and str(p.readlink()) == target:
            continue
        p.parent.mkdir(parents=True, exist_ok=True)
        if p.is_symlink() or p.is_file():
            p.unlink()
        elif p.exists():
            continue  # a real directory someone put here: not ours to remove
        p.symlink_to(target, target_is_directory=True)
        changed.append(p)
    for d in _managed_dirs(root):
        for p in d.iterdir():
            if p.is_symlink() and p.relative_to(root).as_posix() not in want:
                p.unlink()
                changed.append(p)
    return changed
