"""What the test suite guards, as an index rather than 4,000 lines to read.

An agent asking "where is policy layering tested" had one way to find out:
list the tests directory and open files until one matched. Eighteen files and
~3,900 lines, to answer a question whose answer is a filename.

This builds the index instead, from the suite itself. Each test file already
carries a one-line docstring saying what it covers — that line is the index
entry, so the index cannot drift from the tests the way a hand-written table
would. Same rule the rest of the repo follows: everything is a projection,
never a parallel hand-maintained file.

The directory is the other half. A test's *location* names the part of the
platform it guards, using the vocabulary `CLAUDE.md` already uses, so an agent
that has read the router already knows where to look.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from pathlib import Path

#: What each group guards, in the router's own vocabulary. A directory that
#: appears in the suite but not here still indexes — it just has no gloss, which
#: is the nudge to either name it properly or fold it into a group that exists.
GROUPS: dict[str, str] = {
    "ontology": "what things mean, and what must hold of them",
    "graph": "the knowledge graph and the always-on context tier",
    "capabilities": "the seams a feature arrives through",
    "onboarding": "bringing an external project in",
    "gate": "what blocks a merge",
}


@dataclass
class TestFile:
    path: Path              # repo-relative, for anything that reports a location
    #: Relative to the tests directory — what the index links to, because the
    #: index lives *in* that directory. Linking a repo-relative path from there
    #: produces `platform/tests/platform/tests/...`, and a bare filename links to
    #: a sibling that does not exist once the file is inside a group.
    rel: Path
    group: str
    subject: str            # first line of the module docstring
    tests: int
    lines: int
    #: Modules under `pf.` this file imports — what it actually exercises.
    covers: tuple[str, ...] = field(default_factory=tuple)


def _covers(tree: ast.Module) -> tuple[str, ...]:
    """`pf.*` modules imported anywhere in the file, including inside a test.

    Function-local imports are deliberate throughout this suite — a test that
    imports `pf.scaffold.bootstrap` inside the test body is still a test of
    bootstrap, and an index built only from top-level imports would miss it.
    """
    out: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and (node.module or "").startswith("pf"):
            out.add(node.module or "")
        elif isinstance(node, ast.Import):
            out.update(a.name for a in node.names if a.name.startswith("pf"))
    return tuple(sorted(out))


def scan(tests_dir: str | Path) -> list[TestFile]:
    """Every test file in the suite, with what it says it covers."""
    root = Path(tests_dir)
    repo = root.parent.parent
    out: list[TestFile] = []
    for p in sorted(root.rglob("test_*.py")):
        src = p.read_text()
        tree = ast.parse(src)
        doc = (ast.get_docstring(tree) or "").strip().split("\n")[0]
        n = sum(1 for x in ast.walk(tree)
                if isinstance(x, (ast.FunctionDef, ast.AsyncFunctionDef))
                and x.name.startswith("test_"))
        group = p.parent.name if p.parent != root else ""
        out.append(TestFile(
            path=p.relative_to(repo), rel=p.relative_to(root), group=group,
            subject=doc, tests=n, lines=len(src.splitlines()), covers=_covers(tree),
        ))
    return out


def render_index(files: list[TestFile]) -> str:
    """The index, as markdown. Deterministic — it is compared byte for byte."""
    by_group: dict[str, list[TestFile]] = {}
    for f in files:
        by_group.setdefault(f.group, []).append(f)

    total = sum(f.tests for f in files)
    lines = [
        "# What the suite guards",
        "",
        "GENERATED by `pf test index`. Do not hand-edit — `pf test check` fails",
        "the build when this file and the suite disagree, and the suite wins.",
        "",
        (f"{len(files)} files · {total} test functions · "
         f"`uv run pytest platform/tests`"),
        "",
        "Each directory names the part of the platform it guards, so a whole",
        "group can be run on its own: `uv run pytest platform/tests/<group>`.",
        "",
    ]

    for group in sorted(by_group, key=lambda g: (g not in GROUPS, g)):
        members = sorted(by_group[group], key=lambda f: f.path.name)
        gloss = GROUPS.get(group, "")
        n = sum(f.tests for f in members)
        heading = f"## `{group}/`" if group else "## (ungrouped)"
        lines += [f"{heading} — {gloss}" if gloss else heading, "",
                  f"*{len(members)} files, {n} tests*", "",
                  "| File | Guards | Tests |", "|---|---|---:|"]
        for f in members:
            lines.append(f"| [`{f.path.name}`]({f.rel.as_posix()}) | {f.subject} | {f.tests} |")
        lines.append("")

    lines += [
        "## Finding the right file without opening any",
        "",
        "```bash",
        "uv run pf test where policy      # which tests mention policy?",
        "uv run pf test where pf.kg.build # which tests import this module?",
        "```",
        "",
        "`pf test where` searches subjects, filenames and the `pf.*` modules each",
        "file imports — including imports inside a test body, which is where much",
        "of this suite does its importing.",
        "",
    ]
    return "\n".join(lines)


def where(files: list[TestFile], term: str) -> list[TestFile]:
    """Files whose subject, name or imported modules mention `term`."""
    t = term.lower()
    return [f for f in files
            if t in f.subject.lower()
            or t in f.path.name.lower()
            or any(t in m.lower() for m in f.covers)]


def index_path(tests_dir: str | Path) -> Path:
    return Path(tests_dir) / "README.md"


def drift(tests_dir: str | Path) -> str:
    """Empty when the committed index matches the suite; a reason when it does not.

    The index is only worth trusting while it is current. One generated before a
    test file was added is exactly as misleading as no index — it answers "where
    is that tested" with confident silence.
    """
    path = index_path(tests_dir)
    if not path.exists():
        return f"{path} does not exist; run `pf test index`"
    want = render_index(scan(tests_dir))
    if path.read_text() != want:
        return f"{path} is stale; run `pf test index`"
    return ""
