-- metric: active_customers (simple) — generated by `pf report build`
-- Customers with at least one active subscription.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
select
    created_at as metric_time,
    customer_segment,
    country_code,
    sum(case when is_active then 1 else 0 end) as active_customers
from main_marts.dim_customers
group by 1, 2, 3
order by 1
