-- metric: aov (ratio) — generated by `pf report build`
-- Revenue divided by succeeded payment count.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
-- Ratio rule: re-divide at the display grain —
--   sum(revenue) / sum(payment_count)
-- NEVER avg(aov). Components are carried for exactly that.
select
    paid_at as metric_time,
    payment_status,
    customer_segment,
    plan_tier,
    sum(amount) as revenue,
    count(payment_id) as payment_count,
    sum(amount) / nullif(count(payment_id), 0) as aov
from main_marts.fct_payments
where payment_status = 'succeeded'
group by 1, 2, 3, 4
order by 1
