-- metric: revenue_mom_growth (derived) — generated by `pf report build`
-- Month-over-month change in net revenue.
-- Do not edit. Change the metric in transform/models/semantic/, then rerun.
select
    paid_at as metric_time,
    payment_status,
    customer_segment,
    plan_tier,
    sum(amount) as revenue_mom_growth
from main_marts.fct_payments
where payment_status = 'succeeded'
group by 1, 2, 3, 4
order by 1
