-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit.
--
-- orders (orders) — an annotated mart with zero rows is broken
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{ config(tags=['expectations']) }}
{{ dbt_expectations.test_expect_table_row_count_to_be_between(
    ref('orders'), min_value=1) }}
