-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit.
--
-- dim_patients (one patient) — `patient_id` is the declared identity, so it must identify
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{ config(tags=['expectations']) }}
{{ dbt_expectations.test_expect_column_values_to_be_unique(
    ref('dim_patients'), 'patient_id') }}
