-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit.
--
-- fct_registry_annual (one statistic x year x sex x ICD-10 group) — `statistic_id` is the declared identity, so it must identify
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{ config(tags=['expectations']) }}
{{ dbt_expectations.test_expect_column_values_to_be_unique(
    ref('fct_registry_annual'), 'statistic_id') }}
