-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit.
--
-- fct_registry_annual (one statistic x year x sex x ICD-10 group) — an annotated mart with zero rows is broken
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{ config(tags=['expectations']) }}
{{ dbt_expectations.test_expect_table_row_count_to_be_between(
    ref('fct_registry_annual'), min_value=1) }}
