"""Evidence — the reporting layer, as a Tool.

Evidence was wired in before the `Tool` seam existed, and it is the example the
seam's docstring gives of why the seam was needed: seven places touched to add
one tool. This module folds those seven into one declaration. Nothing about
what Evidence *does* changes — `pf.projections.evidence` still compiles every
page from a metric, `report_audit` still scores the result — only where the
wiring lives.

What the declaration carries:

  * **capability** — the files, settings and gate rules `reporting/` needs.
    Moved here from `pf.capabilities` verbatim; same name, so `pf new-project
    --with evidence` and every existing `tools.yaml` keep working.
  * **bootstrap** — regenerate the project from the semantic layer. The same
    code the `reporting` bootstrap step ran; that step now defers to this.
  * **dagster** — a `reporting` asset downstream of the marts, with the audit
    score as metadata, so a metric change shows its page going stale.
  * **surface** — the dev server, for `pf ui` → Review to embed.
  * **health** — Node 20. Evidence 40 does not build on Node 24, and "installed"
    was never the question; "builds" is.
  * **loops** — `dashboard-coverage`, contributed here rather than listed in
    the registry. A loop about the reporting layer belongs to the reporting
    tool, and disappears with it.
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path
from typing import Any

from pf.capabilities import Capability
from pf.tools.spec import DbtBinding, Requirement, Surface, Tool, ToolContext, ToolContribution

README = """\
# Reporting — Evidence BI

BI-as-code for **{{group}}/{{project}}**. Generated by `pf report build`, never
hand-maintained.

    dbt marts -> MetricFlow metrics -> MDL -> queries/metrics/*.sql -> pages/*.md

## The one rule

**Pages never restate business logic.** Every number traces to a metric compiled
into `queries/metrics/`. If a dashboard needs a figure that does not exist, the
fix is a metric definition in `transform/models/semantic/`, then `pf report build`
— not SQL in a page. Two pages filtering differently is how one company ends up
with two revenues.

## Ratio metrics

Ratio queries carry their numerator and denominator so a page re-divides at its
own grain: `sum(num) / sum(den)`. **Never `avg(ratio)`** — it is wrong at every
grain except the one it was computed at, and it is the most common BI bug there is.

## Commands

```bash
pf report build {{group}} {{project}}    # regenerate from the semantic layer
pf report audit {{group}} {{project}}    # mechanical quality score
pf ask {{group}} {{project}} "revenue by month"   # the same metrics, as a question
cd reporting && npm install && npm run sources && npm run dev
```

### Node version

Use **Node 20** (`.nvmrc` is committed). Evidence 40 does not build on Node 24 /
npm 11 — verified by building a pristine `evidence-dev/template`, which fails the
same way, so this is Evidence's supported-runtime boundary rather than anything
about this project. `npm run sources` and `npm run dev` work on newer Node;
`npm run build` needs 20. `pf tool doctor` checks.

## What is generated vs yours

| Generated — do not edit | Yours |
|---|---|
| `queries/metrics/*.sql` | extra pages you write by hand |
| `pages/index.md`, `pages/metrics/*.md` | `components/` |
| `sources/*/`, `evidence.config.yaml` | narrative text in generated pages* |

*Regenerating overwrites generated pages. Put durable narrative in a page you
own, or in the metric `description` so it survives.
"""

GITIGNORE = """\
.evidence/
build/
node_modules/
static/data/
"""

CAPABILITY = Capability(
    name="evidence",
    description="Evidence BI reporting layer, generated from the semantic layer.",
    files={
        "reporting/README.md": README,
        "reporting/.gitignore": GITIGNORE,
    },
    settings={
        "permissions": {"allow": [
            "Bash(pf report:*)", "Bash(pf ask:*)",
            "Bash(npm run dev:*)", "Bash(npm run build:*)",
            "Bash(npm run sources:*)",
        ]},
        "enabledPlugins": ["evidence-bi@platform"],
    },
    gate={
        # Generated artefacts and build output. Editing a compiled metric
        # query is how a page silently stops matching its metric definition.
        "denylist": [
            "**/reporting/queries/metrics/**",
            "**/reporting/.evidence/**",
            "**/reporting/build/**",
            "**/reporting/node_modules/**",
        ],
        "impact_required": ["**/reporting/pages/**"],
    },
    default_enabled=True,
)

DEFAULT_PORT = 3000
NODE_MAJOR = 20


# ---------------------------------------------------------------- helpers --
def reporting_dir(project_dir: Path) -> Path:
    return project_dir / "reporting"


def has_reporting(project_dir: Path) -> bool:
    return reporting_dir(project_dir).exists()


def node_version() -> tuple[int, ...] | None:
    node = shutil.which("node")
    if not node:
        return None
    try:
        out = subprocess.run([node, "--version"], capture_output=True, text=True,
                             timeout=10).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    m = re.match(r"v?(\d+)\.(\d+)\.(\d+)", out)
    return tuple(int(x) for x in m.groups()) if m else None


def health() -> dict[str, Any]:
    """Builds, not merely installed. Node 20 is Evidence 40's runtime boundary."""
    v = node_version()
    if v is None:
        return {"ok": False, "detail": "node not found — install Node 20 (`.nvmrc`)"}
    if v[0] != NODE_MAJOR:
        return {"ok": False,
                "detail": f"node {'.'.join(map(str, v))} — Evidence 40 builds on Node "
                          f"{NODE_MAJOR} only (`nvm use`)"}
    return {"ok": True, "detail": f"node {'.'.join(map(str, v))}"}


# -------------------------------------------------------------- bootstrap --
def bootstrap_project(root: Path, group: str, project: str,
                      project_dir: Path, config: dict[str, Any]) -> Any:
    """Regenerate the reporting layer. Skipped where it was never opted into."""
    from pf.scaffold.bootstrap import StepResult

    if not has_reporting(project_dir):
        return StepResult("evidence", "skipped", "no reporting/ (`pf tool enable evidence`)")
    from pf.projections.evidence import build

    r = build(project_dir, group, project)
    detail = f"{r['metrics']} metric(s), {r['pages']} page(s)"
    if not r["metrics"]:
        detail += " · no metrics in the semantic layer yet"
    return StepResult("evidence", "ok", detail)


# ---------------------------------------------------------------- dagster --
def dagster_assets(ctx: ToolContext) -> ToolContribution:
    """The reporting layer as an asset downstream of the marts it renders."""
    from dagster import AssetKey, MetadataValue, asset

    project_dir = Path(ctx.project_dir)
    if not has_reporting(project_dir):
        return ToolContribution()
    from pf.projections.evidence import collect_metrics

    prefix = ctx.project.replace("-", "_")
    models = sorted({m.model for m in collect_metrics(project_dir) if m.model})
    deps = [AssetKey([prefix, m]) for m in models]

    @asset(
        name="reporting",
        key_prefix=[prefix],
        group_name="reporting",
        deps=deps,
        description="Evidence pages compiled from the semantic layer; audited on build.",
        compute_kind="evidence",
        metadata={"dagster/kind": "evidence", "tool": "evidence"},
    )
    def _reporting(context) -> None:  # noqa: ANN001 — see dagster_runtime note
        from pf.projections.evidence import build
        from pf.projections.report_audit import audit

        r = build(project_dir, ctx.group, ctx.project)
        score, findings = audit(project_dir)
        context.add_output_metadata({
            "metrics": r["metrics"], "pages": r["pages"], "score": score,
            "errors": sum(1 for f in findings if f.severity == "error"),
            "path": MetadataValue.path(str(reporting_dir(project_dir))),
        })

    return ToolContribution(assets=[_reporting])


# ------------------------------------------------------------------ loops --
def loops() -> dict[str, tuple[Any, Any]]:
    """The loop this tool owns. Returned as {name: (LoopSpec, body)}."""
    from pf.loops.runner import LoopRun, LoopSpec

    spec = LoopSpec(
        name="dashboard-coverage",
        description="Score the reporting layer; find metrics no page shows and pages "
                    "referencing metrics that do not exist.",
        autonomy="L1", cadence="daily", token_budget=0, writes=False,
    )

    def body(root: Path, group: str, project: str, run: LoopRun) -> list[str]:
        from pf.projections.report_audit import audit as audit_report

        pdir = root / "groups" / group / "projects" / project
        if not has_reporting(pdir):
            return []
        score, findings = audit_report(pdir)
        out = [str(f) for f in findings if f.severity in ("error", "warning")]
        if score < 90:
            out.insert(0, f"report score {score}/100 — run the dashboard-loop skill")
        return out

    return {spec.name: (spec, body)}


# -------------------------------------------------------------------- cli --
def register_commands(app: Any) -> None:
    """`pf tool evidence …` — the same three verbs `pf report` offers."""
    import typer
    from rich.console import Console

    console = Console()
    ev_app = typer.Typer(help="Evidence: the reporting layer.")

    def _pdir(group: str, project: str) -> Path:
        from pf.cli import pdir
        return pdir(group, project)

    @ev_app.command("build")
    def cmd_build(group: str, project: str) -> None:
        """Regenerate the Evidence project from the semantic layer."""
        from pf.projections.evidence import build
        r = build(_pdir(group, project), group, project)
        console.print(f"[green]✓[/] {r['path']} · {r['metrics']} metric(s) · {r['pages']} page(s)")

    @ev_app.command("audit")
    def cmd_audit(group: str, project: str) -> None:
        """Mechanical quality score for the reporting layer."""
        from pf.projections.report_audit import audit
        score, findings = audit(_pdir(group, project))
        for f in findings:
            console.print(f"  {f}")
        console.print(f"score {score}/100")
        raise typer.Exit(1 if any(f.severity == "error" for f in findings) else 0)

    @ev_app.command("doctor")
    def cmd_doctor() -> None:
        h = health()
        console.print(("[green]✓[/] " if h["ok"] else "[red]✗[/] ") + h["detail"])
        raise typer.Exit(0 if h["ok"] else 1)

    app.add_typer(ev_app, name="evidence")


TOOL = Tool(
    name="evidence",
    title="Evidence",
    summary="Reporting layer: every page compiled from a governed metric.",
    url="https://github.com/evidence-dev/evidence",
    scope=frozenset({"project", "group"}),
    capability=CAPABILITY,
    default_enabled=True,
    # The projection needs nothing installed; only the dev server needs Node.
    offline=True,
    requires=(Requirement("binary", "node", "Node 20 — see reporting/README.md"),
              Requirement("binary", "npm", "ships with Node")),
    dbt=DbtBinding(needs_manifest=True,
                   artefacts=("reporting/queries/metrics", "reporting/pages")),
    surface=Surface(port=DEFAULT_PORT, path="/", embeddable=True,
                    start=("npm", "run", "dev", "--prefix", "{project_dir}/reporting"),
                    health="/"),
    health="pf.tools.evidence:health",
    bootstrap="pf.tools.evidence:bootstrap_project",
    dagster="pf.tools.evidence:dagster_assets",
    commands="pf.tools.evidence:register_commands",
    loops="pf.tools.evidence:loops",
    stack_layer={
        "layer": "reporting", "title": "Reporting (Evidence)",
        "upstream": "evidence-bi", "toolkits": ["evidence-bi", "viz-standards"],
        "artefacts": "reporting/pages/**", "node_kinds": ["Metric"],
    },
)
