"""dbt-expectations — declared data quality, with a generated floor.

The dbt-expectations package (metaplane's continuation of calogica's) gives a
dbt project Great Expectations' vocabulary as native dbt tests:
`expect_column_values_to_be_between`, `expect_table_row_count_to_be_between`,
sixty-odd more. It is macros only — installing it changes nothing until a test
names it — which makes it the perfect *capability* and a useless *checkbox*:
a package nobody's schema files mention is coverage that does not exist.

So this tool does two things:

  1. **Declares the package** in every enabled project's `packages.yml`, so
     any model yml in the project can use the full vocabulary immediately.
     That is the pluggable half — one `tools.yaml` line per family.

  2. **Generates a floor of expectations from the ontology**, the same move
     `pf.tools.recce` makes for review checks. The chain is identical:
     `annotations.yaml` maps columns to roles, the knowledge graph carries the
     resolved role and PII flag per mart column, and this module translates
     what the ontology *asserts* into tests that hold it:

         the mart's grain exists     -> row count >= 1
         an identity key identifies  -> unique, and never null

     Nothing else is generated, deliberately. A money column may be negative
     (credits), a category set drifts legitimately (recce watches that), and a
     range guessed from sampled data is a false positive on a timer. The
     generated floor asserts only what the ontology already claims to be true;
     everything sharper is a judgement, and judgements belong in the model's
     own yml where a human signs them.

## Where the tests live, and how they run

Generated tests are *singular* tests in `transform/tests/expectations/`, one
file per expectation, each calling the package's generic test macro (dbt
compiles `{% test x %}` to a callable macro `test_x`; passing `ref()` and the
column explicitly renders the same failing-rows query the yml form would).
Singular files rather than yml patches because dbt allows one patch per model
and the projects already own theirs — a generated patch would collide with a
human's, and merging into a human's file is exactly what generation must never
do.

They run wherever dbt tests run — `pf seed`, `dbt build`, the Dagster assets —
and every result lands in Elementary's history like any other test, which is
how the two tools compose. There is no separate runner to schedule and no
Dagster hook here: a test that is part of the project needs neither.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pf.capabilities import Capability
from pf.tools import dbtproject
from pf.tools.spec import DbtBinding, Requirement, Tool

PACKAGE = "metaplane/dbt_expectations"
#: 0.10.4 is the first metaplane release; the minor is where the macro
#: vocabulary is stable.
PACKAGE_VERSION = [">=0.10.4", "<0.11.0"]
#: Directory of generated singular tests, relative to the dbt project.
TESTS_DIR = "tests/expectations"
#: First line of every file this module writes. Regeneration deletes stale
#: files by this marker and only by it, so a hand-written singular test that
#: strays into the directory is left alone rather than mown down.
MARKER = "-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit."


# ------------------------------------------------------------------ paths --
def dbt_dir(project_dir: Path) -> Path:
    return Path(project_dir) / "transform"


def tests_dir(project_dir: Path) -> Path:
    return dbt_dir(project_dir) / TESTS_DIR


def ensure_package(project_dir: Path, version: list[str] | None = None) -> bool:
    return dbtproject.ensure_package(dbt_dir(project_dir), PACKAGE,
                                     version or PACKAGE_VERSION)


# ------------------------------------------------------------------ models --
@dataclass(frozen=True)
class MartModel:
    """One annotated mart, in the ontology's terms."""

    name: str
    grain: str
    #: First identity column that is safe to test on, or empty. PII is
    #: excluded even from a uniqueness test: a test failure prints the
    #: offending rows into logs and Elementary's results tables, both durable.
    key: str


def _annotated_marts(project_dir: Path) -> list[MartModel]:
    """Every mart the knowledge graph can vouch for.

    The same read `pf.tools.recce` does for review checks, kept as this
    module's own copy so deleting either tool loses that tool and nothing
    else. A missing or half-built graph yields nothing and the caller degrades
    to declaration-only — the package is still installed, the floor waits for
    `pf kg build`.
    """
    gp = Path(project_dir) / "kg" / "graph.duckdb"
    if not gp.exists():
        return []
    try:
        from pf.kg.store import open_graph
        from pf.ontology.model import load_ontology
    except Exception:  # noqa: BLE001 — graph tooling missing is not fatal here
        return []

    out: list[MartModel] = []
    try:
        onto = load_ontology()
        with open_graph(gp, read_only=True) as g:
            for m in g.nodes("Model"):
                if (m.layer or "") != "marts":
                    continue
                key = ""
                annotated = False
                for e in g.out_edges(m.id):
                    col = g.node(e.dst)
                    if col is None or col.kind != "Column":
                        continue
                    props = col.props or {}
                    role_name = props.get("role") or ""
                    role = onto.roles.get(role_name)
                    if not role_name:
                        continue
                    annotated = True
                    pii = bool(props.get("pii")) or bool(role and role.pii)
                    if not key and role_name == "natural_key" and not pii:
                        key = col.name
                if annotated:
                    out.append(MartModel(
                        name=m.name,
                        grain=(m.props or {}).get("grain", ""),
                        key=key,
                    ))
    except Exception:  # noqa: BLE001 — a broken graph must not break bootstrap
        return []
    return sorted(out, key=lambda r: r.name)


# ---------------------------------------------------------------- generate --
_HEADER = """\
{marker}
--
-- {model} ({subject}) — {claim}
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{{{ config(tags=['expectations']) }}}}
"""


def _test(model: str, subject: str, claim: str, call: str) -> str:
    return _HEADER.format(marker=MARKER, model=model, subject=subject,
                          claim=claim) + call + "\n"


def generate_tests(project_dir: Path) -> dict[str, str]:
    """Filename -> singular-test SQL, for every annotated mart.

    The vocabulary is dbt-expectations' own generic tests, invoked as macros
    (`test_<name>`) so the assertion reads exactly as it would in a model yml.
    """
    out: dict[str, str] = {}
    for m in _annotated_marts(project_dir):
        subject = m.grain or m.name
        out[f"{m.name}__not_empty.sql"] = _test(
            m.name, subject, "an annotated mart with zero rows is broken",
            "{{ dbt_expectations.test_expect_table_row_count_to_be_between(\n"
            f"    ref('{m.name}'), min_value=1) }}}}")
        if m.key:
            out[f"{m.name}__{m.key}__unique.sql"] = _test(
                m.name, subject,
                f"`{m.key}` is the declared identity, so it must identify",
                "{{ dbt_expectations.test_expect_column_values_to_be_unique(\n"
                f"    ref('{m.name}'), '{m.key}') }}}}")
            out[f"{m.name}__{m.key}__not_null.sql"] = _test(
                m.name, subject,
                "an identity that is null identifies nothing",
                "{{ dbt_expectations.test_expect_column_values_to_not_be_null(\n"
                f"    ref('{m.name}'), '{m.key}') }}}}")
    return out


README = """\
# Generated expectations

Every `*.sql` here that opens with a GENERATED marker is derived from the
ontology — `contracts/annotations.yaml` maps columns to roles, and
`pf bootstrap` translates what those roles assert into dbt-expectations tests.
Edit the roles, not these files; regeneration discards edits and deletes tests
whose model or role has gone.

Sharper expectations — value ranges, accepted sets, distributions — are
judgements about one table. Declare them in that model's own yml with the
full dbt-expectations vocabulary (the package is installed project-wide).
"""


def write_tests(project_dir: Path) -> tuple[int, int, int]:
    """Write the generated tests. Returns (written, unchanged, removed).

    The directory is managed by marker: files this run generates are written
    (only when their content moved, so `git status` stays honest), previously
    generated files whose source is gone are deleted, and anything without the
    marker is somebody's hand-written test and is not touched.
    """
    d = tests_dir(project_dir)
    generated = generate_tests(project_dir)
    written = unchanged = removed = 0

    if generated:
        d.mkdir(parents=True, exist_ok=True)
        readme = d / "README.md"
        if not readme.exists() or readme.read_text() != README:
            readme.write_text(README)

    for name, body in generated.items():
        target = d / name
        if target.exists() and target.read_text() == body:
            unchanged += 1
            continue
        target.write_text(body)
        written += 1

    if d.exists():
        for f in d.glob("*.sql"):
            if f.name in generated:
                continue
            try:
                ours = f.read_text().startswith(MARKER)
            except OSError:
                continue
            if ours:
                f.unlink()
                removed += 1
    return written, unchanged, removed


# --------------------------------------------------------------- bootstrap --
def bootstrap_project(root: Path, group: str, project: str,
                      project_dir: Path, config: dict[str, Any]) -> Any:
    """Idempotent per-project setup. Called by `pf bootstrap`."""
    from pf.scaffold.bootstrap import StepResult

    if not (dbt_dir(project_dir) / "dbt_project.yml").exists():
        return StepResult("expectations", "skipped", "no dbt project")

    # `tools.yaml` config, per family or entity:
    #
    #   tools:
    #     expectations:
    #       enabled: true
    #       config:
    #         version: [">=0.10.4", "<0.11.0"]
    #         floor: true      # false = vocabulary only, no generated tests —
    #                          # for a project whose coverage is entirely
    #                          # hand-declared and wants no second author
    version = list(config.get("version") or PACKAGE_VERSION)
    added_pkg = ensure_package(project_dir, version)

    if not config.get("floor", True):
        return StepResult(
            "expectations", "ok",
            ("package declared" if added_pkg else "package present")
            + " · floor disabled by config")
    written, unchanged, removed = write_tests(project_dir)

    bits = ["package declared" if added_pkg else "package present"]
    total = written + unchanged
    if total:
        bits.append(f"{total} generated expectation(s)"
                    + ("" if written or removed else ", unchanged"))
        if removed:
            bits.append(f"{removed} stale removed")
    else:
        # Not a failure: the floor is derived from the graph, and a project
        # that has not built one yet still gets the vocabulary.
        bits.append("no annotated marts in the graph (`pf kg build`) — "
                    "vocabulary available, floor not generated")
    return StepResult("expectations", "ok", " · ".join(bits))


# ------------------------------------------------------------- capability --
EXPECTATIONS_DOCS = """\
# dbt-expectations — {{group}}/{{project}}

Great Expectations' vocabulary as native dbt tests, installed project-wide.
Use any of it in a model's yml:

```yaml
models:
  - name: fct_payments
    columns:
      - name: amount
        data_tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              row_condition: "status = 'captured'"
```

## The generated floor

`transform/tests/expectations/` holds tests derived from the ontology — the
same chain that generates recce checks:

    annotations.yaml   column -> role
    knowledge graph    role + pii, resolved per mart column
    this tool          what the role asserts -> a dbt-expectations test

An annotated mart must not be empty; its declared identity must be unique and
never null. That is all — anything sharper is a judgement about one table, so
it belongs in that model's yml (above), not in a generator.

**Edit the roles, not the generated files.** `pf bootstrap` (or
`pf tool expectations config {{group}} {{project}}`) regenerates them.

## Running

They are ordinary dbt tests: `pf seed`, `dbt build` and the Dagster assets run
them; `pf tool expectations run {{group}} {{project}}` runs just the generated
floor (`tag:expectations`). Results land in Elementary's history with every
other test.
"""

CAPABILITY = Capability(
    name="expectations",
    description="dbt-expectations vocabulary project-wide, plus an "
                "ontology-derived floor of generated tests.",
    files={"docs/expectations.md": EXPECTATIONS_DOCS},
    settings={
        "permissions": {"allow": [
            "Bash(pf tool expectations:*)",
        ]},
    },
    gate={
        # Generated from the ontology roles: a hand edit is a silent fork from
        # the declaration everything else reads — recce.yml's argument exactly.
        "impact_required": [f"**/transform/{TESTS_DIR}/**"],
    },
)


# ------------------------------------------------------------------- tool --
TOOL = Tool(
    name="expectations",
    title="dbt-expectations",
    summary="Great Expectations-style dbt tests, project-wide, with an "
            "ontology-derived generated floor.",
    url="https://github.com/metaplane/dbt-expectations",
    scope=frozenset({"project", "group"}),
    capability=CAPABILITY,
    default_enabled=True,
    # Declaration and generation are pure projections of files the project
    # already holds; requiring dbt here would make what gets scaffolded depend
    # on the machine that ran it.
    offline=True,
    requires=(
        Requirement("binary", "dbt", "uv sync"),
    ),
    dbt=DbtBinding(),
    bootstrap="pf.tools.expectations:bootstrap_project",
    commands="pf.tools.expectations:register_commands",
    # No dagster hook, deliberately: the generated tests are part of the dbt
    # project, so they already run inside the project's own dbt assets — a
    # second runner would be a second verdict on the same question.
    stack_layer={
        "layer": "quality", "title": "Quality (dbt-expectations)",
        "upstream": "dbt-expectations", "toolkits": [],
        "artefacts": f"transform/{TESTS_DIR}", "node_kinds": [],
    },
)


# -------------------------------------------------------------------- cli --
def register_commands(app: Any) -> None:
    """Attach `pf tool expectations ...`. Imported lazily by the CLI."""
    import typer
    from rich.console import Console

    console = Console()
    ex_app = typer.Typer(help="dbt-expectations: declared data quality, generated floor.")

    def _pdir(group: str, project: str) -> Path:
        from pf.cli import pdir
        return pdir(group, project)

    @ex_app.command("config")
    def cmd_config(group: str, project: str) -> None:
        """Regenerate the ontology-derived expectations."""
        d = _pdir(group, project)
        written, unchanged, removed = write_tests(d)
        total = written + unchanged
        if not total:
            console.print("[yellow]![/] no annotated marts in the graph — "
                          f"`pf kg build {group} {project}` first")
            return
        console.print(f"[green]✓[/] {tests_dir(d)} — {total} expectation(s)"
                      + (f", {removed} stale removed" if removed else "")
                      + ("" if written or removed else " [dim](unchanged)[/]"))

    @ex_app.command("run")
    def cmd_run(group: str, project: str,
                strict: bool = typer.Option(False, "--strict",
                                            help="exit non-zero on a failing expectation")) -> None:
        """Run just the generated floor (`dbt test --select tag:expectations`)."""
        from pf.runtime.dbt_runtime import dbt
        from pf.runtime.warehouse import Warehouse

        d = _pdir(group, project)
        wh = Warehouse.for_project(d, group, project)
        proc = dbt(d, "test", "--select", "tag:expectations",
                   duckdb_path=wh.path)
        ok = proc.returncode == 0
        mark = "[green]✓[/]" if ok else "[yellow]![/]"
        # dbt's own summary line is the useful part of its output.
        tail = "\n".join((proc.stdout or "").splitlines()[-8:])
        console.print(f"{mark} expectations {'passed' if ok else 'failed'}\n[dim]{tail}[/]")
        raise typer.Exit(1 if strict and not ok else 0)

    app.add_typer(ex_app, name="expectations")
