{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `mcx.contract_master` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: ExchangeContract · Grain: one MCX futures contract or option expiry chain
#}

with renamed as (
    select
        {{ pf_clean('contract_id', 'natural_key') }} as contract_id,
        {{ pf_clean('mcx_commodity', 'status_enum') }} as mcx_commodity,
        {{ pf_clean('contract_code', 'free_text') }} as contract_code,
        {{ pf_clean('instrument_type', 'status_enum') }} as instrument_type,
        {{ pf_clean('expiry_date', 'reference_date') }} as expiry_date,
        {{ pf_clean('is_traded_today', 'flag') }} as is_traded_today,
        _dlt_load_id
    from {{ source('mcx', 'contract_master') }}
)

select * exclude (_dlt_load_id)
from renamed
where contract_id is not null
{{ pf_dedupe('contract_id') }}
