{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `mcx.futures_bhavcopy` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: ContractSession · Grain: one MCX futures contract per trading day
#}

with renamed as (
    select
        {{ pf_clean('bhavcopy_id', 'natural_key') }} as session_id,
        {{ pf_clean('mcx_commodity', 'status_enum') }} as mcx_commodity,
        {{ pf_clean('contract_code', 'free_text') }} as contract_code,
        {{ pf_clean('instrument_type', 'status_enum') }} as instrument_type,
        {{ pf_clean('trade_date', 'event_time') }} as traded_at,
        {{ pf_clean('expiry_date', 'reference_date') }} as expiry_date,
        {{ pf_clean('open', 'unit_price') }} as open_price,
        {{ pf_clean('high', 'unit_price') }} as high_price,
        {{ pf_clean('low', 'unit_price') }} as low_price,
        {{ pf_clean('close', 'unit_price') }} as close_price,
        {{ pf_clean('previous_close', 'unit_price') }} as previous_close_price,
        {{ pf_clean('volume_lots', 'quantity') }} as volume_lots,
        {{ pf_clean('traded_quantity', 'quantity') }} as traded_quantity,
        {{ pf_clean('quantity_unit', 'unit_of_measure') }} as quantity_unit,
        {{ pf_clean('open_interest_lots', 'quantity') }} as open_interest_lots,
        {{ pf_clean('turnover_lakhs', 'money_amount') }} as turnover_lakhs,
        {{ pf_clean('extracted_via', 'status_enum') }} as extracted_via,
        {{ pf_clean('contract_id', 'foreign_key') }} as contract_id,  -- → ExchangeContract
        _dlt_load_id
    from {{ source('mcx', 'futures_bhavcopy') }}
)

select * exclude (_dlt_load_id)
from renamed
where session_id is not null
{{ pf_dedupe('session_id') }}
