{# GENERATED by `pf gen-staging` from contracts/annotations.yaml. #}
{#
  Staging contract: 1:1 with `gold_api.spot_prices` — one row in, one row out.
  Cleaning is applied here via role-driven macros and is NOT repeated downstream.
  Do not add joins, aggregation, or grain-changing filters to this model.
  Concept: PriceObservation · Grain: one precious metal per gold-api update
#}

with renamed as (
    select
        {{ pf_clean('spot_quote_id', 'natural_key') }} as spot_quote_id,
        {{ pf_clean('price', 'unit_price') }} as spot_price,
        {{ pf_clean('currency', 'currency_code') }} as currency_code,
        {{ pf_clean('quote_unit', 'unit_of_measure') }} as quote_unit,
        {{ pf_clean('updated_at', 'event_time') }} as quoted_at,
        {{ pf_clean('commodity_id', 'foreign_key') }} as commodity_id,  -- → Commodity
        _dlt_load_id
    from {{ source('gold_api', 'spot_prices') }}
)

select * exclude (_dlt_load_id)
from renamed
where spot_quote_id is not null
{{ pf_dedupe('spot_quote_id') }}
