-- GENERATED by `pf bootstrap` (pf.tools.expectations). Do not edit.
--
-- fct_payments (one payment attempt) — an identity that is null identifies nothing
-- Derived: annotations.yaml -> ontology role -> this expectation. Fix the
-- role, not this file; `pf tool expectations config` regenerates it.
{{ config(tags=['expectations']) }}
{{ dbt_expectations.test_expect_column_values_to_not_be_null(
    ref('fct_payments'), 'payment_id') }}
